### ISSUE TITLE
Server won't load

### ISSUE THREAD

**Issue by jbruett** [jadedcat/AS2Configs#10]
#### Condition:
after updating to 1.1.8 server files.  Update process I follow is: remove config, customnpcs, libraries, mods folders and forge jar from existing server.  Copy matching new folders/files into server directory using winscp.

#### Server files path:
/minecraft/as2/

#### ServerStart.sh contents:
java -server -Xms4096m -Xmx6144m -XX:PermSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweekGC -Dfml.queryResult=confirm -jar forge-1.7.10-10.13.1469-1.7.10-universal.jar nogui

[Crashlog](http://pastebin.com/Y5VQRAg7)

**Comment by shadowfacts** [comment]
Try manually downgrading [PackGuard](http://minecraft.curseforge.com/mc-mods/231369-packguard).

**Comment by DragoonPreston** [comment]
You need to upgrade to Java 8, if your using OpenJDK, OpenJDK 8 is available. I just had this problem and updating fixed it.

**Comment by shadowfacts** [comment]
> You need to upgrade to Java 8, if your using OpenJDK, OpenJDK 8 is available. I just had this problem and updating fixed it.

This is incorrect. While this version of PackGuard does require Java, this is only a bug.

**Comment by jbruett** [comment]
shadowfacts, is there a particular version that is suggested?  Packgaurd has 1.0 and 1.1

**Comment by shadowfacts** [comment]
PackGuard [1.3.0](http://minecraft.curseforge.com/mc-mods/231369-packguard/files/2250332) on CurseForge.

**Comment by jbruett** [comment]
so i was running PackGuard 1.2.0 when the crash occurred, your advice was to manually downgrade to 1.3.0, which honestly doens't make sense, but ok, i did it, running 1.3.0 i still get a similar crash issue.

[Crashlog](http://pastebin.com/fPg9qcpm)

**Comment by coolsquid** [comment]
Have an emergency hotfix: [PackGuard 1.3.1](http://minecraft.curseforge.com/mc-mods/231369-packguard/files/2251485/download).

**Comment by jbruett** [comment]
Just tried to upload this and restart the server and received another crash

[Crashlog](http://pastebin.com/RznfH2QP)

**Comment by coolsquid** [comment]
Update to [PackGuard 1.3.2](
http://minecraft.curseforge.com/mc-mods/231369-packguard/files/2251512/download).
Blame me, I'm a bit messy today.

2015-08-09 17:55 GMT+02:00 jbruett <notifications@github.com>:

**Comment by coolsquid** [comment]
Update to [PackGuard 1.3.2](http://minecraft.curseforge.com/mc-mods/231369-packguard/files/2251512/download). Blame me, I'm a bit messy today.

**Comment by pjfranke** [comment]
I can confirm that 1.3.2 does function on the below OK.

Ubuntu 14.04.01 LTS
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by jbruett** [comment]
PackGuard 1.3.2 fixed my issues as well, thanks for the continued follow up coolsquid, you rock!
