### ISSUE TITLE
Transfer Node (Items) not working for cobble gen

### ISSUE THREAD

**Issue by Vizix** [jadedcat/AS2Configs#100]
I tried it in both my actual world and a test world, the transfer node won't automine the cobble ):

**Comment by shadowfacts** [comment]
1. Do you have a World Interaction upgrade in the node?
2. Can you please post a couple screenshots of your setup?

**Comment by Vizix** [comment]
Oh no I don't, do I need that? Sorry I'm new to all things FTB and Agrarian Skies, the tutorial on it I saw on YouTube didn't show that. Is it AG specific?

**Comment by shadowfacts** [comment]
No, the World Interaction Upgrade requirement was added when Extra Utilities updated to 1.7.10. You may have been watching an outdated tutorial.
