### ISSUE TITLE
Aluminum not accepted by pulverizer?

### ISSUE THREAD

**Issue by punto-** [jadedcat/AS2Configs#103]
Since the smeltery in AS2 doesn't accept the broken ores that come out of the sifter directly, I set up an "assembly line" with an autopackager, a pulverizer, and a redstone furnace, so broken ores go in, and ingots come out. The problem is, the pulverizer is not accepting "Aluminum Ore Dust 1609", "Aluminum Ore Sand 1608" and "Aluminum Ore Gravel 1607". Everything else goes in, and produces the correspoding pulverized metal. Is this intended? I'm temporarily setting up a smeltery just to deal with these blocks. Thanks!

**Comment by MarshMilo100** [comment]
i can confirm this, it will be fixed next update.

**Comment by MarshMilo100** [comment]
also an issue for cobalt and ardite
