### ISSUE TITLE
Beheading seems not to work.

### ISSUE THREAD

**Issue by DarkPhily** [jadedcat/AS2Configs#104]
I got a Cleaver with 100% beheading, but wither skeletons and other mobs don'T drop their heads a 100%. Is it a bug or what'S the deal?

**Comment by MarshMilo100** [comment]
This is intended, wither skeletons are specifically excluded from the beheading effect. Because their heads are useful for spawning wither bosses rather than just decoration.
#close

**Comment by DarkPhily** [comment]
Ok, so is it just a thing in this pack or is this an overall thing from TC?

**Comment by MarshMilo100** [comment]
Normal tcon

**Comment by MarshMilo100** [comment]
I believe this is an option in the config as well
