### ISSUE TITLE
Crash on game startup

### ISSUE THREAD

**Issue by x1xHEADSHOTSx1x** [jadedcat/AS2Configs#105]
https://www.dropbox.com/s/t8367zikjmov5kc/crash-2015-09-07_21.32.55-server.txt?dl=0
Version - 1.1.13

I was initially using the version prior to this with the manual update to latest Blood Magic version. I crashed while I was crafting Bottled Taint. I was using the alchemical construct for auto crafting it. While it was auto-crafting I was in either an AE2 crafting terminal or the Thaumic AE Crafting Table, I cannot remember. After the crash the save will now not start on startup. Since I was in an older version I decided to update the pack and see if that would fix the error. Unfortunately that did not fix the issue. I still crash after I select my save and click "Play Selected World " button. Please advise me on steps to fix this issue  or let me know if I am S.O.L. Thanks.

**Comment by MarshMilo100** [comment]
Your quest book info has become corrupted, you must delete the quest book data within your save gamer world save folder

**Comment by x1xHEADSHOTSx1x** [comment]
So I need to delete the players.dat file in the HQM folder, which effectively deletes my world. :(

**Comment by pjfranke** [comment]
Yes and no.  If the issue is that your HQM quests got corrupted, then you do need to delete your HQM data.  You could just move it out from there to your desktop to see if that fixes the issue and lets you start your save, if not, it's something else.

> Curse\Minecraft\Instances\Agrarian Skies 2\saves\Morvy Cottage-Normal\HardcoreQuesting\players.dat

That file, or obviously a different spot if your game instance is named something else, and/or your save is named something else (which it should be)

Yes, this WILL reset your Quest progress.  No, it won't delete your world (or inventory).  It just resets HQM progress, so you'd need to use "/hqm edit" to get an OP book to re-progress to where you were at.  You'll end up with all the rewards again, so just toss them in the void or something.

**Comment by x1xHEADSHOTSx1x** [comment]
When I cut the players.dat file from the HQM folder in my save it deletes my world and starts me over on the beginning island.

**Comment by MarshMilo100** [comment]
Can you show a screenshot of the file, in the folder, that you are deleting? You may be removing the wrong file.

**Comment by x1xHEADSHOTSx1x** [comment]
Screen Shot of the HQM folder
https://www.dropbox.com/s/rklve9sao667v4u/AS2_Folder_ScreenShot.docx?dl=0

Screen Shot of the save file after removing the players.dat file
https://www.dropbox.com/s/f10i0xsvbr4hjxk/2015-09-09_22.25.31.png?dl=0

**Comment by MarshMilo100** [comment]
when you replace the players.dat file back into the save game folder, is the world you were playing in restored?

**Comment by x1xHEADSHOTSx1x** [comment]
When I replace the players.dat file the crash is restored, so I am guessing the world is restored. I cannot even see if the world is reloaded because the crash is immediate.

**Comment by x1xHEADSHOTSx1x** [comment]
Would you like me to upload my save file to drop box for testing on your end?

**Comment by MarshMilo100** [comment]
Or probably google drive would be even better.

**Comment by x1xHEADSHOTSx1x** [comment]
https://www.dropbox.com/sh/c9t32bgyvcww50l/AACO81CM4KNPYuGN4VNvqti4a?dl=0

**Comment by cblair91** [comment]
@x1xHEADSHOTSx1x Please update to the latest version and tell me if this is still occurring.

**Comment by cblair91** [comment]
No response from user. Closing.
