### ISSUE TITLE
Curse Launcher - launches AS2 as vanilla minecraft

### ISSUE THREAD

**Issue by Timostag** [jadedcat/AS2Configs#106]
I have been using the curse client to play AS2 without any problems, until today, when I tried to launch AS2 it opened plain old minecraft. All my AS2 files\folders are still there but I cannot get it to launch.

I have tried pulling my save folder and re-downloading AS2 and pulling it in the new profile, but I had the same issue with it opening Vanilla minecraft and not the mod pack.

I have also tried downloading other mod packs - all open the normal minecraft

Any ideas?

**Comment by enarkay** [comment]
I've been experiencing the same problem from a moment ago. Since it's all the modpacks and not just AS2, I'm assuming it's a CV launcher side problem so I've submitted a bug report. I recommend you do so as well.

**Comment by Timostag** [comment]
Yea Jadedcat has tweeted that they are looking into it

https://twitter.com/JadedcatWylde/status/641302702681624576?lang=en-gb

**Comment by Timostag** [comment]
This is now resolved - Mc launcher updated again and now the modpacks start again
