### ISSUE TITLE
No server files for pack update 1.1.13

### ISSUE THREAD

**Issue by Wdrussell1** [jadedcat/AS2Configs#107]
No server files for pack update 1.1.13.

Unable to find a package for this on the site or curse.

**Comment by pjfranke** [comment]
o.0

They're at the bottom of this page:
http://minecraft.curseforge.com/modpacks/225550-agrarian-skies-2/files/2253747

**Comment by Wdrussell1** [comment]
It needs to be updates in other places too then. Curse links to the wrong page and so does everything else.
