### ISSUE TITLE
Ag2 not opening

### ISSUE THREAD

**Issue by TdoubleT** [jadedcat/AS2Configs#108]
When i go to play agrarian skies 2 instead of opening the modded launcher its opening regular minecraft, its been working fine for ages ive tryed re downloading but i can no  longer play,
thanks for the help.

**Comment by TdoubleT** [comment]
version 1.1.13

**Comment by MarshMilo100** [comment]
This is a big with the curse voice launcher, an issue report has already been submitted to those guys.
