### ISSUE TITLE
Game Doesn't Load Due To Not Enough Space.

### ISSUE THREAD

**Issue by SlyScroll** [jadedcat/AS2Configs#109]
This is the Game Output taken from the launcher.

Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap
Java HotSpot(TM) Client VM warning: ignoring option PermSize=192m; support was removed in 8.0

**Comment by pjfranke** [comment]
How much RAM do you have allocated to the game, how much system RAM do you have, and how much free RAM does Task Manager show before you launch the game?

**Comment by SlyScroll** [comment]
I have 3.5GB allocated to Minecraft and my system has 4GB of RAM overall and it says on Task Manager that im using 1.75GB right now.

**Comment by pjfranke** [comment]
Figure out the issue there? :)
