### ISSUE TITLE
Incorrect questbook entry

### ISSUE THREAD

**Issue by Angani-Giza** [jadedcat/AS2Configs#11]
Running most recent version.
Under [Sky Farm] - [New Crops]

It asks for an artichoke, and the text says.. "To start, mutate artichoke by crossbreeding wheat and lettuce."

However, pressing "U" over a seed in inventory, as it tells you to do, results in...
For wheat. can mix with carrot, farranium, allium, sugarcane, and barley.
None of these mix to artichoke.
Lettuce.. mixes with celery, sugarcane, cabbage, broccoli, daisy, and lastly, asparagus.
Asparagus happens to mix with lettuce for artichoke, not wheat.
To get asparagus, barring quest bags, scallion and corn must be mixed.
For the corn side, mix rye and barley. wheat and sugarcane gives barley, wheat and barley gives rye.
Scallion is just sugarcane and carrot.

If you really want us to go through that, alright, no issue.
But it isn't wheat and lettuce.
I didn't actually check the NEI, as the quest book said what it was, and spent too long trying to get artichoke out of that.

-Angani-

**Comment by cblair91** [comment]
Confirmed.

Check NEI for the correct recipe.

**Comment by jadedcat** [comment]
Note to self: change text.
