### ISSUE TITLE
Emptying a bottle of water with the Fluid Transposer leaves an empty bucket in the output slot.

### ISSUE THREAD

**Issue by zanzammar** [jadedcat/AS2Configs#111]
Title says it all.  Makes for an extremely cheap way to get iron, looping bottles back into the transposer.

Using version 1.1.13 with no changes.  Behavior was observed in multiplayer.

**Comment by shadowfacts** [comment]
This is a bug due to a mod's (idk which one) improper use of the OreDictionary. The water bottle and water bucket are both registered with the same identifier. I suggest that the water bottle be removed from the OreDictionary via MineTweaker.

**Comment by Cre8torzn** [comment]
I am getting the same issue but in reverse. Putting in buckets (With milk) and getting glass bottles back. 

Using Version 1.1.13 with no changes. Multiplayer server.

**Comment by cblair91** [comment]
@Cre8torzn @zanzammar Any update to this with the latest version?

**Comment by cblair91** [comment]
No response from author, closing.
