### ISSUE TITLE
Wrong Forge?

### ISSUE THREAD

**Issue by us5013** [jadedcat/AS2Configs#112]
Ok so im sorta new to multimc, and i need to find the read me.txt for the new agrarian skies, and i just can't find it. This is probably a deep on me... but if someone can tell me the forge i need or where to find the reame.txt would be nice

**Comment by pjfranke** [comment]
Suppose if that was clearly documented it'd be useful.  Noted for next update to add that information to the alternative zip.

10.13.4.1469 is the one you want.
