### ISSUE TITLE
Custom NPCS bug

### ISSUE THREAD

**Issue by samiscool51** [jadedcat/AS2Configs#114]
hey found a bug were if you open the gui that alows you to trade with a Custom NPC, you mouse disappears for some reason

will get a photo to show you

thanks samiscool51

**Comment by Kopo942** [comment]
Can confirm in AgS2 version 1.1.13.

**Comment by samiscool51** [comment]
thanks adleast I'm not the only one that has this problem

**Comment by cblair91** [comment]
@samiscool51 / @Kopo942 Could you update, and tell me if this is still occurring?

**Comment by cblair91** [comment]
Aware of issue, mod author contacted.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#1
