### ISSUE TITLE
 trashcan bug

### ISSUE THREAD

**Issue by sjonnieh** [jadedcat/AS2Configs#115]

**Comment by sjonnieh** [comment]
so after some exploring i think i found the problem

![6](https://cloud.githubusercontent.com/assets/14278252/9855515/f63214f4-5b0e-11e5-91aa-62885f19249e.png)

this happened while i have a trashcan at the end.
but the trashcan isn't working anymore it seems to be  full

![7](https://cloud.githubusercontent.com/assets/14278252/9855573/67b67f2a-5b0f-11e5-853e-94b76124e694.png)

so the trashcan is the bug i believe

**Comment by pjfranke** [comment]
A trash can shouldn't hold items, it should just instantly void anything piped into it.  You can also use a QDS block as a trashcan, as it just voids anything sent to it whether there is a quest bound or not.  I don't think it's an issue with "not keeping up".

All the items seem to be collected around the sieves, not the trashcan/barrels.  That tells me that your ducts (even the impulse itemducts) are backstuffed and the servos won't pull out more items, or just they're not pulling fast enough.  Therefore the sieve inventories fill up, and start popping items into the world.  Do you have the stack sizes set to 64 on the servos?

Also, your item duct routing is less than idea.  You should avoid having loops in the system, instead using S-curves to avoid them.  Wrench the connections between the pipes to disconnect them.  I can't see the left-hand setup, but you'll need 4 extra impuse itemducts to make the right-hand system work, and have one path for items to follow, eventually ending up in the trashcan.  Plus, then it'll be at the end of the row no matter what, and you don't actually need the dense itemduct.

**Comment by sjonnieh** [comment]
the sieves are empthy for days and all of the sudden they werend and yes the servos are set to 64 both of them and i tried manually deleting them but didnt work but i replaced all trashcans maybe it will work now

**Comment by sjonnieh** [comment]
the same problem happend again but i think its dense itemd/trashcan who cant keep up

![2015-09-18_20 45 56](https://cloud.githubusercontent.com/assets/14278252/9968129/01d6376e-5e47-11e5-9023-d0437be166fd.png)
![2015-09-18_20 46 20](https://cloud.githubusercontent.com/assets/14278252/9968136/0854c150-5e47-11e5-9601-798c9bc27fb6.png)
![2015-09-18_20 48 33](https://cloud.githubusercontent.com/assets/14278252/9968140/13ae34c8-5e47-11e5-9186-7b034692f124.png)
![2015-09-18_20 49 19](https://cloud.githubusercontent.com/assets/14278252/9968147/1c76153a-5e47-11e5-9716-cf55642230bd.png)

i removed the dense one and put 2 trashcans maybe that helps
and the filters are white listed, and there are no loops possible

**Comment by samuelroy21** [comment]
you didnt follow any of his advice. that's your problem.

**Comment by cblair91** [comment]
User error :palm_tree:
