### ISSUE TITLE
Creepy doll + witch water for Ender Pearl problem. Won't allow more than one.

### ISSUE THREAD

**Issue by reiniken** [jadedcat/AS2Configs#116]
On my server we started to need ender pearls (and blaze rods) and we have found an issue in peaceful and using the dolls. I haven't attempted this with the thaumcraft dolls yet.

So we make a creepy doll and a barrel of witch water. it makes the ender pearl inside and we get it. Ok now for the next 10 dolls. We make it and then we try to take the ender pearl. Nothing happens. Try it again and the same thing. Ok so we try the angry doll for the blaze rod and we get 1, then try again and it doesn't give us one. We can OP in more pearls so I know that I can at least have extras there, but that's cheating. So is this a bug or working as intended?

edit: version 1.1.13
dolls from ex nihilo modpack Ex-Nihilo-1.38-45
edit 2: It seems I can make one per server restart and that's all

**Comment by pjfranke** [comment]
You're playing AS2 in peaceful mode...no mobs?  That doesn't really seem like it'd work.

I'll have to test Ex Nihilo standalone to see if that's the correct behavior in peaceful mode.

**Comment by reiniken** [comment]
Yeah in peaceful. We are switching off peaceful soon because it's a serious problem not getting ender pearls. I've looked through configs and theres nothing there that could change it, got to be code side.

**Comment by InsaneChemist** [comment]
Enderlilies or enderweeds? Specifically enderweeds, since once I got them to 10/10/10 I could power a 64x endergen with only about 300 of them.

**Comment by MarshMilo100** [comment]
i have tested ex nihilo in peaceful mode and i experienced the correct behavior. i cannot confirm your issue.
