### ISSUE TITLE
Tin gear crafting recipie

### ISSUE THREAD

**Issue by pazon12** [jadedcat/AS2Configs#118]
No matter what kind of tin I use, all crafting recipes for the tin gear will not work, but copper works just fine. Is there something I have to do, or something jaded has to fix.

(I really hope I'm not the only one...)

**Comment by MarshMilo100** [comment]
what exactly are you trying to craft with tin (and from which mod)?

**Comment by pazon12** [comment]
The title? Tin gears won't craft in a crafting grid, and from any mod, any kind of tin I use, it wont make either of the two tin gears in the game.

**Comment by MarshMilo100** [comment]
The tin gear from thermal expansion/foundation should only be craftable using a gear cast in a tinkers construct smeltery and the metal desired. The gear from forestry should still be craftable in a normal crafting grid.

**Comment by pazon12** [comment]
Neither works :/

**Comment by MarshMilo100** [comment]
Have you tried crafting it in a completely normal vanilla crafting table (not AE, tinkers or other)?

**Comment by pjfranke** [comment]
No followup response, closing issue.
