### ISSUE TITLE
aurigold not growing

### ISSUE THREAD

**Issue by statphantom** [jadedcat/AS2Configs#121]
I have successfully breed an aurigold plant however it will not grow (stays at 0%)

I have taken a set up to prove it is set up correctly, using bonemeal uses the bonemeal but the growth stays at 0%, same with watering can.

![2015-09-23_20 17 18](https://cloud.githubusercontent.com/assets/14803258/10043288/f3a2a900-6230-11e5-8b47-df34838727d2.png)

**Comment by samuelroy21** [comment]
when you hover over the crop sticks, does it say in WAILA "this plant is fertile and can grow"?

**Comment by MarshMilo100** [comment]
Lighting?

**Comment by statphantom** [comment]
Yes Lighting and Yes says fertile and can grow, after I signed off and logged in the next day it is working with watering can but not with bonemeal (my first log off-on attempt did nothing)

Date: Fri, 25 Sep 2015 17:17:23 -0700

**Comment by pjfranke** [comment]
Some crops are not able to be bonemealed; it seems you found one.

**Comment by statphantom** [comment]
water can wasn't growing it either at the time, I thought that was the case but when watering can didn't work either I posted, seems to be fixed now, PS: aurigold cant be bonemealed but goldenrod can? 

Date: Fri, 25 Sep 2015 21:21:21 -0700

**Comment by Trisscar05** [comment]
Having this issue as well, using bonemeal on the aurigold consumes it, but doesn't make it grow. Reloading the world and breaking/replacing the plant/crop/ore do not help, and I tend to question the idea that the metal plants cannot be bonemealed, since the redstodendron plants I used for breeding it CAN be bonemealed, but the aurigold plant cannot.
Watering can currently works however.

**Comment by statphantom** [comment]
My original problem was that watering can wasn't working either but it seems to be now, also some metal ones can some cant. aurigold (gold nuggets) can't, but goldrod (gold bars) can. 

Date: Thu, 1 Oct 2015 01:30:50 -0700

**Comment by Trisscar05** [comment]
Diamahlia and Ferranium seeds DO NOT grow when bonemealed, but bucking the trend of nugget crops being immune, Petinia CAN be bonemealed. Also I feel like I'm missing something, but why aren't there any copper or tin INGOT crops, just nugget ones?

**Comment by cblair91** [comment]
This appears to be an oversight by the player. (maybe secret stuff is secret?)
