### ISSUE TITLE
I just deleted all my Ingots haha

### ISSUE THREAD

**Issue by Gamejet** [jadedcat/AS2Configs#122]
So theres a little bug with AE2 and CompactStorage. I put an export bus from AE2 to a 1 Slot big CompactStorage Chest and the results were... suprising. It kept filling the chest even though it was already full and deleted the whole overflow. I tested this with other ways of automated itemflow and the results were the same. So the issue seems to be with automation to smaller than usual chests with CompactStorage. This is probably the wrong place but maybe a tweek to the configs can solve the issue.

**Comment by MarshMilo100** [comment]
Have you tested this issue in an instance with just ae2 and compact storage? If it is still a bug there, I would recommend reporting the bug to their respective mod authors.

**Comment by Gamejet** [comment]
As I said I tested different automated item systems (Itemducts -> Thermal Dynamics) as well and had the same results. So its an issue with CompactStorage. Yeah I will probably have to report that bug there as well.

**Comment by MarshMilo100** [comment]
This seems to be a compact storage bug. Report it to that mod authors bug trackers.

**Comment by Gamejet** [comment]
Okay so I posted that issue on the CompactStorage mod authors bug tracker. The result was quite disappointing: He was a little bit pissed because that bug got fixed already one month ago. I dont realy understand which the newest version of that mod realy is because it says "Last Update: 2.0.0.13" in fat letters when the downloadable file is called "[...]-release-2.1.0-[...]". Because of that Im not gonna open a new issue unless Im 100% certain the modpack is using the newest version of the mod. Anyways Im probably gonna delete that mod at all from my pack.

**Comment by shadowfacts** [comment]
If you use [this](http://minecraft.curseforge.com/mc-mods/223703-compactstorage/files/2256077) file you should be fine.

**Comment by MarshMilo100** [comment]
We will update the mod for the next update, for now you can manually update it yourself.

**Comment by pjfranke** [comment]
Updated to 2.1.0-lts-18 in pack version 1.1.14, closing.
