### ISSUE TITLE
Server start stalls at the same point every time

### ISSUE THREAD

**Issue by NudePenguin** [jadedcat/AS2Configs#126]
Here is a copy of where the start stalls every time:

http://pastebin.com/07vn0Bts

That is all the info I have for you as the console commands window only shows a limited history.

I have changed nothing from the original server file download from Jadedcat so I would have thought if there was an issue there would be more people who are having the same issue, but I just seems to be me. Any idea what is causing it?

**Comment by cblair91** [comment]
@NudePenguin Try using the latest version and see if this is still occurring.

**Comment by cblair91** [comment]
No response from user. Closing.
