### ISSUE TITLE
Worlds dont open.

### ISSUE THREAD

**Issue by daniptv** [jadedcat/AS2Configs#127]
Whenever I go to the singleplayer menu to select a world to load, and I click on 'Play Selected World' , the mod pack just sends me to the main menu. It never loads anything for any map that is on the mod pack. And even trying to create a whole new world, the same thing happens. Does anyone know if I have done something wrong? Any and all help is appreciated.

**Comment by MarshMilo100** [comment]
This is an odd bug involving multiple instances of minecraft being open. Try closing all instances of minecraft and restarting your computer.

**Comment by cblair91** [comment]
@daniptv Is this still occurring?

**Comment by cblair91** [comment]
No response from user. Closing.
