### ISSUE TITLE
Using Dolly on a CompactStorage chest may cause duplicate, 0 slot chest

### ISSUE THREAD

**Issue by ZPanic0** [jadedcat/AS2Configs#128]
When using a Dolly from JABBA to move a CompactStorage chest, sometimes a 0 slot black chest is created in addition to the one now held in the Dolly.

This is in version 1.1.13 of the pack according to the Curse Launcher.

![compactstorage bug](https://cloud.githubusercontent.com/assets/14856717/10121221/afa28fd2-64af-11e5-8e15-cb51c6203d32.png)

**Comment by pjfranke** [comment]
Known bug, we don't have a fix.  As they offer zero inventory space, just discard them.
