### ISSUE TITLE
Scented artificial hives for "Magic Bees" do not work.

### ISSUE THREAD

**Issue by Lodran** [jadedcat/AS2Configs#129]
[15:51:12] [Client thread/INFO] [Ex Nihilo]: Beginning Hive Registry...
[15:51:12] [Client thread/INFO] [Ex Nihilo]: Compatibility OK!: Forestry Bees
[15:51:12] [Client thread/INFO] [Ex Nihilo]: Compatibility OK!: Extra Bees
**[15:51:12] [Client thread/INFO] [Ex Nihilo]: Compatibility FAIL!: Magic Bees**
[15:51:12] [Client thread/INFO] [Ex Nihilo]: Hive Registry Completed!

The affected hives are: Curious, Resonating, Unusual, Deep, Oblivion and Infernal.

**Comment by samuelroy21** [comment]
to my knowledge, this is intentional. those hives are handed over to ex astris. If you look in the Ex astris section of the thaumonomicon, down the line with the thaumic barrel there are special hives you can make to get those bee types.

**Comment by Lodran** [comment]
If that's the case, then the problem is one of documentation.  If a feature of one mod has been disabled in order to force the use of another mod, players shouldn't be left wondering why the feature isn't working.

**Comment by MarshMilo100** [comment]
Noted.
