### ISSUE TITLE
Top Teir Generation

### ISSUE THREAD

**Issue by GamingWithAGoose** [jadedcat/AS2Configs#13]
Hi, I've completed the quest but it wont let me claim my rewards, I click on "Claim Reward" but it doesn't do anything. I've tried deleting my progress in the quest with the OP book but no dice. I've also just forced finished the quest but I still couldn't claim the reward.

**Comment by Infernalized** [comment]
What version  of A S2 are yout using?

**Comment by samuelroy21** [comment]
you aren't having an issue at all, you just need 16 inventory slots free, one for each potion. they don't stack.

**Comment by GamingWithAGoose** [comment]
ahh ty
