### ISSUE TITLE
Inventory dissapeared

### ISSUE THREAD

**Issue by towergame** [jadedcat/AS2Configs#130]
So yesterday the game was running perfectly...
Today I opened my world with a nasty suprise
My stuff was completly vanished(except the chests and blocks i placed down)
I had some important stuff in my inventory

**Comment by shadowfacts** [comment]
Can you please provide the `fml-client-latest.log` (from the `logs/` folder)?

As a temporary measure you could try restoring from a backup.

**Comment by Mhorgul** [comment]
Did you perhaps type "/hqm enable" on the server?
that cleared my inventory atleast

**Comment by towergame** [comment]
Here you go:
https://www.dropbox.com/s/y3bm5n0gdh8koly/fml-client-latest.log?dl=0

**Comment by cblair91** [comment]
@towergame Any update on this?

**Comment by cblair91** [comment]
No response from user. Closing.
