### ISSUE TITLE
v1.1.13 (Mac) Download Incomplete - Crashes MC

### ISSUE THREAD

**Issue by Roadspill** [jadedcat/AS2Configs#132]
I clicked the Mac/Linux download button and downloaded the v1.1.13 file from this page. It downloaded a 155mb+ zip file. When I uncompressed it in 4 different compression programs it still uncompresses all the same files no matter which one I use.

I then went and tried installing it through MultiMC (Installing Forge, Copying files, etc) but when I load the game it crashes. So I tried playing around and noticed that within the mods folder it only has like 2 mods, and a folder (1.7.10) with a couple of mods in there.

So I'm not really sure what is going on there.

Any help would be greatly appreciated.

Thank you,
Arnaud

**Comment by pjfranke** [comment]
You may have missed over the instructions.

> - Mac/Linux Users :  AT THE BOTTOM OF THE PAGE - The one Titled "Alternative" is the alternative download.

> Agrarian Skies 2-1.1.13 - Alternative.zip	258.60 MB

As noted, the file you need for Mac systems is 258MB in size, and contains all the mods.

**Comment by Roadspill** [comment]
I guess my issue was the fact that I didn't click over from the main page that had that listed. I just google searched for Agrarian Skies and it took me directly to the download page where it didn't show that info.

Thanks for pointing that out.
