### ISSUE TITLE
Certain things stop working on chunk unload/reload (Trash cans and Vis Relays, at least)

### ISSUE THREAD

**Issue by UndeadLemon** [jadedcat/AS2Configs#135]
When a chunk with a trash can in it gets unloaded/reloaded, it can stop accepting items. Tested this with two trash cans at separate locations, but only using servos to input into the trash can (might try later with transfer nodes). Matter Condensers from AE do not seem to have the same problem, although I have mine setup to make singularities, which might cause it to function differently.

A similar issue with Vis Relays happens on chunk unload/reload, but strangely enough it seems random which relays stop working. I usually have to break all my relays and replace them until I find the one that stopped working (like replacing christmas lights all over again), and although some might be more likely to break (possibly one's closer to chunk boundaries? I don't know, I need try and keep better track). Once broken and replaced, it works fine, but restarting fixes the issue as well.

Only other possible block I have noticed this with is the security station from AE in combination with the wireless interface. It sometimes can't see the security terminal, which needs to be removed and then replaced and relinked. I'd bet it's the same issue, related to chunks loading and unloading frequently (because who doesn't just fly around in large circles near their base >_>)

**Comment by samuelroy21** [comment]
some in game objects lack coding for "persistence", in other words, once they arent loaded, they forget what they were doing, a good example of this phenomenon being computercraft. Sadly, this isnt a problem that can be fixed with tweaking, report it to the mod authors.

**Comment by cblair91** [comment]
As this is an issue with a mod, nothing we can do, Closing.
