### ISSUE TITLE
graphics glitch with plastic tank

### ISSUE THREAD

**Issue by omfgindeed** [jadedcat/AS2Configs#136]
not sure if this is a mod conflict issue in the pack but the mob spawning zone markers can be seen through walls when looking through a plastic tank filled with pink slime

![untitled](https://cloud.githubusercontent.com/assets/14941665/10416296/f905c26c-6fdf-11e5-8315-03a71f61f8e7.png)

**Comment by MarshMilo100** [comment]
This is most likely a rendering issue with mfr, we cannot really do much about this, you should probably report this bug to them on their bug tracker.

**Comment by cblair91** [comment]
As we cannot support this issue with another mod, closing.
