### ISSUE TITLE
Agricraft custom crop error

### ISSUE THREAD

**Issue by Katalliaan** [jadedcat/AS2Configs#137]
With the update to Agricraft 1.4, it seems that the crops defined in config/agricraft/CustomCrops.txt cannot have a space between the parameters - if there is one, it will complain about an "incorrect amount of arguments". This affects ghastly moss, ardite clematis, ardite bush, cobalt clematis, cobalt bush, manyullyn clematis, and manyullyn bush.

Example:
changing ```ghastlymoss,minecraft:ghast_tear,minecraft:soul_sand,AWWayofTime:AlchemicalWizardrybloodRune:0,3,1, Much quieter than hunting``` to ```ghastlymoss,minecraft:ghast_tear,minecraft:soul_sand,AWWayofTime:AlchemicalWizardrybloodRune:0,3,1,Much quieter than hunting``` corrects the issue.

**Comment by cblair91** [comment]
@Katalliaan Is this still occurring with the latest version?

**Comment by Katalliaan** [comment]
It happened in pack version 1.1.14 using the alternate download. If there is a more recent version of the pack, I cannot verify until the alternate download is up because I do not have the Curse launcher.
