### ISSUE TITLE
Glowshroom (Natura) bonemeal bug

### ISSUE THREAD

**Issue by Trisscar05** [jadedcat/AS2Configs#139]
So the rules I've figured out from trial and error for growing glowshrooms in the overworld are;
-Red X's level of light. Just plain outside nighttime doesn't work. (Only sometimes. It almost seems to depend on Y level whether or not this is true, since I can grow them in light on the start level of the platofrm, but not beneath it.)
-Must be placed on netherrack.

Unfortunately, you can't see or walk in the space of bonemealed (giant) glowshrooms from the overworld when you first grow them. Instead you must close and reload the world in order to have them appear. Though it does sometimes show the first two blocks of the stalk, or a random part of the cap.
Not that the game doesn't know they're there, it won't let you walk into those blocks and instead gives you that glitchy teleporting effect you get when you walk into a chest sometimes.
This is on 1.1.13, as I wanted to get some stuff done and not running before I updated, and I'll try again once I have.

**Comment by cblair91** [comment]
@Trisscar05 Could you try updating and see if this is still occurring?

**Comment by Trisscar05** [comment]
Sadly I don't have access to the computer with the save currently, though I should after the holidays.

**Comment by cblair91** [comment]
@Trisscar05 As this is an issue with a mod, can you please report it to the mod authors, as there is nothing we can do about this. Will update ticket if there is any update from the mod author and we update on our side.
