### ISSUE TITLE
Blood Block does not have a recipe in NEI.

### ISSUE THREAD

**Issue by lakk110** [jadedcat/AS2Configs#14]
When you try to see its recipe, the game shows the ruby's recipe. I don't know if this means it is not craftable or just a NEI bug, because I don't know its recipe to test it.

**Comment by samuelroy21** [comment]
confirmed. this could be an nei bug or a jadedtweaks bug.

**Comment by Infernalized** [comment]
The mod itself does not have a recipe for the bloodblock. It (according to the mcf forum) obtained in creative or through a recipe created by a pack creator or someone else that wishes it to have a recipe.

**Comment by samuelroy21** [comment]
we intend to add a recipe in the next build, please be patient.

**Comment by jadedcat** [comment]
Added in Jaded Tweaks 1.1.25. Manually update Jaded Tweaks or wait for next AS2 build.
