### ISSUE TITLE
no ingot crops for lead and tin

### ISSUE THREAD

**Issue by pie1e** [jadedcat/AS2Configs#140]
in agricraft, there are all the nugget crops for regular ores (iron, copper, gold, aluminum, tin, lead, etc.), but the second level of crops contain the same ores EXCEPT for lead and tin. 
Why is this and can this be fixed soon?
Thank you!!!

**Comment by samuelroy21** [comment]
cause reasons. I will take this up with jadedcat, could be an oversight.

**Comment by cblair91** [comment]
This is intentional.
