### ISSUE TITLE
More issues with agricraft seeds

### ISSUE THREAD

**Issue by Chinthor** [jadedcat/AS2Configs#142]
I'm in the middle of editing the customcrops.txt so that ardite and cobalt seeds work once more. Will also try to put manyulin in. Having never checked the config before, didn't know it was missing.

However, this update adds seeds to NEI for nether quartz, bacon, taint, cinderpearl, and shimmerleaf. Problem is, they have neither a mutation nor a thaumic recipe. Tried in creative with cheaty research and they still don't exist.

Is this intentional or just another missing recipe?

**Comment by cblair91** [comment]
This is intentional.
