### ISSUE TITLE
Invalid Item/Bedrock

### ISSUE THREAD

**Issue by theskipster00** [jadedcat/AS2Configs#143]
![2015-10-13_14 32 57](https://cloud.githubusercontent.com/assets/15096272/10464363/715097c8-71b7-11e5-92a7-b11c9fdb41ab.png)
![2015-10-13_14 33 00](https://cloud.githubusercontent.com/assets/15096272/10464364/7158e7b6-71b7-11e5-8b33-6c70ecc13254.png)

There is a quest called "Irrigation" under the section Sky Farm in the quest book that requires Bedrock as one of the items. It also says it give out an "Invalid Item". I feel like that is most definitely a glitch.

**Comment by neomunk** [comment]
I've experienced this same issue.

**Comment by samuelroy21** [comment]
We are aware of this problem and are currently working to fix it. you can just spawn the OP book and cheat yourself the quest. As one of the gods of this pack, I allow you to do so: don't consider it cheating.

**Comment by neomunk** [comment]
Heh, that actually makes me feel better about that while providing me a good chuckle.  Thanks for your efforts and also the quick reply.

**Comment by samuelroy21** [comment]
np
