### ISSUE TITLE
Crash when Clicking on Cooking Table (Cooking with Blockheads)

### ISSUE THREAD

**Issue by jkmcne** [jadedcat/AS2Configs#146]
I recently experience a crash when clicking on the Cooking Table from 'Cooking with Blockheads'. This appears to started to occur after I rearrange some of the multiblock kitchen Items from 'Cooking with Blockheads'. I have tried breaking; which I still am able to do in game; the table and replacing it but still experience the crash.

Log File:
http://paste.ee/p/81jis

**Comment by samuelroy21** [comment]
please don't post duplicate issues, thread close.
