### ISSUE TITLE
Items mixing/losing aspects from Thaumcraft

### ISSUE THREAD

**Issue by eviltux** [jadedcat/AS2Configs#147]
Not sure if it was something within Thaumcraft (as I'm already familiar with it and don't really read any of the things I unlock through it), a problem with Thaumcraft, or if it's something with this pack (maybe with the update, uncertain if that could have caused it). It seems some objects have had their aspects changed when I first discovered them, some lost all aspects, and some objects cannot even be scanned. 

Example one: The iron tools usually have Metallum plus whatever else would be used by the tool. It did start that way for me at first, but then when looking for a certain aspect I needed to work on quests, I see they are giving me something else besides Metallum. Instead, they are giving me Exanimis and Mortuus and no Metallum.
![2015-10-15_00 29 01](https://cloud.githubusercontent.com/assets/15135428/10504909/c334da86-72d4-11e5-972d-4afc2b74194c.png)

Example two: I set off a few items that I was thinking about getting rid of but unfortunately they will not burn through in the Alchemical Furnace, due to their total value being too high. Prime example is any of the diamond version machines in Progressive Automation. I went to check on all the items in the chest where i stored these, and now they show nothing when I hold shift to check on the aspects. When I try to re-scan those items with the Thaumometer, nothing is happening. No scanning noise, no scanning animation. Nothing. if needed, I could upload a short video demonstrating this.

I'll see if somehow I can try to reproduce this, but given how it randomly occurred, I cannot promise that I can. Also unsure if it only happened to just me, or if others experienced this.

**Comment by Trisscar05** [comment]
Happens to me as well, sand and other random blocks and items are unscannable now. A previous google search had someone with a similar issue claiming it was because of a Extra Utilities update, with the bug disappearing after downgrading, or possibly upgrading as well.

**Comment by Chinthor** [comment]
Just a bump to say that same is happening to me. Was trying to find a way to reset one's scanning knowledge. Some things (like stone bricks) don't scan. It acts like I've already scanned it, and maybe I have. But it shows no aspects. And now coal comes up as Nothing Can Be Learned From This. WTF. I'll try the ExU upgrade or downgrade and see if that helps.

If anyone knows a way to clear scanning knowledge without lobotomizing my player file, let me know. I get the feeling that I'll still end up deleting my player.dat and then rebuilding my quest progression. Urg.

**Comment by Chinthor** [comment]
Tried dropping from ExU 1.2.11 to 1.2.10. Things have the proper aspects once again. Never did find a way to erase my knowledge of scanned items. If I had nothing left to scan, I'd never unlock certain branches of research. Thaumium, for instance, only shows if you scan metalum. Just lucky that I hadn't quite finished my "scan all the things" rampage.

**Comment by cblair91** [comment]
Should be fixed in latest ExU, waiting on modpack update.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#4
