### ISSUE TITLE
WorldSave overwritten on client update

### ISSUE THREAD

**Issue by sojiro288** [jadedcat/AS2Configs#150]
Not sure if this is the correct forum for it, but the cursed voice client when updating the AS2 pack overwrites the world saves without warning. No chance to backup the world nothing...the gods are cruel and have wiped the world clean again. I cri.

**Comment by sojiro288** [comment]
NVM found the backup folder where the world saves were placed "Curse\Minecraft\Backups". However I have lost a few years due to depression. kkthx.

**Comment by pjfranke** [comment]
To not lose anymore years to depression, make sure you rename your save folder.  That way, it's not seen as one of the default/starting maps, and won't get overwritten.
