### ISSUE TITLE
Upgrading the Builder's Wand

### ISSUE THREAD

**Issue by cleverruse** [jadedcat/AS2Configs#154]
My NEI states to upgrade my builders wand, I need an Ingots worth of molten ardite and pour it over an builder's wand to make a super builders wand in a casting table. Problem is the builder's wand wants to do builder's wand things and It cannot be right clicked within the table... Please advise as I dont want to cheat one in.

**Comment by tecrogue** [comment]
The Builder's Wand can be piped into the casting table via hoppers and/or ducts.

**Comment by cleverruse** [comment]
thank you!
