### ISSUE TITLE
Aqueous Accumlator?

### ISSUE THREAD

**Issue by cleverruse** [jadedcat/AS2Configs#155]
I've got water source blocks surrounding my aqueous accumulator save for the spot where I have a Tesseract to transport it. I dunno why I'm only producing 300mb of water per tick? This is what it makes with no water source blocks. Is this feature disabled some where in a config? I just updated to 1.1.8 however it wasn't working in the last version either

**Comment by pjfranke** [comment]
What level of Aqueus Accumulator?  Have you added augments?

An AqAc will produce 800mb/operation with 2 water source blocks, no speed gained for 4 water blocks.  A resonant AqAc will produce 6400mb/op. with 2 source blocks with T1, T2, and T3 Machine Processing Speed augments.

No source blocks produce 160mb/op with zero augments, 320mb/op with 1, 640mb/op with 2, and 1280mb/op with all 3.

**Comment by cblair91** [comment]
Assuming @pjfranke gave an answer to the problem. Closing.
