### ISSUE TITLE
Recall stones not rechargable

### ISSUE THREAD

**Issue by andyb2** [jadedcat/AS2Configs#157]
I've had this issue for a few releases.The recall stones do nothing when in the crafting table with ender pearls. I asked vanhal about this issue and he tested it but the mod is fine so he thinks it has something to do with the recipe being changed.

**Comment by pjfranke** [comment]
This is a known issue, that as you say has persisted for a few updates.  No fix has been found yet, so unfortunately for now the recall stones are not rechargeable.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#7
