### ISSUE TITLE
Scented Artificial hives would appear to be broken. Or ridiculously hard to rng.

### ISSUE THREAD

**Issue by Trisscar05** [jadedcat/AS2Configs#160]
http://imgur.com/yxaO5BF
Yes, those are all exactly one block deep in water. The biome is also default Ocean.

All of those used to be scented hives, and this is after a 10 minute or so wait. It's also in a test world I created, but the results have been similar on my main world. Other hive tests have similarly failed. I'm inclined to think there is something I'm missing somehow, but I have no idea what that would be, and my google-fu has failed to turn up anything.

**Comment by Trisscar05** [comment]
After more testing, (and noticing that water hives and rock hives straight up do not exist in the pack atm, my bad) I've discovered some strange things. For instance, placing scented hives surrounded in stone in an Ocean biome will produce Unusual hives. Which are only supposed to appear in jungle surrounded by flowers. Pics of other odd things (like jungle hives not spawning at all, and instead being replaced, again, by unusual hives) are here;

http://imgur.com/a/4fQIe

-The jungle area is after two rounds of placement
-Meadows would appear to be fine, and all one block vanilla flowers work

The second issue I have found, which I will make into a separate issue on this github, is that the terrestrial reformer from Witching Gadgets (Thaum) appears to be clogged or something, because it will stop changing the nearby biome halfway through the process, leaving random bits as ocean rather than whatever it's supposed to be changing it to. It's the most obvious with the jungle area because the vines are different shades depending on the biome, as shown in the second and third pictures.

**Comment by samuelroy21** [comment]
you were really intended to do this through the thaumcraft tab for ex astris

**Comment by Trisscar05** [comment]
Ex Astris, as far as I know, only deals with the magical versions of these hives, along with three really hard to get ones from the end, bedrock level, and... I think some weird nether version that's separate from the regular nether version? That leaves at least six regular biome hives, plus water, rock, base nether, etc.

There's also the point that even if you could, you'd need to change the quest for the artificial hives, probably to not being used the way they're supposed to be originally. The fact that some of the hives DO work the way they're supposed to, while others don't, means this likely isn't intended and therefore a bug; whether in that they aren't supposed to work, or that some types of hive RNG are broken.

**Comment by samuelroy21** [comment]
pretty sure you can get them with some induction smelter recipes. try looking at the recipes for the hive types you want.

**Comment by Trisscar05** [comment]
Oh indeed I can. My issue here is that I had no clue to look for them till I did a bunch of research on how the artificial hives worked to make sure I wasn't doing something wrong, and ran across a different site with the same issue and the smelter answer. It's not in the book at all as far as I can tell, so I'd like to suggest putting that in instead of explaining the currently defunct method.

**Comment by samuelroy21** [comment]
I'll see what I can do.
