### ISSUE TITLE
Botania Petals - Crops only giving White petals. 

### ISSUE THREAD

**Issue by axle2005** [jadedcat/AS2Configs#161]
Tested in both SSP and SMP.

**Comment by samuelroy21** [comment]
screenshot/video pls

**Comment by pjfranke** [comment]
Tested in 1.1.14, unable to reproduce.  Agricraft mystical flower seeds drop the correct color of petal.

**Comment by Rastauren** [comment]
Same problem.
Version 1.1.14 - Morvy Cottage map.

No matter the color of the flowers, so they will allways give you white petals...

![sshot_1 1 14_whytepetals](https://cloud.githubusercontent.com/assets/16337461/11871470/0f523c56-a4d0-11e5-84dc-ba16583f855e.PNG)
