### ISSUE TITLE
Packer Larger than Expected Error

### ISSUE THREAD

**Issue by mweinbach** [jadedcat/AS2Configs#163]
I am on a server and I tried to use a resonant retriever to pull AE cells into a compact chest, when this happened I got a Internal Exception Netty IO error. This will not let me connect to my island and will kick me when I go. Attached its a picture of the error.
<img width="1216" alt="screen shot 2015-10-03 at 8 29 38 am" src="https://cloud.githubusercontent.com/assets/15623732/10900966/a7cf80c2-819b-11e5-81ca-6f2fdfbeecb6.png">

**Comment by pjfranke** [comment]
You likely hit the NBT data limit, if you were trying to put AE cells with inventory in them into another inventory.  The compact chests's NBT data needs to describe it's contents, as well as the contents of any contents (such as a dolly holding a chest or barrel).

From your description I assume this is a multiplayer server, and not just that you're running it on a server.  Unfortunately, when you join, or if anyone gets close enough to your island to load the chunks, that's likely when the crash would happen.  Anyone else far enough away may not have any issues if they keep their distance.

The way to resolve this would be to use a World Editor and delete the compact chest, which unfortunately would mean losing the contents of the AE cells it contains.  Or rolling back to a backup of the server before this issue happened (unlikely from this long ago on a multi-player server).
