### ISSUE TITLE
Forestry pollinated leaves sometimes don't appear till you reload the world

### ISSUE THREAD

**Issue by Trisscar05** [jadedcat/AS2Configs#164]
This is a bug I remember encountering in other packs, however I can't seem to find the page/thread from back then that mentioned it or why it happens. This is with spectacles on, and sometimes if you just wait long enough (about 8 hours in my case) the leaves will suddenly change on their own in a group.

**Comment by cblair91** [comment]
@Trisscar05 Is there any update on this?

**Comment by Trisscar05** [comment]
I'll let you know once I have access to the save again after New Years, though at the time I just went around the issue with Gendustry.

**Comment by cblair91** [comment]
As this appears to be an issue with a mod, can you please report it to the mod author, and we will update the ticket when there is a fix and we update to it.
