### ISSUE TITLE
Cooking for Blockheads

### ISSUE THREAD

**Issue by flirtyflashr** [jadedcat/AS2Configs#166]
On Version 1.1.14 When I open Cooking for Blockheads (no numberal), the cookbook where the tooltip is saying it'll show all the recipes. It crashes.

**Comment by Trisscar05** [comment]
Do you have a crash log, and if so could you post it please?

**Comment by flirtyflashr** [comment]
Curse\Minecraft\Instances\Agrarian Skies 2\crash-reports

is empty.

and appdata roaming .minecraft isnt there any more, It was there before but i cant remember what i did... im guessing that i had some problems with minecraft once, and then wanted to reinstall, so i deleted that folder

**Comment by shadowfacts** [comment]
Can you send the FML log? It'll be in `Curse\Minecraft\Instances\Agrarian Skies 2\logs\fml-client-latest.log`

**Comment by flirtyflashr** [comment]
I am playing on a server i run locally btw,, dont know if that matters.

So what i have done is, restarted server, restarted client, logging in. Opened that cookbook, and then it says error occured, bringing you back to title screen.

https://drive.google.com/file/d/0B844Xdn3prnzWEo4cDFjY1RXanM/view?usp=sharing

**Comment by pson** [comment]
I had this but with a totally empty fridge. I added the above mentioned FML file as well, please tell me if there is anything else I can do.

https://drive.google.com/file/d/0B9J4VhgTgPX9RnpCSjVvVUpvcXM/view?usp=sharing

**Comment by Trisscar05** [comment]
Use NEI instead of the book, and if you can't get back into your world or near the chunk where it sits, use MCEdit to delete the fridge block. Otherwise wait till the mod author or the pack creator sorts it out I'm afraid.

**Comment by pson** [comment]
It's not a problem, I didn't use it much (just played with it since it's a cool thing) and it only crashed when I try to right-click the cooking table, so it does not cause me any trouble, This whole thing is to provide what assistance I can when you're searching for the bug.

**Comment by Moojuiceman** [comment]
**Seed soup** is the issue. Uses stock and any compatible seed. Same crash happens when using 'Cooking for blockheads I' with the items in your inventory (or fridge). Seems the UI can't display it properly and crashes.
