### ISSUE TITLE
Thaumic Energistics. Import bus, export bus, storage bus

### ISSUE THREAD

**Issue by Chinthor** [jadedcat/AS2Configs#168]
There is a known bug in thaumic energistics involving void jars not interacting properly or at all with buses. The beta release immediately after the stable one we are using has this problem and others marked as fixed. Don't know if that beta will cause more problems for AS2 than if fixes, but you never know.

**Comment by samuelroy21** [comment]
Could you send us a screenshot? thanks
~the real platinum god

**Comment by samuelroy21** [comment]
You failed to respond, and this isn't really a place for "suggestions" per se, so I'm closing this issue.
