### ISSUE TITLE
Agricraft Tanks delete water

### ISSUE THREAD

**Issue by Godomos** [jadedcat/AS2Configs#169]
Using any type of filling will drain the source completely but the tank will still have 0/8000 mb of water inside of it. They are essentially functioning as a fluid void and cannot be used for crop irrigation.

**Comment by samuelroy21** [comment]
I have yet to see this...I use them in my world without any such problems. This may possibly be a UI glitch. I'ma ask for a few things: 1.) screenshot 2.) try an aqueous accumulator 3.) try different shapes. it is a multiblock style structure after all. 4.) different methods of putting the liquid in
thanks for using glitch removal services. have a nice day.

**Comment by Godomos** [comment]
Thank you for your feedback. One of your solutions worked, however the single tank still remains a bugged and voiding fluid through whatever means I attempted.
1) Screenshot: https://imgur.com/DfUZxdN     also attempted other positions for output and input.
2)Aqueous was the first method tried. Also fluiducts and manual bucketing did not work. The accumulator pictured was full resonant 32 bucket tank emptied in seconds. Unable to retrieve water with a bucket or other method.
3) Multiblock tank accepted water from the accumulator, significantly slower than produced, but it works at least.
4) All other methods i tried fail on a single tank. Multiblock tanks work.

Thank you for your workaround.

**Comment by samuelroy21** [comment]
it's not really a workaround, it's how the tanks were meant to be used. If you use a single block, you're doing it wrong. I will bring the issue up with Jaded. In the mean time, this issue is closed.
