### ISSUE TITLE
Progressive automation stone generator

### ISSUE THREAD

**Issue by Timtower** [jadedcat/AS2Configs#17]
I have the issue that my stone generator won't transmit power to my pulverizer which is placed against it.
Is there something wrong with the RF transport?
And yes: I did fuel the generator

**Comment by Infernalized** [comment]
You need to use a fluxduct to transmit power.

**Comment by Timtower** [comment]
@Infernalized Yeah, trying to get the resources for that
Do you know which mod is causing it?

**Comment by Infernalized** [comment]
I'm actually not sure that the stone generator auto outputs to other machines.

**Comment by Timtower** [comment]
Their wiki says that they do.

**Comment by Infernalized** [comment]
I don't see a config option for it and the generator doesn't even power the machines in PA. It could be a bug but from what I can see there is no reason that it should work.

**Comment by Timtower** [comment]
Shame, time for resource grinding then. Thanks for the help

**Comment by pjfranke** [comment]
The Stone Generator does function fine, with a few oddities.  Yes, I confirmed that a pulverizer will not receive power from it.  However, a leadstone energy cell does get charged when placed next to the generator.  A leadstone fluxduct will transmit power from the generator to a pulverizer.  A Progressive Automation stone Chopper, with the RF engine upgrade, placed next to the stone generator does charge its RF engine so it will run.

I thought you needed to wrench the side to "output", but that doesn't seem to matter for RF.  It will output power whether the side is set to Input, Output, or Normal (default).

In addition to the TE machines, AE2 controllers and energy acceptors do not receive power directly.  Nor do MFR machines.

EnderTech charge/health pad do work.  As do Rednet Power cables.  The Ex Astris Hammer and Sieve work.  Extra Utilities pump and quarry will power directly.  Forestry machines work, and Gendustry.
