### ISSUE TITLE
v1.1.14 Refined Relocation Problem

### ISSUE THREAD

**Issue by Linkthekiller13** [jadedcat/AS2Configs#173]
Hello in the storage wars tab of book the block extension quest u cant craft the items and they arent in the NEI. We playing on an server using v1.1.14. Is it disable in the pack?

And when you do craft them game crashes

**Comment by MarshMilo100** [comment]
What items specifically?

**Comment by Linkthekiller13** [comment]
the advance block extension and filtered block extension. We cant look up any of the refined relocation items in NEI

**Comment by MarshMilo100** [comment]
Are you positive that refined relocation is installed in your instance

**Comment by Linkthekiller13** [comment]
I can see it in the config folder and in the mod section on title screen where u click extra

**Comment by samuelroy21** [comment]
so you are saying you can't craft them? or that NEI won't show you the recipe?

**Comment by Linkthekiller13** [comment]
NEI doesnt show them and when u try crafting them. when u go to pull them out the crafting grid the game crashes

**Comment by samuelroy21** [comment]
is your server version up to date?

**Comment by shadowfacts** [comment]
Logs & crash-report or it didn't happen.

**Comment by Linkthekiller13** [comment]
Server is up to date v1.1.14 and here is the crash log when u pull out the item and game crashes
[crash-2015-11-17_17.41.44-client.txt](https://github.com/jadedcat/AS2Configs/files/37339/crash-2015-11-17_17.41.44-client.txt)

**Comment by samuelroy21** [comment]
ask your friend if he changed any configs

**Comment by Linkthekiller13** [comment]
nope he hasnt

**Comment by MarshMilo100** [comment]
What type of crafting grid are you using? From what mod(s)?

**Comment by Linkthekiller13** [comment]
i tried the minecraft crafting table and tinkers table

**Comment by andyb2** [comment]
I've made them in the half slab crafting table and in the AE Terminal with no problem on a server.Strange. Maybe reinstall server files incase of a corruption?

**Comment by Linkthekiller13** [comment]
maybe i try different crafting grid just in case but still doesnt show up in NEI so it sounds like its disable :/

**Comment by Linkthekiller13** [comment]
nah cant even craft them in AE crafting grid.

**Comment by samuelroy21** [comment]
hmm... try a fresh reinstall with the latest version... you should still be able to do a save transfer though with no problems.

**Comment by samuelroy21** [comment]
No response. Closing this thread.
