### ISSUE TITLE
Golden Lasso's are broken

### ISSUE THREAD

**Issue by JoePalffy** [jadedcat/AS2Configs#174]
Titles say it all really, i made 2 golden lasso's but they don't work, tried it on sheep, cows and chicken.
It "lights" up for a split second, like it succeeded but doesn't do anything, reusable safari nets work just fine though on the same animals.

Playing the latest version 1.1.14 although strangely in game it says 1.1.13.

**Comment by JoePalffy** [comment]
PS. the Bug Reports link in game is also broken, but it did get me here so that's something.

**Comment by pjfranke** [comment]
Reusable safari nets would work fine, as they work on both passive and hostile mobs.  There is a change in the pack that makes typically passive mobs hostile to the player, therefore the Golden Lasso, which only works on passive mobs, does not work.

It should still work on villagers and squid though.

The version 1.1.14 vs reported 1.1.13 is almost certainly due to a missed manual change in a config file, which is manually set to report the current version of the pack.

**Comment by JoePalffy** [comment]
Oh, i see, that makes sense now. Any idea how i can disable that easily ? (it should have never been added really)

**Comment by pjfranke** [comment]
What should never have been added?  The Golden Lasso?  Why disable it?  It's still useful for villager wrangling.

**Comment by JoePalffy** [comment]
No, the hostile/passive mobs change, i hate that (and they have some serious knockback too, almost knocked me off the ledge a couple of times)
i love the golden lasso, although i love the reusable safari net even more now that i've actually used it, since it works on everything.
But this is not a bug related thing anymore so i'll be closing this.

PS. it actually says 1.1.14 in the main game screen, it only says 1.1.13 when going to the "extras" page.

**Comment by tecrogue** [comment]
Ah, the passive mobs being hostile is fully intended, as Jaded likes tormenting players.

**Comment by pjfranke** [comment]
FYI, that was added "because Jadedcat". :)  A little bit of evil to spice up the pack.

**Comment by JoePalffy** [comment]
Tormenting is exactly what she is doing and in a lot of ways, like not adding a mod like gravestones, i also had to add vein miner to make life a little less grindy, but it's nowhere near as good as on Clouds of Darkness, it's not set up accordingly, i mean if i wanted to grind all day i would have stuck to vanilla.

**Comment by samuelroy21** [comment]
there is a thaumic horizons procedure which un-hostiles them, IIRC
