### ISSUE TITLE
Drums and enderium plates

### ISSUE THREAD

**Issue by JoePalffy** [jadedcat/AS2Configs#175]
Made an iron drum as per quest request, but whenever i place it down it disappears (its texture does)(with or without fluid), can see it in my hand and inventory though.

Can't seem to make enderium plates, even though they are present in NEI. And before you ask, yes i had plenty enderium in the smelter (24 ingots).

Also i can't seem to smelt redstone or glowstone, i tried 8 redstone dust, it consumed 8 buckets of lava and only melted them half way so i gave up on that. Am i missing something ? i watched some LP's where they said you can but it seems not.

**Comment by pjfranke** [comment]
The first two will need to be tested to confirm.

Melting redstone or glowstone in the smeltery requires higher temperatures.  That can be achieved with blazing pyrotheum tanks fueling the smeltery, but lava is not hot enough for this.  Or, you can melt it in a magma crucible, then add as a liquid to the smeltery via a drain.

**Comment by JoePalffy** [comment]
Oh, ok, that i didn't know, does it actually say anywhere what temperatures lava reaches ? and what other fuel sources can be used ? cuz this is the first time i had this problem.
And yes i made it in the magma crucible.

The iron drum might be a problem on my part (although i don't see how) since i have seen other people use it (in AG2) but don't know what exact version.

PS is anyone still working on this pack ? seems a little abandoned.

**Comment by samuelroy21** [comment]
just use blazing pyrotheum. it melts everything, and faster too! lava will smelt most other things though. Redstone and Glowstone are the only two I remember requiring blazing pyrotheum.

**Comment by JoePalffy** [comment]
I just made a magma crucible and a fluid transposer, they are needed anyway for other things.
Also the beauty of lava is that you can make it automatically and easily.
