### ISSUE TITLE
Preview bug with MFR

### ISSUE THREAD

**Issue by lekiller66** [jadedcat/AS2Configs#176]
Hi, sorry for my bad english but i have a huge problem on my map ! Before to break some machines, i had planter, fertilizer harvester. I decided to break all machines and restart the build and i always see 3 squares but i have only one harvester. I have tried to delete the minefactory forlder in powercrystal folder in config and restart the server but no result ! Please how i can fix this  ?!? Pics can help you to understand better ^^

http://img15.hostingpics.net/pics/95802220151121215853.png

http://img15.hostingpics.net/pics/24693020151121222835.png

Thx for help !

EDIT : Same here with the Sewers... => http://img15.hostingpics.net/pics/49592320151121225708.png

**Comment by samuelroy21** [comment]
try breaking them by shift+right clicking them with crescent hammer.

**Comment by lekiller66** [comment]
Thx samuel, problem fixed with the crescent hammer. And when we hold the Sledgehammer, we can see the radius of the machines, but as i said, i had only one machine (harvester) but i saw 3 squares of radius. ^^ 

Thx 

Closed

**Comment by samuelroy21** [comment]
precision sledgehammer is the wrench equivalent of MFR. Issue closed. Good night America.
