### ISSUE TITLE
Modpack doesn't launch when I click play.

### ISSUE THREAD

**Issue by MyTornHeart** [jadedcat/AS2Configs#178]
I downloaded the latest version of the modpack, waited for it all to install and load up,
It loads as far as the profiles/play screen but when I click play it closes then pops back up with this:
http://pastebin.com/nNFxzjLz

I'm not really sure why it's doing this and any help atall to get the modpack to launch/play properly would be greatly appreciated, thank you.

**Comment by JoePalffy** [comment]
What launcher are you using ?

**Comment by MyTornHeart** [comment]
Apologies, forgot to mention that. I'm using Curse Voice as it's the only launcher i could find.

**Comment by JoePalffy** [comment]
I can suggest 3 things:
1. at the profile/play screen try editing the profile, see if there is anything wrong, opt out of betas and you will probably have to set your screen resolution, (i know i had to) and if that fails, maybe try making a new profile, not sure how that works.
2. reinstall everything (curse voice and AS2)
3. Also i hear you can play AS2 in some other launcher, maybe MultiMC ? i haven't looked into it and it's probably more difficult.

**Comment by MyTornHeart** [comment]
I'll give that a go at the next opportunity, thank you.

**Comment by MyTornHeart** [comment]
I don't really want to use another launcher so i'll avoid that for now, however I have tried the other two things and neither have worked, same result.
Any other ideas?

**Comment by Trisscar05** [comment]
Why is it ignoring your perm size? Check if Curse has the Minecraft setting of RAM allowed set to 4 please.
On another note, using a different launcher can usually fix all the problems you have with a previous one, and they almost always aren't terribly hard to learn to use. It's the easiest way to see if there's something wrong with the pack, or if it's the launcher itself.

**Comment by MarshMilo100** [comment]
PermSize support was removed in Java 8

**Comment by shadowfacts** [comment]
Not removed, but it is now automatically handled internally by the JVM.

**Comment by pjfranke** [comment]
Is this still an issue?

Check your mods directory, does it have all these files? http://pastebin.com/0DbRzkCF

Can you play any other packs from Curse?

**Comment by cblair91** [comment]
No response from author, closing.
