### ISSUE TITLE
Looking up recipes in NEI causes minecraft to crash

### ISSUE THREAD

**Issue by EndearingDolphin** [jadedcat/AS2Configs#180]
I'd like help figuring out what I can do to fix this crash, but I can't figure what is even causing.

I've installed a few of my own mods, namely Ender IO, VeinMiner, Magical Crops, Fastcraft (The FPS boosting mod), Deconstrution bench, Ender Storage, and Open Modular Turrets.
[crash-2015-11-29_23.46.06-client.txt](https://github.com/jadedcat/AS2Configs/files/46957/crash-2015-11-29_23.46.06-client.txt)

**Comment by samuelroy21** [comment]
bro. don't. install. other. mods. As I don't feel like combing through your crash report for details, I'll suggest you do trial and error to find the results you want. however, as you have modded your game past what it should be, I can't help you.
