### ISSUE TITLE
Singleplayer world appears to lose contact with server.

### ISSUE THREAD

**Issue by moondragoness** [jadedcat/AS2Configs#181]
I was encouraged to post here even though I'm not really sure how to recreate this bug. Hopefully I've only done something stupid and there's an obvious fix.

For the past week or two, the first time I run AS2 after a reboot, I can play for about 30 minutes at a time. After that, it starts to behave similar to an MMO when you've lost connection to the server - even though I am playing a singleplayer game.

Chests, furnaces and other machines do not show their GUIs or respond when clicked. Mobs do not move, and likewise do not respond when smacked with sword or fist. Items don't do anything except animate. (For example the watering can will show its water sprinkles, but not actually grow nearby crops. Food acts as if eaten but doesn't get used up or restore hunger.) Once it hits this stage, all I can do is force quit - trying to exit properly gets Minecraft hung up on "shutting down internal server" forever - left it for over an hour once in case it just needed to resolve something. Once it's happened one time it will continue to error this way anytime I reload Minecraft until I reboot my machine, and then I'll get my 30 minutes of playtime before it happens again.

Things I tried to diagnose/fix it:
1) it doesn't seem to generate relevant error logs. There are never crash logs after this event. The regular logfile can be seen here: http://pastebin.com/CkbhjwKq but I can't seem to find anything relevant in it. There is a lot of suspicious failure to play sounds, but nothing to indicate that it's related to the problem.

2) I was running 64-bit Java version 1.7, updated it to 1.8 after the problem started, no difference.

3) I was warned that it could be my mobtrap creating lag - but usually if mobs are the issue, the player lags too, and I wasn't. Regardless, I swapped to peaceful, rebooted, and reloaded everything. Problem still occurs.

4) checked the memory assigned in the launcher and Minecraft is allocated 4gb of ram out of my avail 16gb. This hasn't changed since I started AS2. I did up it to 6gb, just in case, but this didn't help.

5) Just to see if it's my map, I started over on one of the others that came with the modpack. Problem still occurs.

I would love some suggestions of what to try, or what further info might be useful. At the moment AS2 is simply unplayable. A friend suggested Regrowth, so I'm playing that instead, and it works fine. Perhaps it's something to do with the Curse launcher? Everything using the FTB launcher appears to be fine.

**Comment by cblair91** [comment]
@moondragoness Is there any update to this. Is it still occurring?

Have you tried updating to the latest AS2 build (1.1.14)

**Comment by moondragoness** [comment]
It was already build version 1.1.14 when the error started occurring. And yes, the error still occurs. Despite a lot of testing and googling (and posting on forums and reddit) I still can't figure out what the install's issue is.

**Comment by foxbluefire** [comment]
I have the exact same issue as moondragoness. The only way I have been able to "resolve" this issue is to use a backup save. Even doing that, it eventually goes back to being unplayable.

**Comment by cblair91** [comment]
Could you try installing 32 bit java also :? I hear sometimes that fixes stuff

**Comment by foxbluefire** [comment]
Just a update; I installed 32 bit Java and that seemed to solve what ever was wrong. For a while anyway, the same thing just happened again. And this is not localized to AG2 the same thing happened in the Regrowth pack. I am at a loss. I don't know if its Minecraft, Java, FTB or a bit of everything.

**Comment by cblair91** [comment]
By any chance, have you updated either java recently, whether manually or
it did it automatically. Make sure 64 and 32 bit versions match :)

**Comment by Trisscar05** [comment]
If ya'll are on Windows machines, may I request having Task Manager open while you play with the tab for Performance front and center? Take note if the green (or other color if win8 or higher) tracking line goes above 70 percent or so, for longer than a few seconds, after the game has loaded.

**Comment by foxbluefire** [comment]
the highest it got when it was loading was 93% After it finished it never went higher then the low 60's for only a brief moment.

**Comment by Trisscar05** [comment]
Huh, probably not your system then, unless you have malware, though if nothing else on your computer is having processing issues then likely not.
This sounds like a memory leak, so I'm going to suggest turning off the usual culprits one after another till something changes, namely;
Journeymap
Agricraft
AromaBackup

**Comment by cblair91** [comment]
@foxbluefire Can you check java versions like I asked, and report back :)

**Comment by foxbluefire** [comment]
Oh my bad! Yea I do update Java regularly. The 64bit version i have is Version 8.0 Update 72 Build	15. The 32bit was 8.0 build 72.

Is that what you're asking for?

**Comment by Developaws** [comment]
@foxbluefire 

Is this still an issue?

**Comment by foxbluefire** [comment]
When I disabled agricraft everything worked just fine. It's been a while since I played, so I don't know if there were any updates that fixed this issue.

**Comment by Developaws** [comment]
Okay, adding this to 1.1.15 tracker :)

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#11
