### ISSUE TITLE
Agrarian skies files missing

### ISSUE THREAD

**Issue by skittlesrule** [jadedcat/AS2Configs#182]
v. 1.1.14
I have just downloaded AS2 and it works fine except for the fact that when i start any world for the first time, it tells me that there are exactly 18 missing blocks and items. These are all either crops or seeds, and come from agricraft. Any way to fix this, as i have already tried redownloading it?

**Comment by tecrogue** [comment]
The saves were created with an earlier version of the pack and that is showing up because some of the mods have been updated since changing how some blocks and items are included.

The only effect you will see of it should just be that warning the first time you load the one of the saves.

**Comment by skittlesrule** [comment]
Thank you so much! I didn't want to start playing until i solved the problem, so much appreciated.

**Comment by tecrogue** [comment]
Glad to help clear that up! :-)
