### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by TheLogan** [jadedcat/AS2Configs#183]
I'm hoping this is the place to post crash reports as well as bugs.
I honestly don't know what caused my world to crash, the moment it crashed I was just looking in my inventory, I hadn't placed any new blocks in the world and I was just in the process of making the most advanced Culinary Generator.

The main problem here though is that my game crashes when I try to start it up, every time I try to start it up now, it is in effect, unplayable.

The version is 1.1.14 from the Curse launcher

[crash-2015-12-08_18.44.30-server.txt](https://github.com/jadedcat/AS2Configs/files/55813/crash-2015-12-08_18.44.30-server.txt)

**Comment by tecrogue** [comment]
According to that log you have an Extra Utilities (Item?) Transfer Node located at -890,55,990 which is causing the crash.

Does this happen in a brand new save as well, or only in Lands of Logan?

**Comment by TheLogan** [comment]
I've got a lot of transfernodes in the other save, and I hadn't just placed the one at [-890,55,990], it had been there for probably a few hours before it caused the crash.
However I had just been standing around that area.

Now, I don't remember 100% what my chain of actions was at the time (sadly our brains don't have perfect reply xD)

But, I had a whole bunch of JABBA barrels with ores and such resources, and a large system to refine cobblestone into ingots and other useful stuff.
Well, the [-890,55,990] transfernode was moving resources from a different system, that was also connected to the resource barrels, this system was a lot newer (a few hours at most), it was for refining sand into soulsand put it through a sieve and the transfernode in question then moved resources from the sieve through a sorting node and either into a chest or into the network of JABBA barrels, I'd messed up with the sorting node though, and there were a few things stuck, and I'd forgotten to add the item in the transfernode to the a filter in the sorting node, so I think I had just taken the item from the buffer in the transfernode at the point where the game crashed.

I'm aware that this is a different story than the first one, but the first time around, I'd forgotten that I was just quickly trying to correct this problem while otherwise trying to make "The Culinary Generator to rule all Culinary Generators!!!" (I've actually never used them, I was just trying to complete a quest xD )

But thank you for pointing out the block causing it, that means I should be able to edit the savefile and simply remove the block (I hope), cheers =)

**Comment by TheLogan** [comment]
damn.. I removed the transfernode causing the problem, started the game up, and it crashed, this time referencing again a transfernode, but at [-902,55,1000]
I have a looming fear that it may be something larger than just two transfer nodes, but I'll try removing them until the save becomes playable again.

Oh and I forgot to mention before, it's only this save, it doesn't happen if I start a new game.

**Comment by tecrogue** [comment]
Hmm, in that case it could be something in your transfer network as well...you might try posting this to the extra utilities [bug tracker](https://github.com/rwtema/extrautilities) as well just in case.

**Comment by TheLogan** [comment]
Yeah, I've been removing a number of transfernodes now and everytime I try to play it lets me play for a second or two freezes for half a second and crashes with a new transfernode complaining, I'll definitely be posting at their tracker too, cheers.

**Comment by cblair91** [comment]
@TheLogan Is there any update if this is still broken for you or not?

**Comment by TheLogan** [comment]
@cblair91 
A friend of mine who's a lot more adept at all things minecraft went through it and fixed whatever was wrong, I'm not sure what he did but I assume he simply removed all offending blocks.
At any rate the savegame works again.
I posted a bug report on the Extra Utilities bug tracker, but there's been no word from there yet, (though from my understanding it's a single guy doing all the work, so it may take a while).

My friend isn't online at the moment however I'll post more info once I get a hold of him, my understanding however was that it had to do with Extra Utilities and had nothing to do with the modpack.
Nice hair btw.

**Comment by cblair91** [comment]
Thanks for the compliment =]

Since this is being handled by the mod author with which the buggy item is, closing ticket.
