### ISSUE TITLE
I can't see the boss ButterFlutter.

### ISSUE THREAD

**Issue by Kawthala** [jadedcat/AS2Configs#185]
http://imgur.com/qYqobjx

I went to the Nether for the boss quest. And then I saw the health bar of the boss but cannot find the boss. After dying several times I decided to go into creative and what I found was no body of the boss but only the text box of the name. I went to see videos of the boss to see its a small butterfly but to me it could be wayyyy too small

**Comment by pjfranke** [comment]
What map are you playing on?

Unfortunately, some of the maps do not have ButterFlutter set correctly, or not at all.  It's possible your mob is not set in aggressive mode, but would need tweaking with the CustomNPCs wand to "turn on".

I don't know why you don't see it, and only the WAILA text.  Possibly similar corruption/misconfiguration.

**Comment by Kawthala** [comment]
I play on the Morvy Cottage map .But I created a new world and just copied the template from the Morvy Cottage. I sometimes copy the save onto my thumbdrive to play the save on different computers.

**Comment by samuelroy21** [comment]
it's broken on a few map, even mine. I hereby grant you permission to hax that chieve in. Type "/HQM edit" into your chat to recieve a copy of the questbook in a sort of debug mode.

**Comment by MaLoe** [comment]
Had the same issue on the morvy map. Got it fixed by switching from java 8 to java 7 (Windows 10). Didn't had him on my original playthrough on the default platform thou.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#12
