### ISSUE TITLE
Cannot find Agrarian skies 2 anymore ?

### ISSUE THREAD

**Issue by RyoNam** [jadedcat/AS2Configs#186]
It just delete on FTB launcher 
Why i want to play again

**Comment by pjfranke** [comment]
Sorry, what?  Please clarify your problem.

Agrarian Skies 2 has only ever been available on the Curse launcher, or via an alternative download from www.curse.com or minecraft.curseforge.com.  It is not, and has not been posted on the FTB launcher.

**Comment by cblair91** [comment]
Closed as per "FTB Launcher". If this issue carries on with Curse Voice, please request a re-open.
