### ISSUE TITLE
AS2 Server HQM not loading

### ISSUE THREAD

**Issue by Lant2** [jadedcat/AS2Configs#187]
Hello,

I recently created a new server to play on with a friend. There is no crash or any kind of indication I can see that is causing the HQM mod to not work on the server. It work's perfectly fine on single player. I have downloaded the server from Curse and I'm using the 1.1.14 version. We also seem to spawn away from the platform which is not a big deal but the HQM not working has me lost completely. When I try to use any /HQM command it gives me the error - Unknown command. Try /help for a list of commands

I have checked to make sure the edit mode for HQM is false. 
I have tried to copy the folders and mod from my single player game and it gives the same error. Not sure why but it looks like the mod is not enabling server side? Any help would be appreciated. 

Forgot to mention, I made sure the pack on both our computers is 1.1.14 as well from Curse Voice Plug-in.

**Comment by cblair91** [comment]
Hello Lant2,

Few checks first:

~ Have you modified any of the mods (changed, updated, added new ones, removed any)
~ Have you modified any of the configs (changed, updated)

Other things that we will require:
~ A copy of the server log and a copy of the forge log (please use pastebin)

----

As for a possible fix right now, check your server.properties, and change op-permission level from 4 to 2 (bug with forge not liking commands in-game otherwise)

**Comment by Lant2** [comment]
Thank you for your response. 

I changed the Op-Permissions from level 4 to 2 and it did not change anything

http://pastebin.com/iaNT6sgw is the server log for a fresh server and nothing has been changed. 

I had to break down the FML log, it was too big for 1 paste bin. Sorry about this.
1. http://pastebin.com/79zxdNyg
2. http://pastebin.com/J9iwaxjr
3. http://pastebin.com/CUH1DzNh
4, http://pastebin.com/1fH4pz3k
5. http://pastebin.com/qAMbY1km

Thank you again for your assistance.

**Comment by cblair91** [comment]
@Lant2 What OS is your server using?

**Comment by Lant2** [comment]
I'm using Windows 7 Ultimate.

**Comment by cblair91** [comment]
Is that computer OS, or the one on your server? o.O

**Comment by Lant2** [comment]
Both. I'm running the server from the same computer. I did this with the old technic mod with out any issues. everything runs fine except for the HQM. It is just for me and 1 other person.

**Comment by cblair91** [comment]
@Lant2 If you don't already have it, please get Teamviewer, and send an email to: admin@betadev.co.uk with your user Id and password. This will allow me to remote in to see what on earth is going on :)

**Comment by Lant2** [comment]
Thank you. I have sent the email.

**Comment by cblair91** [comment]
Huh weird, can you try sending an email to cblair91@gmail.com instead :P Silly mail isn't syncing from BD atm

**Comment by Lant2** [comment]
Sure thing. Sent it now.

**Comment by cblair91** [comment]
Problem resolved <3

**Comment by Lant2** [comment]
Thank you so much. I would have never been able to find it.

**Comment by Lant2** [comment]
I just tried to multiplayer and it still does not work.

**Comment by cblair91** [comment]
Resolved again :P Always remember to run forge jar, not minecraft_server jar folks!
