### ISSUE TITLE
Botania Petals - Crops only giving White petals (clossed)

### ISSUE THREAD

**Issue by Rastauren** [jadedcat/AS2Configs#188]
Re-Open Issue

Version 1.1.14 - Morvy Cottage map.

No matter the color of the flowers, so they will allways give you white petals...
![sshot_1 1 14_whytepetals](https://cloud.githubusercontent.com/assets/16337461/11956681/44e1473c-a8bc-11e5-9cf1-7d2849cb999c.PNG)

**Comment by malarne83** [comment]
crops ...

**Comment by Rastauren** [comment]
crop, flower, stalk, seed, whatever...

But pay attention this title is copied from other post that is already closed because nobody posted a picture...

Here, there is a new one, with the same title but attaching a picture. Can u solve my problem?

**Comment by cblair91** [comment]
Should be resolved in Botania 1.8, awaiting pack update.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#13
