### ISSUE TITLE
Console Spam in Server, Renders it unplayable

### ISSUE THREAD

**Issue by carTloyal123** [jadedcat/AS2Configs#19]
It seems that when I log off of a server that I play alone on basically that the server console spins out into an endless loop of errors. I can log back on but everything is frozen. I can not even run commands in the server console. 
It is as follows:

```
01:15:27 p.m. [Netty IO #2/ERROR] [FML] NetworkDispatcher exception
01:15:27 p.m. java.io.IOException: It has canceled a connection established by the software in your host computer.
01:15:27 p.m. at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_45]
01:15:27 p.m. at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_45]
01:15:28 p.m. at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_45]
01:15:28 p.m. at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_45]
01:15:28 p.m. at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:249) ~[NioSocketChannel.class:?]
01:15:28 p.m. at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:680) [AbstractChannel$AbstractUnsafe.class:?]
01:15:28 p.m. at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:266) [AbstractNioChannel$AbstractNioUnsafe.class:?]
01:15:28 p.m. at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:488) [NioEventLoop.class:?]
01:15:28 p.m. at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
01:15:28 p.m. at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
01:15:28 p.m. at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
01:15:28 p.m. at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
01:15:28 p.m. [Netty IO #2/ERROR] [FML] NetworkDispatcher exception
01:15:28 p.m. java.io.IOException: It has canceled a connection established by the software in your host computer.
```

I do now know much about coding and the like but would love any feed back.
Thanks
Agrarian Skies 1.1.8 with no added mods.
(I usually use FastCraft but took it out to see if that was the issue but ran into the same problem.)
As far as reproduction the only way I can tell is logging in and then out will make the messages loop.

Edit (shadowfacts): Formatting

**Comment by carTloyal123** [comment]
http://www.mediafire.com/download/4384mrohdbu6zoz/fml-server-latest.log
This is the entire server log

**Comment by shadowfacts** [comment]
> It has canceled a connection established by the software in your host computer.

It looks like your firewall is blocking the server.

**Comment by carTloyal123** [comment]
I can still log on though, the server is just frozen. If it was blocked would I still be able to even ping the server?

**Comment by samuelroy21** [comment]
one way or another, something on your pc doesnt want you playing minecraft. try and lower the firewall, that is the most likely culprit.

**Comment by carTloyal123** [comment]
I will try to adjust it.

**Comment by carTloyal123** [comment]
I cant find anything in the firewall settings. The application is allowed full access on server host and client. Nothing is being blocked related to the server that I can find

**Comment by shadowfacts** [comment]
Hmm, maybe your router has a built-in firewall that's causing issues?

**Comment by carTloyal123** [comment]
That is true, I will take a look.

**Comment by carTloyal123** [comment]
Could those settings be affecting the connection between client and server? I can connect to server but the lag is super real even though the tps is 20 and ping is low?
