### ISSUE TITLE
Inscriber doesn't charge with AE

### ISSUE THREAD

**Issue by Ryw1el** [jadedcat/AS2Configs#190]
Inscriber in Agrarian Skies 2 Version 1.1.14 doesn't get charged by AE power. Instead, it can only take RF. Are there any ways to fix it?

**Comment by pjfranke** [comment]
Can you please post a screenshot of your setup, showing the lack of charge, and that the segment of AE cable is powered?  That doesn't sound correct.

**Comment by samuelroy21** [comment]
ae is an internal unit for AE. it auto converts RF to AE when cabled to a RF provider.

**Comment by cblair91** [comment]
@Ryw1el It has to be connected directly to the power source (e.g. generator, RF cable, RF->AE converter etc.), it doesn't gain power via AE cable.
