### ISSUE TITLE
[Pastebins - Crash Report + Logs] Crash on startup.

### ISSUE THREAD

**Issue by AndaleTheGreat** [jadedcat/AS2Configs#191]
http://pastebin.com/3KmBLqkU - Crash
http://pastebin.com/VT1D3R4J - FML Log frod crash time (only last few minutes, whole thing was too big for PB)
http://pastebin.com/H06D9Wvj - Log from time of crash
Placed a Slime Channel then shift-clicked to place a block next to it but replaced it instead, then realized I could not open inventory. (Forgot name of second block. Stone Brick in 5 & Netherrak in 2, 4, 6 & 8.) Same crash every time I restart server. (Obviously not single player.)

**Comment by cblair91** [comment]
@AndaleTheGreat Logs no longer available, can you re-paste?

**Comment by Developaws** [comment]
As no response in more than a month, closing.
