### ISSUE TITLE
Broken crossbow bolts

### ISSUE THREAD

**Issue by atvman36** [jadedcat/AS2Configs#192]
So I made a crossbow bolt with a manyullyn core and enderium "head". It claims the material to repair it with is enderium yet it doesn't accept the ingot or nugget form of it. I have repair IX on it but used it to where the durability is at 0. It's been about 20 minutes and it hasn't increased in bolt count. I've tried both manyullyn bolt and enderium bolts.

**Comment by Trisscar05** [comment]
Bolts are generally a bit weird to repair/make/calculate the dmg of. I'd like to suggest creative-ing the bolt part again, and throwing that in the tool station to see if you can use such a thing to repair it. 
If that works, delete the creative bolt part and remake as you wish, if it doesn't.....maybe you have to pour the material on it in the smeltery table again? XD

**Comment by atvman36** [comment]
Yeah I have tried the bolt part and I tried pouring enderium (repair material) over the bolts. The weird thing is the word color is purple yet the color of it on the ingot is green.

**Comment by atvman36** [comment]
I found a little work around. I made a manyullyn bolt and changed the part and repaired it with manyullyn and changed the bolt back to enderium.

**Comment by Trisscar05** [comment]
Lol, nice. Glad you found a way, maybe someday we'll hear how it's supposed to be repaired. XD

**Comment by lucagardi** [comment]
I'm experiencing this same issue, no way I can repair the Enderium bolts.
How is this marked as a "user error"?

**Comment by cblair91** [comment]
Since this is still apparently a thing, re-opening.

**Comment by GreenChicken** [comment]
I just figured it out. Use enderium chunks and it will repair them.

**Comment by samuelroy21** [comment]
ok everyone, you can go home now.

**Comment by postal291** [comment]
Wait... how the heck does one make enderium chunks?

**Comment by Trisscar05** [comment]
Either use the ingots to make tool rods in the part builder (which probably doesn't work with enderium, but that's how you do it with other materials that can't be smelted), possibly use the nugget cast though I've never tried it, or spawn it in I suppose? Could also try the gem cast now I think about it, but I've never had to make chunks for anything because I always use moss upgrades, so...
