### ISSUE TITLE
hardened fluiduct glitch

### ISSUE THREAD

**Issue by rcx760** [jadedcat/AS2Configs#194]
![2016-01-02_22 34 12](https://cloud.githubusercontent.com/assets/13920767/12076196/137c2e26-b1a1-11e5-8953-5d0464ea2b97.png)
![2016-01-02_22 34 19](https://cloud.githubusercontent.com/assets/13920767/12076197/1381a482-b1a1-11e5-856c-3be72491284a.png)

As you can see by the pictures above, my hardend fluiduct coming out of the smeltery keeps .glitching, after some time. I have run this setup before in Ag skies 1 and it works but in 2 i keeps glitching out with makes this really unplayable :(. its not a just a virutal glitch, the pipes stop working.

Feels like it has something to do with the smeltery because my lavagen system its not effected by the glitch.

**Comment by cblair91** [comment]
Is there any fluids in the pipes?

This seems like different fluids are in different pipes, so when the chunk unloads and re-loads, it then separates them because of different liquids.

**Comment by Developaws** [comment]
As no response in more than a month, closing.
