### ISSUE TITLE
Does not load the world

### ISSUE THREAD

**Issue by Materex** [jadedcat/AS2Configs#195]
Hello
I have a problem with the Agrarian skies 2. Modpack starts normally, but there is a problem with charging the world. He is still the same problem, and I can not turn on my map.
Here is a screen grab of the error:
http://imgur.com/PicTWqh

**Comment by Trisscar05** [comment]
Could we get the log from the console as well, in a link to pastebin.com?

**Comment by Developaws** [comment]
As no response in more than a month, closing.
