### ISSUE TITLE
crash lanserver nei

### ISSUE THREAD

**Issue by monkeybee11** [jadedcat/AS2Configs#198]
game  crash when looking recipe in nei not host on "open to lan|"
didn't change anything.
http://pastebin.com/RuwsfA99

**Comment by monkeybee11** [comment]
me know the erro says "do not report bc of cooking with blockhead" but we havent changed anything hon-est (sry for bad spelling)

**Comment by Trisscar05** [comment]
The cooking with blockheads thing is a false positive, you likely haven't changed anything at all and it's good you posted the log.
This is a multiplayer issue usually, I think there are a couple closed/open issues on here which deal with it, though I don't remember whether they came to a solution. But you say you had the crash even in single player?

**Comment by monkeybee11** [comment]
the crash is from my dad we play on a lan server via the "open to lan" buttion on my client

**Comment by Trisscar05** [comment]
Ahh, I see. Yeah, had this issue a while back as well, lemme see if I can find the thread....
https://github.com/jadedcat/AS2Configs/issues/148
Seems like it's something we'll need to wait for an update to fix. All I can suggest is that whoever isn't hosting should avoid looking up recipes in NEI with "U" (or possibly at all) until it's fixed.

**Comment by monkeybee11** [comment]
me am the 1 hosting and dont get the bug its only my dad that gets it

**Comment by Trisscar05** [comment]
I know. Like I said, I've had it occur for others while hosting as well.

**Comment by monkeybee11** [comment]
AH ok sry my bad miss read

**Comment by cblair91** [comment]
Duplicate of #148, closing and awaiting NEI update.
