### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Aciho** [jadedcat/AS2Configs#199]
log here:

http://pastebin.com/4xaERb3E

It claims the pack has been tampered with, but I haven't changed anything.

I followed this guide to install it:

http://minecraft.curseforge.com/forums/jadeds-packs/agrarian-skies-2/questions/general/884-how-to-install-as2?page=3#c52

and I used the hardest starting world.

**Comment by cblair91** [comment]
https://github.com/CoFH/Feedback/issues/470

Should be fixed in a newer version of CoFH, we'll update the version on the modpack for next release.
