### ISSUE TITLE
Texture error

### ISSUE THREAD

**Issue by Moontuner** [jadedcat/AS2Configs#2]
![2015-07-30_14 19 11](https://cloud.githubusercontent.com/assets/13578527/8995800/63b4f9d8-36d9-11e5-9fe0-caa7f91dc6b4.png)

![2015-07-30_14 20 53](https://cloud.githubusercontent.com/assets/13578527/8995810/6e79729a-36d9-11e5-9af1-edc8d6437822.png)
![2015-07-30_14 19 57](https://cloud.githubusercontent.com/assets/13578527/8995813/7765bc42-36d9-11e5-8023-feb502e1b031.png)

no clue why just started it up to play today and it did this 
Please help

**Comment by shadowfacts** [comment]
Logs or it didn't happen :P

But seriously, please provide a paste of the logs.

**Comment by Moontuner** [comment]
it didn't crash though

**Comment by Moontuner** [comment]
unless you mean some other type of log

**Comment by shadowfacts** [comment]
Not a crash report. Provide the contents of the FML log using a service like Pastebin.

**Comment by Moontuner** [comment]
ok

**Comment by Moontuner** [comment]
found what you meant by looking in the folder

**Comment by Moontuner** [comment]
working on it

**Comment by Moontuner** [comment]
it says i exceeded the data limit on pastebin
any ideas as to what else i could use?

**Comment by Moontuner** [comment]
nvm gonna use google docs

**Comment by shadowfacts** [comment]
You could try:

- [hastebin](http://hastebin.com)
- [pastebin.ubuntu.com](http://pastebin.ubuntu.com)

**Comment by Moontuner** [comment]
ok

**Comment by Moontuner** [comment]
just a sec haste bin is being slow

**Comment by Moontuner** [comment]
btw which log should i use alot of them are from the same time and the one im trying to use is like 3,000 kbs so its really laggy when i paste it somewhere

**Comment by shadowfacts** [comment]
`fml-client-latest.log`

**Comment by Moontuner** [comment]
thats much smaller thank you

**Comment by Moontuner** [comment]
its still taking a while though

**Comment by Moontuner** [comment]
aalmost there

**Comment by Moontuner** [comment]
http://pastebin.ubuntu.com/11969777/

**Comment by Moontuner** [comment]
finally

**Comment by Moontuner** [comment]
hello?

**Comment by Moontuner** [comment]
@shadowfacts did you check it out yet?

**Comment by shadowfacts** [comment]
1. Be patient, I am not your personal tech support, I have other things to do.
2. I have no clue whatsoever is going on. :/

**Comment by Moontuner** [comment]
ok thx sorry for being impatient

**Comment by Infernalized** [comment]
Looks like an OpenGL issue as the logs dont have a version for it. You can try to reinstall the AS2 instance and see if that fixes it.

**Comment by Moontuner** [comment]
i tryed that thx tho

**Comment by Moontuner** [comment]
is there any other way you can thnk of?

**Comment by pjfranke** [comment]
Line 11256: [17:02:14] [Client thread/ERROR] [journeymap/]: Could not load blocksTexture :java.lang.OutOfMemoryError

Line 12976: [17:03:03] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.OutOfMemoryError

I'll ask you the same questions I asked the other person who has submitted a bug report at this time, as it seems to be a very similar issue:

1: How much memory do you have the CurseVoice launcher set to give Minecraft?
2: How much system memory do you have?
3: When you check Task Manager, how much FREE ram did you have before launching AgSkies2?

**Comment by Infernalized** [comment]
Was about to ask the same. That's the only error that I  can see in the logs.

**Comment by Moontuner** [comment]
how do i check the memory on curse?

**Comment by Moontuner** [comment]
nvm found it

**Comment by Moontuner** [comment]
was at 1 gig and i have 7 gigs of ram but 3.25 are usable

**Comment by shadowfacts** [comment]
Yeah, try allocating 3 gigs, that *should* be enough

**Comment by Moontuner** [comment]
ok but won't that blue screen me?

**Comment by shadowfacts** [comment]
Uh... No... Why would it?

**Comment by Moontuner** [comment]
idk just something i heard about allocating to much ram to one thing

**Comment by shadowfacts** [comment]
If you have 3.25 GB free when MC is not running, you should be fine allocating 3

**Comment by Moontuner** [comment]
also before i try this i am running a 32bit

**Comment by shadowfacts** [comment]
Oh...

**Comment by shadowfacts** [comment]
32 bit Java or a 32 bit CPU?

**Comment by Moontuner** [comment]
both

**Comment by Moontuner** [comment]
i have a 64 bit capable cpu but it has a 32 bit OS

**Comment by Moontuner** [comment]
i think my java is 32

**Comment by shadowfacts** [comment]
... why?

**Comment by shadowfacts** [comment]
Unless you install the 64 bit version of your operating system, you won't be able to run 64 bit Java.

**Comment by Moontuner** [comment]
i know

**Comment by Moontuner** [comment]
i have no money to buy the 64 bit OS as i am only 15

**Comment by Moontuner** [comment]
unless there is a way to get the 64bit version for free

**Comment by shadowfacts** [comment]
You can increase the amount of RAM allocated to 2GB, but that is the maximum that 32 bit Java supports.

**Comment by Moontuner** [comment]
thank you for your help
