### ISSUE TITLE
in game guide book missing in 1.1.8

### ISSUE THREAD

**Issue by EvilZeR0** [jadedcat/AS2Configs#20]
games made before 1.1.8 but have been upgraded to 1.1.8 still have the book but its listed as "create new book" and the book still works.

however if the game is made in version 1.1.8 the book is non existent.

**Comment by Nightarix** [comment]
i've noticed that the default, and by extension template, worlds all give an error involving the blood magic book. i believe the cause is some of the ID's for certain items changed? like the soul chunk claimer and the Blood magic book.
