### ISSUE TITLE
Can't grow netherwart

### ISSUE THREAD

**Issue by Kuryo** [jadedcat/AS2Configs#200]
Basically what the tittle said, i can't grow netherwart for the love of god... >_>
I've searched and tried anything, put myself in a dark box, netherwart on soulsand with crop sticks, waila says it can't grow and so does the seed analiser (and it doesnt grow at all).

**Comment by RedSpah** [comment]
It has to grow in nether.

**Comment by samuelroy21** [comment]
it requires a PITCH BLACK room. use blackout curtains to get in and out, and a magnum torch should keep the mobs away.

**Comment by Developaws** [comment]
As no response in more than a month, closing.
