### ISSUE TITLE
No Aluminium Ores in Nether make aluminium incredibly difficult to obtain

### ISSUE THREAD

**Issue by RedSpah** [jadedcat/AS2Configs#201]
Title. Without Nether Aluminium Ore there's no Aluminium Ore, and without that there's no way to get Aluminium other than by shifting gravel, as the plant that grows aluminium needs aluminium ore to grow.

**Comment by Katalliaan** [comment]
If I remember correctly, there is a quest that gives you aluminum ore as a reward. Additionally, MFR's laser drill will bring up aluminum, and can have its generation chance increased with white foci.

**Comment by samuelroy21** [comment]
you can generate it with orechids and sifting is an automatable process.
