### ISSUE TITLE
Botania Ring of Far Reach not affecting attack range

### ISSUE THREAD

**Issue by toddnollan** [jadedcat/AS2Configs#202]
The Botania Ring of Far Reach, meant to increase both block (breaking and placing) range and attack range by three blocks, affects only block range.
Pack V1.1.14, tested with an empty hand and TiCon Scythe.

**Comment by Trisscar05** [comment]
Happens in other packs as well. Have you also poked the Botania github/forum?

**Comment by samuelroy21** [comment]
this is a vazkii problem, not a me problem. report this on what ever they use for error reporting over at botania hq
