### ISSUE TITLE
Random Floating Molten Wither Iron

### ISSUE THREAD

**Issue by USSRSpetsnaz** [jadedcat/AS2Configs#205]
I noticed that if i go away from my base my game would start to lag, this is because there is a lot of floating molten wither iron and I was wondering whats the easiest and quickest way to remove them all and why are they there?

**Comment by Trisscar05** [comment]
Wait.... what? Why are there random molten liquid blocks around your base? XD
Pics please, should give us an idea of what might have likely turned into it due to blocks mismatches and such.

**Comment by USSRSpetsnaz** [comment]
![2016-01-25_20 42 45](https://cloud.githubusercontent.com/assets/16857819/12563878/45e4f432-c3a4-11e5-895c-d52007a5db76.png)

**Comment by USSRSpetsnaz** [comment]
![rage](https://cloud.githubusercontent.com/assets/16857819/12564451/34568ed0-c3a7-11e5-9abb-a8538c338f48.gif)

**Comment by USSRSpetsnaz** [comment]
Problem solved:
Made a backup and then i removed the ExtraTiC mod and launched the server, it removed all blocks from ExtraTiC including the liquid then i relaunched the server with the mod again and the liquid is still gone but the blocks are back, you get it right?

Job Well Done

**Comment by USSRSpetsnaz** [comment]
There are floating survivalist power generator (Power Multiplier x8)

**Comment by samuelroy21** [comment]
umm... you been messing with IDs at all? that's what this looks like to me

**Comment by Trisscar05** [comment]
Those are definitely in the formation of the clouds spawned by Natura, but it only changed some of them.... This is weird.

**Comment by samuelroy21** [comment]
there are multiple different types of clouds iirc

**Comment by Trisscar05** [comment]
True, but I was under the impression that most of them are the white ones, with only scattered and rare "thunderhead" grey ones.
But yes, this would appear to be a ID conflict. Spets, have you added anything to the pack?

**Comment by cblair91** [comment]
@USSRSpetsnaz can you send a pastebin of your forge log please :)

**Comment by Developaws** [comment]
As no response in more than a month, closing.
