### ISSUE TITLE
Endearing pickaxe and NEI tinkers cast recipes

### ISSUE THREAD

**Issue by adstheorganic** [jadedcat/AS2Configs#206]
I went to upgrade the pick of writing with an endearing pickaxe head and this supposed to be manyullyn mining level according to NEI even though the Enderium pickaxe head says Alumite and this should be the same as endearing is just Enderium, however the pick could not mine Cobalt or Ardite and it could mine nether diamond ore which is manyullyn level, I did a bunch of mining to upgrade the mining level to see if that fixed it, it now says mining level Alumite, stills allows me to mine nether diamond ore and not Ardite or Cobalt. Also in NEI it shows that endearing large plate casts can be made by pouring on the Enderium, however this doesn't work and holding shift over the cast it doesn't show Enderium or Endearing as a usable material. this is the same for some other cast as well, this one is not game breaking but kinda annoying. This is version 1.1.14

**Comment by samuelroy21** [comment]
this is normal. you can mining level further with some upgrades that you can apply to the pick.

**Comment by adstheorganic** [comment]
No that's what I'm saying, that was the upgraded package head, and it mined manyulln level stuff but not cobalt and ardite when manyulln is above those so anything that can mine manyullun is supposed to be able to mine anything, as there is nothing above that

**Comment by adstheorganic** [comment]
Pickaxe*

**Comment by samuelroy21** [comment]
oh, well in that case, what *could* it mine. also, did you add anything else to the pickaxe

**Comment by adstheorganic** [comment]
I tested this in creative with a an unmodified endearing pickaxe and had the same results and so I'm pretty sure it's not the modifiers, and I mined nether diamond ore which is manyullun level, but it couldn't mine ardite or cobalt ore.

**Comment by adstheorganic** [comment]
![2016-02-08_19 05 42](https://cloud.githubusercontent.com/assets/16973042/12896027/a14e8240-ce97-11e5-869d-3be06c0cb103.png)
![2016-02-08_19 05 05](https://cloud.githubusercontent.com/assets/16973042/12896060/c9f25cda-ce97-11e5-816e-73afb3f339ca.png)
so the enderium is used to create a endearing pickaxe head which is mining level manyullyn
![2016-02-08_18 49 22](https://cloud.githubusercontent.com/assets/16973042/12896101/061a2288-ce98-11e5-94ce-a860f204382f.png)
however the enderium pickaxe which is uncraftable but should be the same says mining level alumite
![2016-02-08_19 17 12](https://cloud.githubusercontent.com/assets/16973042/12896218/ba89fbee-ce98-11e5-8848-4e91f2245516.png)
when the mining level is increased it goes down to alumite
![2016-02-08_18 56 42](https://cloud.githubusercontent.com/assets/16973042/12896127/3f40d098-ce98-11e5-9d46-e1f4431bf386.png)
and 
![2016-02-08_19 00 38](https://cloud.githubusercontent.com/assets/16973042/12896149/5b474808-ce98-11e5-9f24-198e1266e5d7.png)
![2016-02-08_19 00 39](https://cloud.githubusercontent.com/assets/16973042/12896155/5f1c3312-ce98-11e5-9aa9-3134a2695238.png)
![2016-02-08_19 00 40](https://cloud.githubusercontent.com/assets/16973042/12896159/633ee336-ce98-11e5-8cfe-892af362ec06.png)
this is the same for both the upgraded and not upgraded version, and the tool tip is correct about harvestablitily

**Comment by adstheorganic** [comment]
hopefully that clears things up a bit, when I say increased mining level i mean through iguana tweaks by just mining a lot, hopefully that's helpful

**Comment by blade1981m** [comment]
It seems like the mining level name shown by Waila and the Tinkers Tooltips is not reading the overrides config file properly. For example, the endearing pickaxe is mining level 8 which should be showing as Diamond harvest level and the enderium pickaxe is mining level 9 which is Alumite. So it seems like it is reading from the Overrides config file if it is 9 or more, but if it is 8 or less it is reading from the Defaults config file instead. I am thinking the ores are having the same issue too as Nether Diamond Ore should be harvest level 8 (Diamond) but it is showing Manyullyn from the Defaults config file.

**Comment by adstheorganic** [comment]
So basically your saying it's a problem with the tool tips rather than the actual game mechanics, and I just wasted loads of enderium on making loads of endearing tools ha ha, oh well, I'm just going to have to make a ton of new tools instead, thank you for clearing that up, hopefully that gets fixed soon.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#16
