### ISSUE TITLE
Agricraft missing seeds.

### ISSUE THREAD

**Issue by MrSpellMaster** [jadedcat/AS2Configs#208]
I recently started playing Agrarian Skies 2 and when I got into Agricraft I saw that some seeds are missing- there is no cobalt,afdite,ghasttear and some others.
When I open the custom crops file,however there is cobalt and ardite added in the file? 

When I launch the game the recipies are not shown on NEI.

**Comment by samuelroy21** [comment]
this is an error we intend to fix in the next update. don't worry, all of these things can be obtained through alternate means. We know about this problem already, so I'm closing this thread.

**Comment by MrSpellMaster** [comment]
How can I obtain them

**Comment by samuelroy21** [comment]
you don't. the "things" I referred to would be the resources they generate, not the things themselves. don't worry, next update should fix the problem alltogether.

**Comment by MrSpellMaster** [comment]
So, when will the next update be? 
Kristiyan
On Jan 31, 2016 6:18 PM, samuelroy21 <notifications@github.com> wrote:you don't. the "things" I referred to would be the resources they generate, not the things themselves. don't worry, next update should fix the problem alltogether.

**Comment by samuelroy21** [comment]
...that's one way to reply. Can't give an ETA on next update, you can find what you need in the nether or through other means though. So you don't really need any of the missing crops *THAT* much.
