### ISSUE TITLE
AE2 Bug?

### ISSUE THREAD

**Issue by Kratzwurst** [jadedcat/AS2Configs#21]
Hey Jadecat

in the actually version 1,1.8 have i a problem with the quest series . i complete the quest "sky blocks" and than stops the quests and here comes nothing following quests in this series. Or need this quest series a special requirement...?
What i do: quest book reset and try also hqm edit and the problem is still there.

Here 3 Screenshots from the quest series:

http://fs1.directupload.net/images/150805/xfdb2ywc.png
http://fs2.directupload.net/images/150805/bsjmzvqu.png
http://fs2.directupload.net/images/150805/5dzx6g8z.png

Greets from Germany Kratzwurst ;)

**Comment by pjfranke** [comment]
Not a bug, there is a pre-requisite trigger quest in another quest-line that you need to complete first.  I don't recall if it's the machinery/processing one, or in Storage Wars, but one of those will open up further AE2 quests.

**Comment by Kratzwurst** [comment]
Okay thank you 
--
Gesendet von der myMail-App für Android Mittwoch, 05 August 2015, 07:02PM +02:00 von pjfranke < notifications@github.com> :

**Comment by jadedcat** [comment]
Its in Storage Wars.
