### ISSUE TITLE
Morvy cottage nether quest

### ISSUE THREAD

**Issue by Aironax** [jadedcat/AS2Configs#210]
ok so the quest says to go to 
x -155
y 88
z 141

but the bedrock ceiling is at z 128. now i have dug around a 20x20 area at bed rock, i have used the enderpearl trick and gotten up on top of the bedrock and physically perched at -155, 88 , 141.

this quest worked perfectly in AG1 but its broken for me unless anyone can think of what im doing wrong? is there a way to delete the nether and try again?

**Comment by samuelroy21** [comment]
bro, height is "y". there is no (realistic) limit to x or z

**Comment by Trisscar05** [comment]
Yup, X and Z are the cardinal directions, and Y is height above or below the ground.

**Comment by Aironax** [comment]
oh lol, i feel so stupid, thanks guys
