### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by chancelarose** [jadedcat/AS2Configs#211]
I go to start my server and a little bit into it loading up I get this problem. Can't find fix anywhere else.
Please help!
Link to log:
https://gist.github.com/chancelarose/9ebc2aa2774d5e0d1272

**Comment by tecrogue** [comment]
O_O

Sorry about the slow reply, are you still having this issue?

If so can you post the crashlog that is generated?

**Comment by Developaws** [comment]
Corrupted world, try restoring from a backup, otherwise there's nothing we can do.
