### ISSUE TITLE
Agriculture Journal Crash

### ISSUE THREAD

**Issue by sylent-flame** [jadedcat/AS2Configs#212]
I'm having an issue with reading my Agricultural Journal.

The biggest confusion is that on my desktop, np. Works fine. My laptop... 4 out of every 5 times when I start to look at the recipies, the game crashes.

I do have all the same settings (in game / curse / computer (as best a possible)).

Been dealing with this for 3 weeks or so and have been trying numerous muliple options, but nothing.

Why?

**Comment by Trisscar05** [comment]
Logs plox? Should be in a folder in the pack files if you don't want to create it again with the console open.

**Comment by sylent-flame** [comment]
[AgriCrash.txt](https://github.com/jadedcat/AS2Configs/files/120845/AgriCrash.txt)

note: Was told that it wasn't Agricraft that was causing the problem, which is fine... but it only happens when I open the Agricraft Journal, no other time.

**Comment by Trisscar05** [comment]
Gah! No downloads please. Paste it into pastebin or similar and give us that link. Downloading it goes past several security protocols that shouldn't be ignored without reason.

**Comment by sylent-flame** [comment]
Hopefully I did this correctly - through Gist
https://gist.github.com/sylent-flame/bac70291e03f7cd86195.js

**Comment by Trisscar05** [comment]
XD I'm afraid that is kinda unreadable. Thank you for the attempt though.
http://pastebin.com/
^This is the site I mean. Paste the log into the giant blank area, submit, then post the link here.

**Comment by sylent-flame** [comment]
Ok ... I think I've done it - http://pastebin.com/VjYb4iCq
This is the first time I've asked/done an online request for assistance, sorry for all the confusion - I really like the AS and would love to have it working well. The only change I've made is three of my movement keys - and assigned the duplicated keys to an unused key. I also tried to increase my memory allocation, to no avail. I am hoping that you can help me figure this out - Crash completely out or don't use the Journal ? (which would you choose?) I choose no journal at this point - That's how much I like it.

**Comment by Trisscar05** [comment]
Wtf, why does minefactory care about.... Is this occurring when opening the book from your inventory, or looking at stuff while it's sitting in the scanner?

**Comment by sylent-flame** [comment]
It happens in both places ... in the analyzer with or without seeds in ... In both cases, I see the 'Intro' page and when I click the arrow to turn the page - BAM, lock up and completely closes the game.

**Comment by Trisscar05** [comment]
Hum. Interesting. Do you happen to remember which seed you entered into it last?

**Comment by sylent-flame** [comment]
Tried various ones that currently have ... Carrot, Potato, Pumpkin, Melon, Sugarcane, Lettuce and Wheat ... We are on LAN - his desktop is the Single opened up, I am on laptop ... We have even tried from a complete log out of Curse and then back in of my laptop - Each time trying a different one and they will go through the analyze process and give the updated stats, just can't get 'into' the book - I even tried his Journal and making a new Journal.

**Comment by Trisscar05** [comment]
So it only affects your account?

**Comment by sylent-flame** [comment]
That is correct

**Comment by Trisscar05** [comment]
Hum. Okay, so this is a LAN issue only? Like if you start a new game (or even the current world) and log in as yourself is it still crashing?
The reason his book works no better than yours is likely because the info therein is tied to your player ID btw.

**Comment by sylent-flame** [comment]
Ok ... 
On Laptop:
- Uninstalled/Reinstalled AS2 - Did not make a difference - Still no Journal.
- (received and per your suggestion) Loaded copy of the World from Desktop (LAN host) - Opened in Single Player - Put me in the Hosts position with their inventory - Journal worked fine - Quit out.
- Opened Multiplayer to Desktop/LAN - Journal worked!

Been playing thru LAN (one day) - Still having lockup/crashes - They are fewer and far between (2-3 hours vs every 10-15 minutes).

My Current solution when lockup/crash:
- Open the 'Copy' in Single Player - Check that the Journal works (it has every time) - Quit - Open Multiplayer to Desktop/LAN - Journal works again - Continue 'almost' error free. (It only takes a couple of minutes to do this process.)

I think you are correct in that it seems to be something attached to my ID somehow - Any possible suggestions on a setting that may be causing it (the laptop or desktop/host) ?

**Comment by Trisscar05** [comment]
There are quite a few issues that only seem to pop up in LAN for the generality of modded MC. It's annoying, but it's how it works for now.
One way to possibly fix this would be to have your host go into the world's player data of you and delete the info it has saved for you in the journal area. Note that I have never messed with this before and have almost no idea where it would be. XD
The fact that it doesn't happen every time you open the book, but only once in a while, would indicate that it isn't just some corrupted seed data, unless the data is a slow leak that fills the memory of either your computer or the host's.
The crash log is blaming a texture and minefactory reloaded for some reason, so I assume one of the special seeds for this pack is the culprit, but I'm not certain.
I feel I should add that really, NEI has nearly all the info the book provides. I almost never use the book because of this, and you can scan seeds without it being in the device. It's nice to carry around and is likely a bit faster to navigate through, but if it's causing you so much trouble.....*shrug*

**Comment by sylent-flame** [comment]
Yeah ... Don't think we want to venture into that one (not that experienced - Yet). If it continues or gets worse - We'll look into this in more detail (or drop you another line).

But we do want to Thank You for being right on top of our question/request and responding with Information, not just "No, not me/us" or some simple/short unrelated answer.

And another Thanks ... With all the testing I've been doing, I've increased my Crop Mutations to twelve - And Growing!!

**Comment by Trisscar05** [comment]
Gj! You're welcome for the quick response, though I must admit it's mainly because I almost live on the net. XD
I wish you all success with the pack and this bug, and all fun with MC in general. ;)

**Comment by Developaws** [comment]
As no response in more than a month, closing.
