### ISSUE TITLE
Wooden gear not working for gearcast

### ISSUE THREAD

**Issue by dabigmoose** [jadedcat/AS2Configs#214]
I took the time to read things several times and I understand that JCtweaks is supposed to make it so that you can use a wooden gear to make a cast for various gears you need to make.  I tried this several times before giving in and just giving myself the gearcast to make the iron gear I needed.  I even tried doing the old make a wooden one upgrade to stone but you cant make a stone gear which is why jctweaks exists.  I wiped everything and even tried a fresh install.

**Comment by Trisscar05** [comment]
Been a while, but don't you get the cast from a quest reward?

**Comment by dabigmoose** [comment]
I haven't seen one.  I read the description of jadeds tweaks mod and it specifically states that it made it where you could use the wooden gear to make a cast.  I have recently kind of enjoyed doing some of the HQM things and I like AS2 a whole lot.

**Comment by Trisscar05** [comment]
Remind me, are there two different types of wooden gear from two different mods atm, or is that either fixed or from a different pack?
Also have you tried both aluminum brass and gold as cast metals?

**Comment by Developaws** [comment]
To make a gear case, you make a stone one, and pour aluminum brass/gold around it. NEI should have a correct recipe?
