### ISSUE TITLE
Unexpected Crash :(

### ISSUE THREAD

**Issue by Lupoid** [jadedcat/AS2Configs#215]
Getting some goldenrods to 10/10/10, put them in chest 1 -> normal item duct with normal servo -> seed analyzer -> normal item duct with normal servo -> chest 2 then game died :(

[crash-2016-02-12_22.03.47-server.txt](https://github.com/jadedcat/AS2Configs/files/128786/crash-2016-02-12_22.03.47-server.txt)

**Comment by Trisscar05** [comment]
Plz no download crash logs. Use pastebin.com instead.

**Comment by Lupoid** [comment]
Thanks but sorted it anyways. I replaced the itemduct with transfer nodes. Seems to be something to do with agricraft seeds going through as multiples.
