### ISSUE TITLE
Cactus seeds producing black ink sacs; podzol does not give any flower seeds

### ISSUE THREAD

**Issue by Wenzer96** [jadedcat/AS2Configs#216]
I planted (AgriCraft) cactus seeds and waited for it to grow, but it produces only ink sacs like from squids, not cactus green.
Also, I saw in NEI you could get botania flower seeds from sifting podzol in a sieve. It doesn't give me anything at all.

Sorry, I'm new to these kinds of things so if you need more information please ask :)

I'm using MultiMC and AS2 - 1.1.14 Alternative.zip

**Comment by tecrogue** [comment]
Huh, it sounds like something got mixed up in the configs.

Can you try re-downloading the pack and copying your save over to the new instance and seeing if it still occurs?

**Comment by Developaws** [comment]
As no response in more than a month, closing.
