### ISSUE TITLE
FPS Problems

### ISSUE THREAD

**Issue by mcobinbash** [jadedcat/AS2Configs#219]
When I launch the game the menu has low fps, taking a few seconds to highlight a different tab. In-game I get 10 fps for a few seconds then it drops to 2 fps and stays there. The problem persists in servers and single player maps. The maps I've been testing on are all brand new. The lag seems to go away after I restart my computer but only for about 30 minutes. I usually get 120-200 fps.

**Comment by Trisscar05** [comment]
Have you tried lowering all settings and adding either fastcraft or optifine?

**Comment by mcobinbash** [comment]
Yes Iv'e installed optifine and lowered all the settings and still maintain 2 fps

**Comment by Trisscar05** [comment]
Huh. Odd. Mk, checklist time:
-What's your OS, Java version #, and are they both 32 or 64 bit?
-What are the general specs of your computer (mostly just need ram and stuff, not models of parts or anything.)
-Have you recently scanned for viruses and malware, and when did you last defrag your hard drive?

**Comment by mcobinbash** [comment]
64 bit OS and Java
My computer has 8 GB of ram and a fx-8350
I've just recently bought an antivirus and scan at night when my computer is idle
I haven't defraged my hard drive in a while ago I'll try that

**Comment by Trisscar05** [comment]
But what IS the OS, Windows Xp,7,8,10; Mac, Linux and distro?

**Comment by mcobinbash** [comment]
Windows 8.1 and the low fps persists after the hard drive was defragged

**Comment by Trisscar05** [comment]
......Huh. Apparently it isn't your computer then. Good to know I suppose.
Next step then. Could you please paste a log of you starting up the game to when it loads the world into pastebin.com, and then post the link?

**Comment by Developaws** [comment]
As no response in more than a month, closing.
