### ISSUE TITLE
Crash on Loading

### ISSUE THREAD

**Issue by SKYLAKEss** [jadedcat/AS2Configs#22]
---- Minecraft Crash Report ----
The pack has been tampered with. Do not report any errors.
 origin, thaumicexpansion
 BiomeTweakerCore

// Would you like a cupcake?

Time: 15. 8. 5 오후 2:22
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
	at com.temportalist.thaumicexpansion.client.RenderAnalyzer.<init>(RenderAnalyzer.scala:39)
	at com.temportalist.thaumicexpansion.client.ProxyClient.register(ProxyClient.scala:22)
	at com.temportalist.origin.foundation.common.IMod$class.initialize(IMod.scala:55)
	at com.temportalist.thaumicexpansion.common.TEC$.init(TEC.scala:91)
	at com.temportalist.thaumicexpansion.common.TEC.init(TEC.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more
Caused by: java.lang.ClassNotFoundException: scala.reflect.api.TypeCreator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Possibly involved mods --
Details:

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 748406720 bytes (713 MB) / 1853882368 bytes (1768 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1469 134 mods loaded, 133 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1469-1.7.10.jar) 
	UCHI	Forge{10.13.4.1469} [Minecraft Forge] (forge-1.7.10-10.13.4.1469-1.7.10.jar) 
	UCHI	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHI	Aroma1997Core{1.0.2.14} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.14.jar) 
	UCHI	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHI	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHI	WitchingGadgetsCore{1.1.9} [Witching Gadgets Core] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	AccidentallyCircumstantialEvents{1.6.0} [Accidentally Circumstantial Events] (accidentallycircumstantialevents-1.6.0.jar) 
	UCHI	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHI	bdlib{1.9.0.94} [BD Lib] (bdlib-1.9.0.94-mc1.7.10.jar) 
	UCHI	ae2stuff{0.4.2.43} [AE2 Stuff] (ae2stuff-0.4.2.43-mc1.7.10.jar) 
	UCHI	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) 
	UCHI	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHI	Aroma1997CoreHelper{1.0.2.14} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.14.jar) 
	UCHI	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) 
	UCHI	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHI	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHI	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHI	Automagy{0.26.2} [Automagy] (Automagy-1.7.10-0.26.2.jar) 
	UCHI	autopackager{1.5.4} [AutoPackager] (autopackager-1.5.4.jar) 
	UCHI	bagginses{2.1.1} [Bagginses] (Bagginses-2.1.1.jar) 
	UCHI	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
	UCHI	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHI	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHI	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCHI	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHI	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UCHI	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHI	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHI	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHI	BiomeTweaker{1.2.128} [BiomeTweaker] (BiomeTweaker-1.7.10-1.2.128.jar) 
	UCHI	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-7.jar) 
	UCHI	Botania{r1.7-201} [Botania] (Botania r1.7-201.jar) 
	UCHI	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-1.7.10-release-2.0.0.12-universal.jar) 
	UCHI	CustomMainMenu{1.6} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.6.jar) 
	UCHI	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHI	Ding{MC1.7.10} [Ding] (Ding-MC1.7.10.jar) 
	UCHI	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHI	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHI	EnderTech{1.7.10-0.3.2.388} [EnderTech] (EnderTech-1.7.10-0.3.2.388.jar) 
	UCHI	exnihilo{1.38-44} [Ex Nihilo] (Ex-Nihilo-1.38-44.jar) 
	UCHI	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHI	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHI	exastris{MC1.7.10-1.16-36} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-36.jar) 
	UCHI	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	ExtraUtilities{1.2.8} [Extra Utilities] (extrautilities-1.2.8.jar) 
	UCHI	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) 
	UCHI	progressiveautomation{1.6.21} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.21.jar) 
	UCHI	ExtraTiC{1.4.4} [ExtraTiC] (ExtraTiC-1.7.10-1.4.4.jar) 
	UCHI	FinndusFillies{2.1.0.12} [Finndus Fillies] (FinndusFillies-1.7.10-universal-2.1.0.12.jar) 
	UCHI	FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) 
	UCHI	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57.jar) 
	UCHI	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	MagicBees{1.7.10-2.3.2} [Magic Bees] (magicbees-1.7.10-2.3.2.jar) 
	UCHI	gendustry{1.5.2.107} [GenDustry] (gendustry-1.5.2.107-mc1.7.10.jar) 
	UCHI	gud_thaumicnei{1.3.0} [Thaumic NEI] (gud_thaumicnei-1.3.0.jar) 
	UCHI	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHI	hardcoremapreset{2.1.0} [HardcoreMapReset] (HardCoreMapReset-2.1.0.jar) 
	UCHI	headcrumbs{1.5.4} [Headcrumbs] (Headcrumbs-1.5.4.jar) 
	UCHI	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHI	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHI	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHI	JadedsShinies{1.7.10-1.2} [Jadeds Shinies] (JadedsShinies-1.7.10-1.2.jar) 
	UCHI	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) 
	UCHI	launchgui{1.7.10-2.0-17} [LaunchGUI] (LaunchGui-1.7.10-2.0-17-client.jar) 
	UCHI	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	NEIAddons{1.12.10.33} [NEI Addons] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
	UCHI	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHI	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) 
	UCHI	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
	UCHI	origin{5.0.0} [Origin] (Origin-1.7.10-5.0.0-Beta.jar) 
	UCHI	SquidAPI{1.1.14} [SquidAPI] (SquidAPI-1.1.15.jar) 
	UCHI	PackGuard{1.1.0} [PackGuard] (PackGuard-1.2.0.jar) 
	UCHI	rainmaker{1.6} [Rainmaker] (Rainmaker 1.7-BloodMagic.jar) 
	UCHI	recallstones{0.5.1} [Recall Stones] (RecallStones-1.7.10-0.5.1.jar) 
	UCHI	RefinedRelocation{1.0.8b} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.8b.jar) 
	UCHI	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2.jar) 
	UCHI	rfwindmill{0.7a} [RF Windmill] (rfwindmill-1.7.10-0.7a.jar) 
	UCHI	RouterReborn{1.2.0.25} [Router Reborn] (RouterReborn-1.7.10-1.2.0.25-universal.jar) 
	UCHI	Sanguimancy{1.7.10-1.1.9-31} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-31.jar) 
	UCHI	SimpleLabels{@VERSION@} [SimpleLabels] (SimpleLabels-1.7.10-1.0-6.jar) 
	UCHI	simplyjetpacks{1.5.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.1.jar) 
	UCHI	SolarFlux{1.7.10-0.8a} [Solar Flux] (SolarFlux-1.7.10-0.8a.jar) 
	UCHI	SpecialAI{1.1.1} [Special AI] (SpecialAI-1.7.10-1.1.1.jar) 
	UCHI	StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) 
	UCHI	StorageDrawers{1.7.10-1.5.12} [Storage Drawers] (StorageDrawers-1.7.10-1.5.12.jar) 
	UCHI	StorageDrawersNatura{1.7.10-1.0.2} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.0.2.jar) 
	UCHI	supercraftingframe{1.7.10.3} [Super Crafting Frame] (supercraftingframe-1.7.10.3.jar) 
	UCHI	tcnodetracker{1.1.2} [TC Node Tracker] (tcnodetracker-1.7.10-1.1.2.jar) 
	UCHI	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHI	thaumicenergistics{0.8.10.7} [Thaumic Energistics] (thaumicenergistics-0.8.10.7.jar) 
	UCHE	thaumicexpansion{3.0.0} [Thaumic Expansion] (ThaumicExpansion-1.7.10-3.0.0-Beta.jar) 
	UCHI	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) 
	UCHI	ThermalCasting{0.0.3} [Thermal Casting] (thermalcasting-0.0.3.jar) 
	UCHI	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHI	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHI	TownBuilder{1.0.0-Build8} [Town Builder] (Town-Builder-1.0.0-Build8.jar) 
	UCHI	TravellersGear{1.16.5} [Traveller's Gear] (TravellersGear-1.7.10-1.16.5.jar) 
	UCHI	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHI	WitchingGadgets{1.1.9} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.9.jar) 
	UCHI	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	HardcoreQuesting{The Journey (4.2.4)} [Hardcore Questing Mode] (HQM-The Journey (4.2.4).jar) 
	UCHI	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	UCHI	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHI	JCTweaks{1.24} [JCTweaks] (jctweaks-1.7.10-1.24.jar) 
	UD	BiomeTweakerCore{1.2.128} [BiomeTweaker Core] (minecraft.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	RedstoneArsenal: -[1.7.10]1.1.1-89
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	ThermalDynamics: -[1.7.10]1.1.0-161
	List of loaded APIs: 
		* API_NEK (1.0.0) from Origin-1.7.10-5.0.0-Beta.jar
		* AppleCoreAPI (1.1.0) from AppleCore-mc1.7.10-1.1.0.jar
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.0-102.jar
		* BotaniaAPI (56) from Botania r1.7-201.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.8.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.8.jar
		* BuildCraftAPI|transport (4.0) from RouterReborn-1.7.10-1.2.0.25-universal.jar
		* CoFHAPI (1.7.10R1.0.12) from Ex-Astris-MC1.7.10-1.16-36.jar
		* CoFHAPI|block (1.7.10R1.0.7) from EnderTech-1.7.10-0.3.2.388.jar
		* CoFHAPI|core (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHAPI|energy (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|inventory (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|item (1.7.10R1.0.7) from EnderTech-1.7.10-0.3.2.388.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.25-universal.jar
		* CoFHAPI|tileentity (1.7.10R1.0.7) from EnderTech-1.7.10-0.3.2.388.jar
		* CoFHAPI|transport (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|world (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.25-universal.jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|audio (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.388.jar
		* CoFHLib|gui (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.388.jar
		* CoFHLib|gui|container (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.388.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib|util|position (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib|world (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.388.jar
		* CoFHLib|world|feature (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* compactstorage (v2.0.0a) from compactstorage-1.7.10-release-2.0.0.12-universal.jar
		* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* gendustryAPI (2.1.0) from gendustry-1.5.2.107-mc1.7.10.jar
		* Guide-API|API (1.7.10-1.0.1-20) from Guide-API-1.7.10-1.0.1-20.jar
		* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
		* RefinedRelocationAPI (1.0.0) from RefinedRelocation-1.7.10-1.0.8b.jar
		* Sanguimancy|API (@VERSION@) from Sanguimancy-1.7.10-1.1.9-31.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.5.12.jar
		* Thaumcraft|API (4.2.0.0) from Pam's HarvestCraft 1.7.10i.jar
		* TravellersGear|API (1.0) from TravellersGear-1.7.10-1.16.5.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	PackGuard|ADDITION: The following mods have been added: origin, thaumicexpansion
	PackGuard|REMOVAL: The following mods have been removed: BiomeTweakerCore
	Forestry : Info: The following plugins have been disabled in the config: industrialcraft

How I Fix? I want Playing This PACK.

**Comment by shadowfacts** [comment]
You are using Thaumic Expansion (the cause of the crash) which is not supported by this modpack.
