### ISSUE TITLE
Choppers shearing wrong leaves

### ISSUE THREAD

**Issue by UrbanAshke** [jadedcat/AS2Configs#220]
When using any type of shears in a Chopper, with a shearing upgrade, it produces leaves with the name 'Oak leaves 18:8' which will not function as normal leaves. They can't be placed in composting barrels, can't be used for any crafting recipies and are generally useless. 
They will be converted back to 'Oak leaves 18" which do work normally but only by being placed in the world and using shears on them again.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#15
