### ISSUE TITLE
Tesseract problems

### ISSUE THREAD

**Issue by MrSpellMaster** [jadedcat/AS2Configs#221]
Whenever I try to interact with tesseract my game crashes. I can place it but not interact with it?

**Comment by Trisscar05** [comment]
Logs, paste into pastebin.com and give us the link plox? Crash logs can be seen real time with the console open (via options menu of the launcher) or in the logs folder of the pack.

**Comment by MrSpellMaster** [comment]
I updated the mod and it is working now.
