### ISSUE TITLE
I'm Smeeelting - Seared Bricks

### ISSUE THREAD

**Issue by piurafunk** [jadedcat/AS2Configs#222]
Trying to complete the I'm Smeeelting quest, crafting seared bricks doesn't get picked up by the quest book, even clicking manual submit. Known bug?

**Comment by piurafunk** [comment]
Seems that completing all 16 bricks updates the quest book, but there's no incremental update when you craft only some of them. Minor bug, at most.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#17
