### ISSUE TITLE
Unlimited Enderman Spawning

### ISSUE THREAD

**Issue by Shadesttone** [jadedcat/AS2Configs#223]
Myself and two others have been greatly enjoying Agrarian Skies 2, but after a few days we started to have Endermen spawn on the [Easy] island. They haven't stopped since. We average about 15 Endermen at any given time, "Good" days are 6-8 and bad ones are...Nuts. Whenever it starts to rain, we have a dozen or more endermen teleporting around randomly, shrieking as they take damage. 

If we so much as look up, we get destroyed by multiple Endermen. We don't know how to fix this. It is a privately hosted server. Thank you.
Below are several Imgur links of said issue. (I blotted out my Friends' names at their personal request.)

http://imgur.com/a/lwjbY

**Comment by Trisscar05** [comment]
Can't be certain from the pics, so I'm gonna ask:
Do you currently have a mob trap of some kind going with water as a conveyor for the mobs?

**Comment by Shadesttone** [comment]
No, our only "mob trap" is a small (5x5) box that spawns infinite exploding creepers.

**Comment by Trisscar05** [comment]
Huh. Interesting, and everywhere else is lit up so nothing can spawn I take it?

**Comment by Shadesttone** [comment]
Absolutely. I used F7 and checked all over. We do have Endermen spawning in dark spots, but there's nowhere to spawn on our island, and the small mob spawner/corridor leading from it is always packed full of zombies, witches, and skeletons.

We're in the progress of replacing the entire island with slabs, so maybe that'll help.

**Comment by Trisscar05** [comment]
Endermen can tele about thirty blocks away from a start point if I remember the wiki correctly. Are the dark spots further than that? And if they aren't dark anymore, will they still spawn?

**Comment by Shadesttone** [comment]
We could definitely check, but the only spawning place is a small room (5x5) or so, which is usually full of zombies. Its...Been quarantined after accidents. Additionally, we left the server on overnight, and came back to over 4,000 resonant ender in our smeltery. Good lord.

**Comment by Trisscar05** [comment]
I mean, for purposes of debugging I'd say that using Gamemode 1 to check would be acceptable. This is mostly to check if the Endermen are following the usual spawning rules, or if a mod has screwed with their files somehow.

**Comment by Shadesttone** [comment]
I could try, but the server owner, a friend, probably wouldn't take his time. Still, I could see what we can do...The entire island was replaced with slabs and two-block high roofs, so we're free from Endermen for now. I just have no idea how it happened.

I guess that I might as well close this, thank you for trying to help. Well, actually, thank you FOR helping. We couldn't find the root of the cause but if anybody else has this happen, well, maybe this'll help.
