### ISSUE TITLE
MineFactory Reloaded Fertilizer Issue

### ISSUE THREAD

**Issue by Zoidey** [jadedcat/AS2Configs#225]
Not sure if anyone has noticed or posted this issue (that I could see or find) but here I go anyway.

A friend and myself have noticed how the MFR Fertilizers don't seem to work. You put the MFR fertilizer in it or bonemeal (when you enable it in the config) and nothing happens. It's full of fertilizer and power but just sits there doing nothing. It seems to be an issue with Agricraft as I removed the Agricraft mod and run a singleplayer map and it worked once Agricraft was removed. Maybe it's the cropsticks that are blocking the MFR Fertilizer from seeing the crops (kinda like the issue with the Railcraft invisible blocks). Any fix for this to have them work together (The MFR Fertilizer and Agricraft).

**Comment by Trisscar05** [comment]
Did you try to fertilize vanilla plants, ore plants, and/or Harvestcraft plants, with and without the crop sticks?

**Comment by Zoidey** [comment]
Yeah tried pretty much tried most saplings, Vanilla, Agricraft, Ores, Pam's etc and no luck until I uninstalled the mod.

**Comment by Trisscar05** [comment]
Siiigh, silly Agricraft. Mk, I suggest you go poke the Agricraft forum/github/bug reporting area and see if this is a known thing or not, since if it's just a problem with MFRvAgricraft instead of a pack specific issue, then the mod makers will probably need to do something.

**Comment by Zoidey** [comment]
Yeah been thinking the same thing, thought I'd ask here to see if others have struck this issue also. I think it's the fact that the crop stick are blocking the  MFR Fertilizers sign so to speak so it can't detect any crops in front of it.

**Comment by Trisscar05** [comment]
Well tbf crops are most likely creating their own version of each plant, so not so much that the fertilizer can't see it as it doesn't know what to do with it I assume, might be that crop versions just aren't on the whitelist of fertilizable stuff.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#19
