### ISSUE TITLE
mods are missing

### ISSUE THREAD

**Issue by captainvimes** [jadedcat/AS2Configs#227]
I haven't set up a server from curse before so I decided to look at a tutorial
https://www.youtube.com/watch?v=exNsgyxqSWo

I followed every step through to the end, however when I accepted the eula and started the server up through cmd it is telling me that there are 93 mods missing and asking whether I want to continue without those mods or to cancel. I didn't know whether this was an issue with the server files (forgot to mension I'm using 1.1.14) or whether this is how the modpack was mean't to work

any help would be much appreciated
ps I have never used github before

**Comment by tecrogue** [comment]
Double checking, you have all of the mod  files in the proper folder on your server, yes?

**Comment by Developaws** [comment]
As no response in more than a month, closing.
