### ISSUE TITLE
Server slowly running out of memory

### ISSUE THREAD

**Issue by Timefactor** [jadedcat/AS2Configs#228]
I'm hosting a 1.1.14 server via Creeperhost and we've started having issues with memory depletion.
 
The first thing we noticed is that after the server has been running a few hours, the first player that logs in, gets disconnected immediately but the server shows him as online. After a few minutes, the ghost player is kicked and the player can now join the server.
 
On a reboot, the fresh server is using roughly 20% of the 4GB's allocated to it. After 6-8hours of online time, even with no players playing. It'll be at 80-83% of the RAM used.
 
I've tried loading Opis on the server and client to see if I can determine what's causing the issue but for some reason, Opis doesn't work. It keeps telling me that it's an unknown command. I see no errors on the console or any information regarding Opis on boot. But MapWrite is working as I can see the minimap that loads with Opis. So I'm not sure why the Opis command doesn't work.
 
At this point I'm at a lost as to what to look at next.

I can provide server access if that can help in figuring it out :)

**Comment by Timefactor** [comment]
Finally got Opis working. It was a user error on my part. Issue seems to be caused by an unknown Entity type, after 6 hours or so of running, RAM was up to 80% used again, took me 15 minutes to log into the game. After I was finally in, Ran Opis and it reported 415 entities that have no type. Unsure what they are or how to kill them. A server reboot clears these entities and then the cycle starts over.

I'm now trying to isolate what these entities are and what I can do to stop this from happening.

**Comment by Trisscar05** [comment]
What happens if you use cofh to get a list of entities, does anything interesting appear?

**Comment by cblair91** [comment]
Are you sure people don't have chunk loading, and their systems like sieve, or auto productions aren't spilling over and causing mass tile entities to spawn? :P

**Comment by Developaws** [comment]
As no response in more than a month, closing.
