### ISSUE TITLE
Quest book dissapearing

### ISSUE THREAD

**Issue by snackyzac** [jadedcat/AS2Configs#233]
I made a server. Updated both my client and server however when I make the world and grab the quest book it disappears. That and I cannot trigger the /hqm quest

**Comment by tecrogue** [comment]
What version of the pack are you using, and what map?

Additionally, does this happen when you try it in single player, or only in multiplayer?

**Comment by snackyzac** [comment]
i got it fixed and I was using the single player world

**Comment by snackyzac** [comment]
i followed this word for word and it worked fine so yay https://www.youtube.com/watch?v=g62AJemL9DM

**Comment by tecrogue** [comment]
Hmm. It could be that the version of Java you were running did not like the pack. 

Glad to hear it is working for you now!
