### ISSUE TITLE
I just installed agrarian skies 2 and played, but something happened. Help please!

### ISSUE THREAD

**Issue by MrZwild** [jadedcat/AS2Configs#234]
So I played single player, and started off with the 'Default Platform-Normal' but then this appeared:
Forge Mod Loader detected 18 missing blocks/items

And then it shows me what im missing, help pls what should i do i wanna play normally

**Comment by tecrogue** [comment]
That is caused because the maps were originally created using earlier versions of the mods. Since the mods made changes it does that on the first launch of any of the maps.

Sorry about the confusion, but you are fine to ignore that warning when you first start to play one of the maps.
