### ISSUE TITLE
NPC's don't seem to be spawning

### ISSUE THREAD

**Issue by mylbp2ps3** [jadedcat/AS2Configs#236]
I'm playing on multiplayer with one other friend, I've visited multiple windmills and don't seem to be able to find any NPC's at any of them.

**Comment by Trisscar05** [comment]
Which map did you two start on?

**Comment by mylbp2ps3** [comment]
Don't think we chose a map, we just started the server when it was downloaded.

**Comment by Trisscar05** [comment]
If the windmills are pre-generated, and you're on a sky block, you chose a map. Whether the server has it's own preset I don't know.

**Comment by mylbp2ps3** [comment]
The windmills are pre-generated and we're on a skyblock (same as the one direwolf20 was on, although there was a chest with keys and such in)

**Comment by Trisscar05** [comment]
Look at the various worlds in single player and see if you can find the one the server defaulted to? Once you do, check to see if the npcs spawn there?

**Comment by Developaws** [comment]
As no response in more than a month, closing.
