### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by ThatGermanman** [jadedcat/AS2Configs#237]
My friend is hosting a server, and when I try to join, the game rejects me and said 'Mod Rejection [FMLMod:ae2stuff{0.5.0.56}]. It does this repeatedly, and my game and his are both up to date.
Any help?

**Comment by Trisscar05** [comment]
Could you pastebin and then link the full log please?

**Comment by Developaws** [comment]
As no response in more than a month, closing.
