### ISSUE TITLE
Help, black screen!

### ISSUE THREAD

**Issue by Ploopyploop** [jadedcat/AS2Configs#238]
So, the problem is whenever I try to launch Agrarian Skies 2 using the Curse launcher (Not sure what the name is. I think it was curse voice or curse client), It launches minecraft, only for me to find a black screen where I can't do anything. If I get lucky enough, I will see the Mojang screen but it gets stuck on that too and then crashes. Can someone please help?

**Comment by tecrogue** [comment]
Can you provide any logs? Forge or crash logs would be helpful figuring out
what is going in.

**Comment by Developaws** [comment]
As no response in more than a month, closing.
