### ISSUE TITLE
Zombie Brain Jerky not consistent

### ISSUE THREAD

**Issue by Sorrol** [jadedcat/AS2Configs#239]
![untitled](https://cloud.githubusercontent.com/assets/18319083/14338196/33b22d52-fc75-11e5-86ec-3a2484b0881c.png)
![untitled2](https://cloud.githubusercontent.com/assets/18319083/14338198/36730962-fc75-11e5-9b34-cd1b9c6353e6.png)
![untitled3](https://cloud.githubusercontent.com/assets/18319083/14338199/383d5b26-fc75-11e5-8821-dbbba6d721d8.png)

As you can see, the game says it is a nourishing morsel, regenerating half a hunger point and granting half a nourishment point...
Sadly when eaten it gives 3 hunger points and 5 nourishment points.

This seems to be a bug/inconsistency in Hunger Overhaul...
Getting these is also very easy... A Drying Rack needs 3 Wooden Slabs, a Zombie Brain Jerky needs a Zombie Brain on a Drying Rack for only 30 seconds... And once you've got a decent mob spawner you get endless Zombie Brains...

Cheers,
Sorrol

**Comment by Sorrol** [comment]
Comparing this to drying a Rotten Flesh giving a Monster Jerky... That is a Nourishing Morsel as well, same visual in the inventory, and it does give only the Nourishing Morsel points...
Also that takes 300 seconds on the Drying Rack.

**Comment by pjfranke** [comment]
Did you notice the Thaumcraft Aspect points the brain jerky gives you?

If it was only a morsel of food value, you could chow down on them to quickly gain tons of aspects.  As is, it's such a good food, it slows that process down, unless you have something to burn through hunger.

Not a bug.

**Comment by Sorrol** [comment]
Perhaps change the inventory value and name of food value then?
