### ISSUE TITLE
Unable to repair flint hatchet after Grandmaster'ed and use in a stone chopper

### ISSUE THREAD

**Issue by DaemosDaen** [jadedcat/AS2Configs#24]
After leveling a pair of flint axes (while swapping them in/out of the stone chopper) I got one of them up to grandmaster, and was unable to repair it. I fortunately had enough good luck and for it to get Reinforced X and it can't break (which was my goal). Unfortunately My personal hatchet broke and can not be repaired. I have verified the material (flint) and have tried it, I can not swap out parts or anything (nor can I swap parts on the unbreakable hatchet in my stone chopper

I had another user test it and she can't repair the Hatchetman either.

I did end up just cheating in a new pick (with consensus from other players) with the same buffs. but I lost all my skill XP

**Comment by pjfranke** [comment]
That is intended behavior.  In the IguanaTinkersTweaks\main.cfg, the following setting limits how many times a tool can be repaired.  If you are wanting to use a tool long term, you need to make sure to put Mossy on it before its fully broken:

    # Limits the amount how often a tool can be repaired. -1 means unlimited repairs, like normally. [range: -1 ~ 999, default: -1]
    I:repairsLimit=30

**Comment by DaemosDaen** [comment]
If that is intended, then it may want to be mentioned in quest book somewhere.as several people did not know this was the case.
