### ISSUE TITLE
AS2 nei crash

### ISSUE THREAD

**Issue by freacko00** [jadedcat/AS2Configs#240]
When ever i play with a friend of mine, LAN, him hosting, I crash when i try to look up any of the agricraft seed mutations, but he can view them fine
[crash-2016-04-07_17.08.12-client.txt](https://github.com/jadedcat/AS2Configs/files/209314/crash-2016-04-07_17.08.12-client.txt)

**Comment by Trisscar05** [comment]
Already been at least noted in another thread, though I'm at a loss as to where. Anyone remember the last time this issue was posted and where it is now?

**Comment by Developaws** [comment]
Duplicate of #148
