### ISSUE TITLE
Agricraft blocks missing

### ISSUE THREAD

**Issue by conition** [jadedcat/AS2Configs#241]
Whenever I start in a new map minecraft says there are 489 blocks missing in this save and lists very many Agricraft Blocks and they aren't available ingame.
What to do against that?
thanks for helping

**Comment by pjfranke** [comment]
If you have Agricraft installed, but are starting a new game on one of the included maps, that is normal.

The maps were created several versions ago, and a few mods have been removed, and some have changed names/IDs, so it appears to the user to be missing blocks.

**Comment by conition** [comment]
Ok thank you very much
