### ISSUE TITLE
when i spawn there is no land i know it is a sky island but there is no sky islands

### ISSUE THREAD

**Issue by WolfieRex81** [jadedcat/AS2Configs#242]
please help me

**Comment by Trisscar05** [comment]
Do you have the console open when you load the game? Could we get a copy of the log from that, in pastebin.com or similar link?

**Comment by ManateeOut** [comment]
I also have this problem.
http://pastebin.com/dRUnvSF3

**Comment by Developaws** [comment]
Please provide more information, and logs.
