### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by Kocsisbg** [jadedcat/AS2Configs#243]
Hello 
my  AGS 2 1.1.14 server every time crash or smoething  i have this error 
https://www.dropbox.com/s/47o6s0er49ui27l/fml-server-latest.log?dl=0

**Comment by Trisscar05** [comment]
Please put the crash log into a pastebin and link it, or paste it into this thread. Downloads are generally to be avoided if possible.

**Comment by Kocsisbg** [comment]
<script src="https://gist.github.com/Kocsisbg/4855c3505cece12a49e7ee3fb348cfdf.js"></script>

**Comment by Kocsisbg** [comment]
Herre is  
<script src="https://gist.github.com/Kocsisbg/4855c3505cece12a49e7ee3fb348cfdf.js"></script>

**Comment by Trisscar05** [comment]
Cool, thank you.
Hum, Could we get a description of when it crashes? Are you in world, what are you doing at the time if you are, etc?

**Comment by Kocsisbg** [comment]
if i upload to a server host than wont launch

**Comment by Trisscar05** [comment]
Did you update it to the newest version before the log was created? If so, please downgrade and see if that still works?
If not, downgrade anyway and see if that changes anything.
The log is saying you were missing a bunch of blocks and items when you attempted to load the save. Try creating a new world in the current version and see if that will load?

**Comment by Developaws** [comment]
Logs provided show no crashing/errors, is this still an issue? @Kocsisbg

**Comment by Codingale** [comment]
I think the issue was
```
There are 93 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```
fml confirm seemingly freezes the server, and I couldn't do it without specifying the launch options. Right after that prompt the server stops so I assume it was fml cancel or just closed.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#22
