### ISSUE TITLE
Can not get into world 

### ISSUE THREAD

**Issue by Schniblee** [jadedcat/AS2Configs#244]
whenever i try to get into my world i get this crash 

http://pastebin.com/314EdgWM

please help. Thanks!

**Comment by Trisscar05** [comment]
Go into your SAVE configs and delete the hardcore questing folder. That should reset your progress and hopefully stop the crash. If it works, type "/hqm edit" into chat, which will get you a OP quest book that'll let you re-complete the quests you had done before. Once done with that, toss the OP book into the void and carry on about your day.

**Comment by Schniblee** [comment]
where are the save configs?

**Comment by Schniblee** [comment]
i deleted the hqm folder in the configs and it didnt work. 

http://pastebin.com/XYa1L88A

**Comment by Schniblee** [comment]
i deleted the wrong folder at first but i deleted the right one and it is fixed. Is there a way to get what i had in my inv back?

**Comment by Schniblee** [comment]
That fixed it,  is there a way to get the stuff that i had in my inv back?

**Comment by Trisscar05** [comment]
Wait what, it deleted your inventory?
Could you give me the file path to the folder you deleted?

**Comment by Schniblee** [comment]
open AS2 Folder -> saves -> Sweet Reminice -> delete hardcore questing

**Comment by Trisscar05** [comment]
Whaaaaaaaattt......
That's the correct file path, but hell if I know why it took your inventory with it. Did you get new copies of the starter books when it did so, or was your inventory just empty?

**Comment by Schniblee** [comment]
empty

**Comment by Trisscar05** [comment]
Weird. I think you should use creative (use LAN if you don't have cheats on) to get your things back, and as long as the crash is fixed you should be okay. That is really odd though. It shouldn't have touched your inventory at all, unless something else is at work here. If anything else happens, poke me and I'll try to figure out if it's related.
