### ISSUE TITLE
Crash when using Watering Can

### ISSUE THREAD

**Issue by Cordux** [jadedcat/AS2Configs#247]
I was using the water can (Normal) when it crashed. I Have not put in any other mods or so.
Anyone that can help me?
Here is the log: [Crash-Log](http://pastebin.com/VAbw5T5E)

**Comment by Trisscar05** [comment]
You can't watering can Agricraft empty crop sticks without it crashing. Break all the crop sticks around the area of where you were watering, and be careful or just use Agricraft sprinklers/thaumcraft lamps of growth/any other form of passive growth increase in the future.

**Comment by Developaws** [comment]
Should be fixed as of latest version of AgriCraft, just needs a mod update.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#23
