### ISSUE TITLE
Unable to launch AS2

### ISSUE THREAD

**Issue by ManateeOut** [jadedcat/AS2Configs#249]
Having a problem even launching this modpack.  Any possible solutions?
http://pastebin.com/dRUnvSF3

**Comment by Trisscar05** [comment]
Which launcher, what's your RAM/OS/allocated RAM? And while you did find the likely error, entire logs tend to be a good plan just in case other stuff crops up.

**Comment by Developaws** [comment]
Corrupted forge installation;

1. Write down minecraft version(we need forge version later) pack uses
2. Click `(...)` button
3. Select `Open Folder`
4. Locate `Curse/Minecraft`
4. Open `install/libraries/net/minecraftforge/forge/<version from step 1>´
5. Delete file in the folder. e.g. `forge-1.10-12.18.0.2000-1.10.0.jar`
6. Restart pack
