### ISSUE TITLE
world not loading

### ISSUE THREAD

**Issue by fax99** [jadedcat/AS2Configs#251]
when i try to load a world it just goes back to title screen, but it worked until 2 days ago

http://pastebin.com/wnYKtGru

**Comment by Trisscar05** [comment]
Hum...... M'k, please try a couple things?
-Start a new world, does that load?
-Copypasta the save to a different computer and see if it can be run there?
-Check to see if anything has been updated, including your OS, Java, and your antivirus program

**Comment by fax99** [comment]
New worlds don't load either
Unfortunaltely I don't have another computer to try
I tried to delete and reinstall the mod pack but it won't work...

**Comment by Trisscar05** [comment]
What's the news on things being updated? Since if it affects new worlds as well, that would be the most likely culprit.

**Comment by fax99** [comment]
i installed the pack on multi mc and now it works fine ^^
