### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by beast5888** [jadedcat/AS2Configs#257]
I'm running AS2 1.1.14 and when I try to start the server I get this in the console: 
http://pastebin.com/R7ULtTmA

**Comment by Trisscar05** [comment]
Checklist time!
-OS, Java up to date, both 64x?
-Add any mods to the server version?
-Tried turning your game/computer off and on again?

**Comment by beast5888** [comment]
Update java and got this: http://pastebin.com/R1TuGv8y

**Comment by Trisscar05** [comment]
Delete the hardcore questing folder and reload the whole thing. Btw, is this a LAN server or full on IP server?

**Comment by beast5888** [comment]
It is a full on IP server, After deleting the hardcore questing folder the server still crashed, but I fixed some of the reason it crashed and now I get this: http://pastebin.com/vLFXV1WL
