### ISSUE TITLE
AGSkies 2 ver.1.1.6 Multifarm Bug

### ISSUE THREAD

**Issue by Shadow-player** [jadedcat/AS2Configs#26]
Trying to complete the multifarms quest under Skyfarm,
I built the requested items Farmblocks they ask for 1, but I made 100, Gearbox, Hatch, Valve and Control and the book will not recognize them.  I didn't use stone bricks, I used Quartz blocks.
It is a manual detect so I can cheat in stone ones, but I thought I'd mention it.

**Comment by pjfranke** [comment]
That's not really a bug, then.  It can be hard to see in the book sometimes, especially for things that are subtly different, like potion colors, or the chocolate milk.  However, as you said, the ones in the quest were asking for the gearbox, block, hatch, valve, and control made with stone bricks, not quartz blocks, or any of the other options.

Not following instructions is not a bug.  If a quest asks for Fire Shards (4281:1), and you have Water Shards (4281:2), it's not a bug that it's not accepting them.  Yes, the item ID is the same for the different material Multifarm blocks, but the block data is obviously not the same.

**Comment by Shadow-player** [comment]
No where in the book does it state use stone blocks.  The quest and pictures state: farm gearbox, farm hatch etc.  Yes the picture is of stoneblock version.  The book does state what kind of blocks can go under the multifarm, so it seems it could have been clearer about what the farmblock should be made of.

**Comment by jadedcat** [comment]
Note to self: add oredictionary to farmblocks, change quest to ore dict detect.

(just marking this for later)

**Comment by Shadow-player** [comment]
Would you consider this a bug ?

**Comment by tecrogue** [comment]
With the picture in the book showing the stone block version, for that version it wouldn't be, but if it doesn't accept it later once it is changed to being an ore dictionary detect, then it would be.
