### ISSUE TITLE
Agrarian Skies 2 crashing upon launching.

### ISSUE THREAD

**Issue by zakOwns** [jadedcat/AS2Configs#260]
Hello,
I recently downloaded curse in order to play agrarian skies.
When i am on the minecraft client after clicking play on curse, i continue to click play on the mc client and it crashed almost instantly.
log - http://pastebin.com/yuuRr3XP

**Comment by Trisscar05** [comment]
Try updating Squid API?

**Comment by Developaws** [comment]
You're running java 1.6, update to 1.8.
