### ISSUE TITLE
Nei disappeared

### ISSUE THREAD

**Issue by Foruz** [jadedcat/AS2Configs#263]
When i open up agrarian skies 2 and go into a world in singleplayer it displays a massage that says "A fatal error has occured, this connection is terminated"  and then i try to go into my world in singleplayer again and there is no NEI. There is no button on the bottom left like the mod isn't even installed.But when i go back to main menu and go into the mod list it says that the nei is installed

Has any of you experience this and maybe knows how to fix the problem i would really appreciate it

**Comment by Trisscar05** [comment]
Backup your saves, then delete and reinstall the modpack. Try going in again, and if that fails try a new world to make sure the old one isn't corrupted.

**Comment by Developaws** [comment]
Have you tried pressing "o", or any other keybind you set to hide/show NEI?

**Comment by samuelroy21** [comment]
Yes, press the button "O" when in your inventory. If that works, pls tell us.

**Comment by Developaws** [comment]
Assuming based on lack of reply, problem solves. Re-open if still an issue.
