### ISSUE TITLE
Is using forge bad because im crashing!!!

### ISSUE THREAD

**Issue by CrazyPharaoh** [jadedcat/AS2Configs#264]
I have downloaded forge and i have put the Agarian Skies zipped folder into the .minecraft mods folder and whenever i open minecraft using forge, the game crashes. I have made sure i am using the right forge version, 1.7.10
![image](https://cloud.githubusercontent.com/assets/20958287/17572945/dfa7b058-5f5f-11e6-9889-111c8735bd3a.png)

**Comment by Trisscar05** [comment]
It's probably better to use the Curse launcher, Forge is a bit temperamental if you don't have experience with it. That doesn't mean it's bad, it's just Linux to the easier to use/less control Apple OS.

**Comment by Developaws** [comment]
Please use curse for launching modpacks, we don't support ones outside of curse.
