### ISSUE TITLE
Nether Quest incompletable(?)

### ISSUE THREAD

**Issue by Aserdon** [jadedcat/AS2Configs#266]
The coordinates given are -151, 88, 141. This location is above the bedrock in Nether.  Is there any way to complete this quest?

**Comment by Trisscar05** [comment]
If I remember correctly one of the ways to complete it is to "bug" the bedrock out of the way. There are some tutorials online about how to do this in vanilla based on version, and if I remember correctly a modded way involves the bloodwood tree from Natura.
Another suggestion from Reddit involves ender pearling up through the one block thick roof, though that does mention that it's unpredictable and may take several tries and a lot of pearls.
I think this is supposed to be a "think outside the game mechanics" quest. I'd suggest that you go and have fun with it, and make sure you don't have anything you'd rather not lose on you when you do. XD

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#26
