### ISSUE TITLE
Can't load the modpack, it crashes.

### ISSUE THREAD

**Issue by AquaVirus** [jadedcat/AS2Configs#27]
I installed the Agrarian Skies 2 modpack today and it doesn't load. I can't even see the Mojang screen.
Crash:
http://pastebin.com/kS4LP6tD
Steps to reproduce:
Install Agrarian Skies 2-1.1.8.
Try to play the game normally.
Wait for the crash.

More information:
Agrarian Skies 2 version: 2-1.1.8
Minecraft Launcher version: 1.6.19
Java version: Version 8, update 51 ( build 1.8.0_51-b16 )

(( I have no idea on why the crash report says that I'm using Java 8 update 25. ))

**Comment by dogidogi13** [comment]
does it say something like gendustry and foresty bee thing?

**Comment by Infernalized** [comment]
Th log shows that you are missing a required forge library. You will need to delete the instance and re-download it to get the libraries. As for the Java version you probably have both versions installed on your PC and its using update 25 instead of 51.

**Comment by saekalive** [comment]
also, if this fix doesnt work ^ reinstall java with the latest version of java 7. minecraft runs best on 7 versus 8

**Comment by shadowfacts** [comment]
Not true. There is no "best version" of Java to use for Minecraft. A general trend is that newer versions of Java run better overall because bug fixes and performance enhancements are made in each version.

**Comment by pjfranke** [comment]
The error seems to be related to your Scala libraries.  I don't know if they're corrupted, but it's a good next spot to look.

Mine are downloaded by Curse to my "Curse\Minecraft\Install\libraries\org" folder.  I actually deleted the scala-lang folder, and it was re-downloaded upon launching the game.  They're not actually in the game instance (for me that's Curse\Minecraft\Instances\[pack-name]), so re-downloading the pack wouldn't help.

As Shadowfacts said, there isn't a "Best" Java for performance.  In fact, if you want to give some criteria for "Best", some mods are now making use of Java8 features, which means you won't be able to run the packs with them on Java7 anyway.

Which is really a moot point when using CurseVoice.  My Cursevoice has its own copy of Java8u25, at Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25\bin\java.exe so even if I had Java7 on my computer, OR Java8u51, it wouldn't matter.  Yours similarly is using Java8u25 to run.

**Comment by AquaVirus** [comment]
Where can I find the CurseVoice folder?

**Comment by AquaVirus** [comment]
Pjfranke's fix worked, thanks.

**Comment by Mikejag0** [comment]
hey i have a similar problem 
https://github.com/jadedcat/AS2Configs/issues/291#issue-2680380105
please help as sonn as possible
