### ISSUE TITLE
Downloading from curse, no mods in the pack

### ISSUE THREAD

**Issue by antocs** [jadedcat/AS2Configs#270]
Hello, i tried to download the pack but when i open the .rar, no mods in it, why?

**Comment by Trisscar05** [comment]
Wait, why are you opening the .rar? Are you unable to run the pack from the curse launcher?

**Comment by samuelroy21** [comment]
you see, the RAR doesn't contain the actual mods, or else that file would be HUUUUUUUUGEE. Instead, it has computer code that tells your game where to download all the mods from. It's designed to be installed with Curse launcher, and you'd have a hell of a time trying to do it any other way.
