### ISSUE TITLE
Forge detecting missing blocks/items

### ISSUE THREAD

**Issue by Samboni** [jadedcat/AS2Configs#275]
When I make a new world from a template, I consistently get a message saying that Forge detected either 18 or 19 missing blocks/items. No idea why it fluctuates between those two numbers, but it does. [Picture](https://i.gyazo.com/a912dfa6846f683561de368c418c7eba.png) Any ideas for a fix, and is this a problem? I am downloading using the Curse client.

**Comment by tecrogue** [comment]
This is expected. The templates were created with an older version of those mods, and how they handled those items changed in the later versions.

That is just Forge letting you know it changed, but it will not negatively affect your game in any way.
