### ISSUE TITLE
Can Not Launch AS2 1.1.8 Crash Apears?!

### ISSUE THREAD

**Issue by dogidogi13** [jadedcat/AS2Configs#28]
I guess some thing with forestry and gendustry here is the report. I need help as soon as possible!

https://drive.google.com/open?id=1YaPekq1U-X7xSWxp8xt4L9pkvs0M8N2m0xu9FuH_G7g

Thanks, bye!

Note; I'm from Turkey so that I can not use pastebin.com because it's banned...

**Comment by dogidogi13** [comment]
Also it appears every version of the pack please jadedcat (the cuite one) help me.

**Comment by dogidogi13** [comment]
1) I tryed re-installing every single but the crash 
2) Lower versions; same issuse
3) When I delete gendustry ıt did work (but ı eventually need it so ı musn't delete it [I re-install it])
4) I don't know what to do next please help

**Comment by MarshMilo100** [comment]
did you try reinstalling just gendustry?

**Comment by samuelroy21** [comment]
what is your OS, and what is your version of Java? it worked fine for me.

**Comment by pjfranke** [comment]
Try this suggestion from the (now closed)  bug report thread. I'm on mobile, so not easily able to copy and paste. 

http://minecraft.curseforge.com/forums/jadeds-packs/agrarian-skies-2/773-agskies-2-beta-bugs?comment=2585
