### ISSUE TITLE
Game crash after /give command

### ISSUE THREAD

**Issue by LordToaster** [jadedcat/AS2Configs#281]
So I am playing on Agrarian Skies 2 server version 1.1.14 and I used the command

/give Lord_Toaster 5790  ( This was supposed to be for a leadstone jetpack)

Right after I hit enter my game crashed and it keeps crashing when I attempt to join the server again.
I hope someone can help me with this as I am a complete noob with this stuff.
I do not have another account yet to try and join the server with at the moment but I will as soon as possible.
[crash-2017-01-09_14.55.32-client.txt](https://github.com/jadedcat/AS2Configs/files/693618/crash-2017-01-09_14.55.32-client.txt)

Hope someone can help me ASAP!
Thanks in advance!

**Comment by tecrogue** [comment]
Please use Pastebin for providing crash reports, however you saved this one it mangled the formatting entirely.

**Comment by LordToaster** [comment]
Hi!
Thanks for the reply but I fixed it. I used NBTexplorer to remove the item that I spawned from my inventory via my player file
