### ISSUE TITLE
MCVersion annotation error help. Edit: Graphic drivers problem. User fixed. 1-29-17

### ISSUE THREAD

**Issue by Nbenito** [jadedcat/AS2Configs#282]
I am using AS2 version: 1.1.14
Forge version: 1.7.10-10.13.4.1614

When i try to launch the game. It closes the launcher and then give me an error stating that some core mods don't have "MCVersion annotation." This didn't happen before until today and i was just playing the same profile 2 days ago. I haven't changed anything to the mods, resources packs, Configs, or in-game setting and have already done a full wipe of the profile and did a clean download. i still keep getting the error and have no idea what or how to fix.
Here is the paste bin for the 2 logs i get
GameOutput: http://pastebin.com/Aph431Zd
Launcher log: http://pastebin.com/Cq48scMr

**Comment by Trisscar05** [comment]
Hum. Alright, did you update anything else, like your OS or Java?

**Comment by Nbenito** [comment]
OS is the latest windows 10 and also i tried using the latest Java 8 which at the time was in 121. i also reverted to Java 7 update and it still didn't work. if needed i even went and downloaded individually the two mods that gave me the error standalone and tried that. still same thing happen.

**Comment by Nbenito** [comment]
Ok so i just found out the issue. the issue is the new update to the Nivida Graphics drivers i have. if i use the latest version 378.49. i get this error. when i rolled back to version 376.19. worked as normal.

**Comment by Trisscar05** [comment]
Glad to hear you found it! Also insert obligatory "NVIDIA!!!" gif here.

**Comment by Developaws** [comment]
This issue was moved to JadedPacks/AS2Configs#33
