### ISSUE TITLE
Can't download the modpack

### ISSUE THREAD

**Issue by MonSi37** [jadedcat/AS2Configs#284]
Hello everyone the launcher displays an error when I download this pack.
The others packs works so i don't think thats a connection problem but i dont know what it is
![2017-06-24 1](https://user-images.githubusercontent.com/29674249/27507992-669a06ee-58dc-11e7-82da-6aaddfaaf9a0.png)
![2017-06-24](https://user-images.githubusercontent.com/29674249/27510756-4b0885ae-5918-11e7-94b5-d6816ca2f64d.png)

Please can u help me :'( i want to play on this pack

**Comment by MonSi37** [comment]
up

**Comment by tecrogue** [comment]
I  just tested it using both the launcher and the url given in the error and it worked fine. It looks like that is an issue with either your connection to the Curse servers, or your launcher. 

I would check with the launcher support for assistance. (Click the question mark in the bottom left of it, then select [Get Support] )
