### ISSUE TITLE
Out of Heap Space

### ISSUE THREAD

**Issue by lizardshaman** [jadedcat/AS2Configs#3]
was attemting to join a lan server and it crashed retried it and crashed again

http://pastebin.com/be34PxFm

**Comment by pjfranke** [comment]
Your log has the following lines:

Memory: 31111376 bytes (29 MB) / 497025024 bytes (474 MB) up to 497025024 bytes (474 MB)
        JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m -Xmx4G -Xmx512M

1) How much memory do you have the CurseVoice launcher set to give Minecraft?
2) How much system memory do you have?
3) When you check Task Manager, how much FREE ram did you have before launching AgSkies2?

It looks like you _may_ have it set to give Minecraft 4GB.  That's more than it needs really, unless you're running a resource/texture pack with 32-bit textures, which do tend to consume a lot of RAM.  3GB should be enough for most packs, especially one in a void world, unless you have an established base with a LOT going on....or something that derped out and has tons of loose entities.

**Comment by shadowfacts** [comment]
You can try changing the `-XX:PermSize=256m` option to `-XX:PermSize=512m` to increase the heap space given to Java.

**Comment by lizardshaman** [comment]
tried both things you guys said still not working if you need to know im using a Toshiba satellite c55-a laptop

**Comment by pjfranke** [comment]
Well I only asked you to check information (and ideally to then tell us), not to make any changes.  I may have been unclear, when I saw "-Xmx4096m" I said it looks like you are already set to allow 4GB for Minecraft, not to set it to 4.  I set my games to 3GB, and unless on the F3 screen I see my RAM usage regularly running close to that, I leave it and it works just fine.

At worst, you should be able to create a new instance via CurseVoice, then copy over your /Saves, /JourneyMap, /TCNodeTracker, /options.txt to the new one.  Or not /Saves if you're only playing on a server.
