### ISSUE TITLE
Crash While On Multiplayer

### ISSUE THREAD

**Issue by saekalive** [jadedcat/AS2Configs#30]
Reloaded up just fine. what is the cause/issue? it was a random crash while idle.

http://pastebin.com/9cZPiWmj

**Comment by jadedcat** [comment]
Something, somewhere in the world ticked incorrectly. Its nearly impossible to figure out what.

**Comment by saekalive** [comment]
just happened again while trying to open a resonant satchel

**Comment by pjfranke** [comment]
Have you opened that satchel since the last crash, and before this one?  That is, is there something in there that may have crashed you (a quest reward bee with now invalid attributes, perhaps).

**Comment by saekalive** [comment]
no, ive used it normally since then
