### ISSUE TITLE
Crash when opening any inventory

### ISSUE THREAD

**Issue by BLUESHADOW2020** [jadedcat/AS2Configs#31]
Crash log: http://pastebin.com/U4xTmYvB

Version: 1.1.8

My friend and I were playing together on a lan server over hamachi (I was hosting). Everything was working fine, until when he relogged after he had to go and the the problem started. Everytime he opened any inventory (player or block) he would instantly crash, neither of us changed anything, I was able to open inventories just fine. He tried restarting his computer but that changed nothing.

**Comment by jadedcat** [comment]
Please post your log file from the log folder inside the save location. This is the crash report. I need the full log please.

**Comment by BLUESHADOW2020** [comment]
Sorry about that,
His log file: http://pastebin.com/evJdWDKM
My log file: http://pastebin.com/q2bueHX8

**Comment by MarshMilo100** [comment]
try deleting you player's inventory file in saves/[world name]/data/[all files with the affected players name]

**Comment by MarshMilo100** [comment]
no feedback for over 3 days...

**Comment by BLUESHADOW2020** [comment]
Sorry about that, we found a sort of fix, every time he launches his
client, before he joins my world, he has to enter a single player world and
open his inventory, then he may leave the world and join mine with no
complications. We haven't played in while though so I don't know if it is
still necessary.
