### ISSUE TITLE
Unable to attach Hardened Flux Capacitor to Tool

### ISSUE THREAD

**Issue by leonidasIIV** [jadedcat/AS2Configs#32]
I am unable to attach a Hardened Flux Capacitor to a Mattock made with the following parts and upgrades:
Flint axe head
Bone shovel head
Green Slime Tool Rod
Diamond and Gold Block modifier slot

In order to attach a Hardened Flux Capacitor to the tool, which has over 400 durability as required, I must level the tool up with iguana tweaks so that there are 2 open modifier slots available.

**Comment by jadedcat** [comment]
That's intended. You must have 2 modifier slots to attach the flux capacitor.

**Comment by leonidasIIV** [comment]
Then after applying the flex capacitor, only 1 modifier is used according to the tool top.
