### ISSUE TITLE
redstodendron seeds needs redstone ore?

### ISSUE THREAD

**Issue by NarigudoBR** [jadedcat/AS2Configs#33]
in the later version it needed a machine frame bellow and now it needs a redstone ore,but I don't received a redstone ore in quests

**Comment by hikkiko** [comment]
iirc you can mine some nether redstone and smelt it.

**Comment by NarigudoBR** [comment]
nether redstone will explode right?

**Comment by pjfranke** [comment]
This is intended behavior.  

You are correct, resource flowers previously needed a machine frame, now they require specific blocks based on the flower type, e.g: redstodendron needs vanilla redstone ore.

hikkiko is correct, you can mine nether redstone ore, and smelt that block to get 2 vanilla redstone ore (same for other nether ores mod ores).

Yes, if you do not use a silk-touch pick, it will trigger neighboring ore blocks to explode, spawning hellfish.

**Comment by NarigudoBR** [comment]
thanks pjfranke
