### ISSUE TITLE
White Screen on start up

### ISSUE THREAD

**Issue by Netherguy** [jadedcat/AS2Configs#34]
When I start up Minecraft A black Screen comes up then after 2 minutes it goes white screen and I can here the music for minecraft plz help me

**Comment by shadowfacts** [comment]
Please post the fml-client-latest.log using a service like pastebin

**Comment by Netherguy** [comment]
there is no notepad thing inside logs folder

**Comment by Netherguy** [comment]
it takes me to dicksonware document

**Comment by shadowfacts** [comment]
> there is no notepad thing inside logs folder
> it takes me to dicksonware document
o_O

Open `fml-client-latest.log` inside the `logs/` folder of your instance with Notepad. Then, copy/paste the contents of it into a service like pastebin and post the link here.

**Comment by Netherguy** [comment]
http://pastebin.com/1EUu0YFV

**Comment by jadedcat** [comment]
That is not the full log.

**Comment by pjfranke** [comment]
Typically issues like this are from not enough RAM allocated to Minecraft.  In your CurseVoice Minecraft settings, ensure your RAM is set high enough to play.  http://puu.sh/jFw7z/92b7ba869c.png

How much system RAM do you have?  If you only have 4GB of RAM, you wouldn't be able to allocate much to Minecraft, and may need to close all other programs to play.
