### ISSUE TITLE
Nether Boss "The Terrible" MIA

### ISSUE THREAD

**Issue by Trisscar05** [jadedcat/AS2Configs#38]
Admittedly I'm probably attempting to find it rather early, but the quest opened after I sniped a bunch of creepers, so I figured I'd at least check it out. The coords lead me to an area of exposed heat sand, and the instructions and comments I later found indicated that there should be a giant butterfly at the location, however nothing appeared, and for a good while (till I loaded quite a few more chunks and more ore explosions happened) nothing would spawn in the nether at all, including pigmen and other usual mobs, though nether fish still spawned whenever an ore was mined.
The boss is still MIA, though pigmen have started appearing along with imps and wisps. I haven't gone and found any of the other NPCs yet, so I'm not yet certain if the mod simply isn't functioning or not.

**Comment by pjfranke** [comment]
Which map are you playing on?  Not all of the maps implemented the CustomNPCs npcs, such as JadedCat in the overworld, Soaryn and Morvy in the Nether, and Direwolf20 in the end.

**Comment by Trisscar05** [comment]
Whichever one has the purple clay 3x3 as the start. I believe it was the generic normal one, however the name escapes me atm.

**Comment by pjfranke** [comment]
The Default Platform - Normal map.

I have been playing that one, and can confirm it does not have the NPCs in the nether or overworld.  

Morvy Cottage does have all:
http://media-curse.cursecdn.com/attachments/142/204/ad585e67511abb20faab870f746260d9.png

boni does have the Nether NPCs I understand:
http://media-curse.cursecdn.com/attachments/142/206/08e2cd330e51d76fc639ade043a4fbad.png

I can not say about the other two minimal overworld maps, whether they have the Nether NPCs.
