### ISSUE TITLE
Issue with mob spawning/invisible players and mobs

### ISSUE THREAD

**Issue by srkad** [jadedcat/AS2Configs#39]
We made an Agrarian Skies 2 Single player (with lan connection) and had no problems. All mobs loaded fine, both hostile and "friendly". We decided we wanted to get some friends involved and set up a server. Everything on the mod seems to work correctly except for two things.

1. Mobs are spawning but at a VERY slow rate. I'm talking since we have joined we have seen MAYBE 5 hostile mobs. (We set up a room for them to spawn to test this). In our single player game mobs were spawning like crazy in our mob spawner. We also set up an area correctly for non hostile mobs (Pigs cows etc) 36 blocks from any people with grass and torches. No non hostile mobs will spawn there. In addition when we use the spawn eggs given from quests the animals come out invisible. The only way I have found to get rid of them is by getting thorns enchantments on my armor and having them kill themselves on me. I cannot hit them but they can hit me.

2. People will occasionally become invisible. Kind of like another post I just read where they had to die to be seen again however it is a recurring problem. The only way I have found to fix this is by having them disconnect from the server and reconnect (Or die) but it is only a temporary fix and they become invisible again a short time later. It only happens to one person on the server at any given time and they are invisible to everyone.

As a side note we have no chandeliers or magnum torches set up to prevent mobs from spawning and all settings about mob spawning for my server are set to true.

Any help is much appreciated. Thank you!​

Update: It "seems" as if only pigs are invisible. They also drop items when they die.

**Comment by srkad** [comment]
Anyone have any ideas?

**Comment by MarshMilo100** [comment]
Is there possibly a large buildup of mobs in another dimension that is taking up the mob count?
