### ISSUE TITLE
Crash related to fire elemental from Blood Magic

### ISSUE THREAD

**Issue by dman11235** [jadedcat/AS2Configs#4]
I summoned a fire elemental in my world, and immediately upon spawning the game crashed.  I haven't tampered with the pack as the report claims, other than decreasing the Thaumcraft message scroll rate.  Really don't think that's the issue though...

http://pastebin.com/1gAFcWgB

**Comment by Gloval** [comment]
I am having the same issue.  Have tried a number of different demons and get the same crash.
I see in my AS2 window in the Curse Client that I can upgrade Blood Magic but it does not seem to want to take the update.

**Comment by Gloval** [comment]
This fixed the issue.
Now able to summon any demon I want.

**Comment by dman11235** [comment]
Wait, the LEET version fails?!?!  How!

Anyways, I'll try that.  If I can figure out how the auto-update thing on this launcher works...

**Comment by Gloval** [comment]
If you cannot figure out how to delete/add the mod let me know. I can walk you through it.

**Comment by D3adsh0ter** [comment]
Can you tell me how to update the mod please?

**Comment by MarshMilo100** [comment]
You need to go into profile options in the drop down list from the ••• at the top right of the screen and unlock the profile to change anything
