### ISSUE TITLE
Server Not Starting

### ISSUE THREAD

**Issue by PigKing107** [jadedcat/AS2Configs#40]
When I tried starting the server on MCProHosting I got the error 
http://pastebin.com/W01zmLtv

**Comment by pjfranke** [comment]
As noted lower in the logs, your server host is using Java7:
Java Version: 1.7.0_72

The pack includes PackGuard-1.2.0.jar, which is only compatible with Java8.  You can either see if your host has a way to let you run the pack on Java8, or you can manually upgrade the Packguard jar to 1.3.2 to resolve the issue.
