### ISSUE TITLE
installation failed please check your error log for details

### ISSUE THREAD

**Issue by RcpMCraft** [jadedcat/AS2Configs#41]
i dont know where is the error log but idk why its not working plz help asap

**Comment by pjfranke** [comment]
Please be more clear in what failed.  Were you downloading the pack from CurseVoice and it failed?  Was this at some other stage in the process?

**Comment by RcpMCraft** [comment]
how can i check the error log?

**Comment by RcpMCraft** [comment]
yes the downloading from the cursevoice and idk what you mean in the other question

**Comment by pjfranke** [comment]
Have you tried to re-download the pack?  How fast is your internet connection?  If you have a slow connection, or possibly WiFi issues that could be why it failed.

**Comment by pjfranke** [comment]
You can check your logs at:

C:\Users\[userID]\AppData\Roaming\Curse Client\Logs\CurseClient

When you try to download the pack, if it fails, the most recent log in there will have the data why it failed.  If you don't understand it, post it to pastebin and link here.  FYI, there will be a lot of lines with your Windows userID listed, like the below:

 "message": "Downloading: http://addons.curse.cursecdn.com/files/2215/235/Mantle-1.7.10-0.3.2.jar to C:\\Users\\[UserID]\\AppData\\Local\\Temp\\Curse Client\\1\\468.zip"

If you don't want that publicly shown, open the file in Notepad first, and do a "Replace" for your UserID with something like, "UserID".
