### ISSUE TITLE
Axe of the Stream not working on Greatwood/Silverwood

### ISSUE THREAD

**Issue by Bucket777** [jadedcat/AS2Configs#43]
Thaumcraft's "Axe of the Stream" cannot chop Greatwood / Silverwood trees. The stream function works with vanilla trees (Eg. Oak).

AS 1.1.8 (Alternative + Native Launcher).

**Comment by pjfranke** [comment]
I can confirm I saw this in 1.1.6 as well.  I can't see anything in the configs that indicate it is specifically set higher, or the Axe of the Stream is set lower.  It's possibly a thing that needs to be overridden and never was.

As a workaround, you can use a Thaumium grafter to harvest the leaves until you have enough sapling drops, then use a different tool to harvest the wood (Terra Truncator, Lumber Axe, MFR harvester, etc).  The Thaumium Grafter has VERY LOW durability. so I would recommend enchanting it with Repair (preferrably 5) first, then have a wand on you for it to repair from.

**Comment by MarshMilo100** [comment]
Thaumcraft log blocks need mining level 6, but the axe of the stream only has a mining level of 5. So it cannot mine them.

**Comment by MarshMilo100** [comment]
We will change the axe's level to 7. You can do this manually by going into config/iguana tinker tweaks/tooloverrides.cfg and under thaumcraft change axeelemental to 7 from 5.
