### ISSUE TITLE
Rune of Earth not crafting in the Runic Altar after right clicking with the wand of the forest

### ISSUE THREAD

**Issue by TheDerpyCat** [jadedcat/AS2Configs#45]
Version 1.1.8
I put in all the right items, the three manasteel, the stone block, the coal block, and the mushroom.
theres plenty of mana being connected via a mana spreader from a mana pool that has some mana in it, and when I right click with the wand of the forest it doesn't show the symbol gaining mana. I crafted all the rune of spring, fire, water, mana, and air perfectly fine. I'm also playing on a server with the newest version.
![2015-08-12_14 21 28](https://cloud.githubusercontent.com/assets/13770109/9233073/1453cb8c-40ff-11e5-94b0-94fa895edf3b.png)

**Comment by pjfranke** [comment]
If it is not recognizing it as a valid recipe, remove the items (shift+right-click with an empty hand), break the alter, re-place and try again.

Are you sure the pool has enough mana to make the recipe?  It may not start if there is not enough to complete.

**Comment by TheDerpyCat** [comment]
It still didn't work after removing the items, breaking the altar and doing it again. And to test if it had enough mana I threw a few black lotus and it still didn't work.

**Comment by pjfranke** [comment]
A basic rune crafting recipe costs 8500 mana, and a black lotus adds 8000.  Certainly tossing 2 in would give you enough mana.

Does NEI show it as a valid recipe?

If you launch a SSP game and cheat in the necessary items, are you able to craft it OK?

Have you asked if anyone else on the server is having issues?

**Comment by TheDerpyCat** [comment]
yeah I threw in two and it didn't work and yes nei said that it is a valid recipe. In SSP it work. And its my server that im playing with my friend and he couldn't get it to work either
