### ISSUE TITLE
Ghastlymoss Missing Texture

### ISSUE THREAD

**Issue by natedogith1** [jadedcat/AS2Configs#47]
Same as #46, except as far as I can tell the texture file doesn't exist. Forgot to mention, this is on the second growth stage. Also, looking at it closer, it appears the second stage file is listed as the first stage file, and the file that should be the first stage doesn't exist.

**Comment by pjfranke** [comment]
Confirmed, a the mis-labeled textures will be corrected, and the missing texture file added.
