### ISSUE TITLE
Spawn Eggs Don't Show up in NEI

### ISSUE THREAD

**Issue by natedogith1** [jadedcat/AS2Configs#48]
Simply put, the spawn eggs don't show up in NEI. I'd pass this off as intentional, except that the spawn eggs have recipes.

**Comment by pjfranke** [comment]
The reason you don't see them (or only the 1 generic) is that INpureCore is filtering out items.  The settings for that can be adjusted to show or hide variations of the same item with varying metadata.  This may or may not be adjusted in the next update.

If you want to adjust it yourself, you can use the information here to change the config for INpureCore:

http://forum.feed-the-beast.com/threads/inpurecore-custom-nei-filters.97975/
