### ISSUE TITLE
Thaumcraft NEI Plugin

### ISSUE THREAD

**Issue by natedogith1** [jadedcat/AS2Configs#49]
So two issues here.

1) There are two thaumcraft nei plugins.

2) One of the plugins has issues. (I believe this is Thaumic NEI (file name gud_thaumicnei) )

To expand on 2. When I look up an Arcane Crafting Table recipe, the plugin will show that recipe whenever I try to lookup anything else.

To reproduce 2: Have an item that's created in the Arcane Crafting Table unlocked. Look up the recipe for that item in NEI. Look up the recipe for something else in NEI. Look through all the recipe types (the top buttons), one of them will show the recipe for the Arcane Crafting Table item.

**Comment by pjfranke** [comment]
There being 2 plugins isn't a bug, they do work differently.  If you prefer not to use one or the other you can disable it.

Yes, one has issues.  That is already being addressed here:

https://github.com/jadedcat/AS2Configs/issues/15

Unless there is an update from the author fixing the bug, it will be downgraded to 1.2.3 in the next version of the pack.

**Comment by natedogith1** [comment]
How do they work differently?

**Comment by MarshMilo100** [comment]
Thaumcraft nei plugin shows recipes and uses for the different aspects as if they were items in nei. Thaumic nei allows you to search for a specific aspect, such as aer, and see all of the items that have that aspect on them in nei.

**Comment by pjfranke** [comment]
To expand on what MarshMilo100 said...

Thaumcraft NEI plugin has several features, such as showing unlocked Infusion, Crucible, AND Worktable recipies, as well (as mentioned) as showing the aspects, what compound aspects they're used in, and what scanned items contain that aspect.  It integrates with the NEI items page by having the aspects you have discovered listed, and anything not discovered is a "?" icon.  It does support shift-clicking items into a worktable, as well as the Arcane Crafting Terminal.

gud Thaumic NEI doesn't have anything that appears in NEI, but if you click an unlocked arcane recipe it will show you how to make it, whether via worktable, crucible, or infusion.  One nice feature is if you look up an infusion recipe, you can click the Runic Matrix icon in the upper right, and see all discovered infusion recipes.  Version 1.2.3 did not support shift+clicking into a worktable, that was added in 1.3.0, but so was the mentioned bug.

They both add at least 1 unique feature to the game it seems.

**Comment by natedogith1** [comment]
So, if I understand right, Thaumcraft NEI plugin has the aspect stuff, and gud Thaumc NEI lets you look at all recipes for worktable/crucible/infusion? Is that all?

**Comment by pjfranke** [comment]
Yes, that seems to be a primary difference.  Otherwise, they have different looking GUIs, and behave slightly differently in those regards, but primarily have the same function.  We are downgrading the mod from 1.3 to 1.2.3 to fix the "sticking" bug, at the expense of losing the shift-clicking from NEI, but both will be staying in the pack.  Once an updated version is released, we will then add it in the next pack update.
