### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by bakaxyf** [jadedcat/AS2Configs#5]
I used ServerStart.bat in zip file.
[fml-server-latest.log] (https://gist.github.com/bakaxyf/6b234bfcdd9c2dcf73d6)
edit: version 1.1.8

**Comment by shadowfacts** [comment]
This looks like a problem caused by PackGuard when it tries to cache. Do you have any special characters in the directory structure leading up to the instance directory?

**Comment by bakaxyf** [comment]
Problem solved, sorry for bothering.
