### ISSUE TITLE
Applied Engineering

### ISSUE THREAD

**Issue by GamingWithAGoose** [jadedcat/AS2Configs#51]
For some reason, the Applied Engineering quest line only shows one quest for me. I've completed the quest but no other ones show up after. I know that there are more quests because I've seen them for other people and it says I have only completed 8% of the quest line. Can someone please explain what's gone wrong?

**Comment by MarshMilo100** [comment]
There are many quests throughout the book that require quests from other quest lines to be completed as parent quests first.

**Comment by pjfranke** [comment]
You need to progress further in the Storage Wars quest line to trigger more quests to appear in the Applied Engineering tab.
