### ISSUE TITLE
TE/TD: Inconsistent RF Values

### ISSUE THREAD

**Issue by Pyr0Byt3** [jadedcat/AS2Configs#56]
When Thermal Expansion 4 was released, the RF values for a lot of things changed. Currently only Thermal Dynamics Fluxducts have the updated values, which is kind of weird, because Leadstone/Hardened/Redstone/Resonant Fluxducts can now transfer 200/800/8,000/32,000 RF/t respectively, but Energy Cells and Flux Capacitors are still using the old 80/400/2,000/10,000 RF/t curve. The RF storage capacities of these items were also buffed a bit to better accommodate the greater RF/t bandwidth.

Far be it from me to tell the Jaded One herself how to balance a modpack, but I'd love to see the Cell/Capacitor values updated to match vanilla TE; although lowering the Fluxducts' values is also a viable option to make things consistent.

**Comment by MarshMilo100** [comment]
you can configure the rf send/receive values for the various cells in the config/cofh/thermalexpansion/common.cfg, this will possibly be updated in the next version.
