### ISSUE TITLE
Amaranth Logs Producing wrong planks in TE Sawmill

### ISSUE THREAD

**Issue by the-began** [jadedcat/AS2Configs#57]
Placing Amaranth Logs in Sawmill produces 6 Eucalyptus Planks

**Comment by MarshMilo100** [comment]
I can confirm this as an issue.

**Comment by MarshMilo100** [comment]
we have notified the makers of both mods involved, if neither of them can fix the issue, jadedcat will implement a fix herself. hopefully will be fixed next update.

**Comment by pjfranke** [comment]
https://github.com/progwml6/Natura/issues/234

Bug posted on the Natura tracker.
