### ISSUE TITLE
Tinker's construct tools gaining xp for no reason

### ISSUE THREAD

**Issue by XxZajoZzO** [jadedcat/AS2Configs#59]
When I hold any tinker's construct tool/weapon in my hand the tool will level up for no reason.
Video: https://www.youtube.com/watch?v=SgGDafdD4bs
Pack Version: 1.1.8
Added mods: Chisel, Ztones, Carpenters blocks, ChiselTones
fml-client-latest.log: https://dl.dropboxusercontent.com/u/92370990/MC/fml-client-latest.log

**Comment by pjfranke** [comment]
Do you have a Drill of the Dead ritual running on your blood altar (well anywhere really)? That will put the effective XP from the kills onto held items.

**Comment by XxZajoZzO** [comment]
I did and when I removed it it stopped. Thanks
