### ISSUE TITLE
I Broke the game :x

### ISSUE THREAD

**Issue by Neooxys** [jadedcat/AS2Configs#6]
I Don't know how this happened but it's quite a bad thing & i'm scared of lags :|
Any Way to fix it? :|

http://imageshack.com/a/img661/2946/k71Ei2.png

**Comment by Neooxys** [comment]
They keep respawning at the same place when i kill them !!!

**Comment by Neooxys** [comment]
I just let like 20 Jaded In Lave then i built back the original platform, & for some reason it worked! XD

**Comment by Neooxys** [comment]
They're back...
And the lava isn't working anymore...

**Comment by dmf444** [comment]
try /cofh killall, that should kill all entities
(may kill any cows/pigs/sheep so be wary of using it)

**Comment by jadedcat** [comment]
cheat in a "npcwand" right click the "Jadedcat" npc. Choose delete.

**Comment by Neooxys** [comment]
Thanks for the tip, i'll try it!

**Comment by Neooxys** [comment]
Oh, and i have another problem with the NPC Direwolf20, when he ask me to help him, the answer "Yes" isn't working, and the "No way" is increasing my agressive statut :|
