### ISSUE TITLE
Creating Destablised Redstone in Smeltery

### ISSUE THREAD

**Issue by the-began** [jadedcat/AS2Configs#60]
Redstone isn't melting in smeltery, dust stops at about 1/2 way and block stops at about 1/3, recipes like signalum work in smeltery if you add destablised redstone, just unable to melt it in smeltery

**Comment by pjfranke** [comment]
That is by design, lava is not hot enough. You can see this in NEI on the recipe for destabilized redstone in the smeltery. I don't recall what does show the temperature of lava though, I just know it's not enough. 

To make it work, to melt redstone you need to use blazing pyrotheum.
