### ISSUE TITLE
Crash while summoning an Elemental (Blood Magic)

### ISSUE THREAD

**Issue by x1xHEADSHOTSx1x** [jadedcat/AS2Configs#66]
Was trying to summon the Air Elemental from Blood Magic and the game crashed. It crashes now every time I open it. The top link is to the original crash and the second is a link to the crash on loading. Game is currently unplayable please advise. Thanks.

Original Crash: https://www.dropbox.com/s/9judaoljjt83uju/crash-2015-08-17_23.08.19-server.txt?dl=0

Loading Crash: https://www.dropbox.com/s/quj2k2c01xc8ram/crash-2015-08-17_23.11.43-server.txt?dl=0

**Comment by pjfranke** [comment]
That is a known bug in the current version of Blood Magic that ships with 1.1.8.  The next pack update will include an updated Blood Magic which corrects this issue.  You can unlock the pack yourself and update Blood Magic to fix your issues prior to the pack update release.
