### ISSUE TITLE
Thaumic Expansion is not working

### ISSUE THREAD

**Issue by noobyaran9** [jadedcat/AS2Configs#67]
This mod doesn't show up in the thauminomicon and the recipe won't show up in the NEI even with the creative thauminomicon.

**Comment by MarshMilo100** [comment]
it appears that thaumic expansion is not a finished mod. in an instance with just thaumic expansion and its dependents, there are no entries in the thauminomicon or recipes for any of the items within the mod, yet. we will contact the mod author about these issues.
