### ISSUE TITLE
Crash on first time launch

### ISSUE THREAD

**Issue by polkinghorbd** [jadedcat/AS2Configs#68]
Sorry if this has been covered already, I just want a way to fix it through Curse Voice
I load up Curse Voice, click on play on the agrarian skies 2 modpack, and it loads the launcher.  Hit play again and it gives me this without even loading up the Mojang symbol
http://pastebin.com/K5fER3E7
If I could get help it would be greatly appreciated
I am running 1.1.8

**Comment by MarshMilo100** [comment]
you are issing some important forge libraries, you need to delete and reinstall the agrarian skies instance in curse voice.

**Comment by pjfranke** [comment]
See my comments here to see if that will resolve your issue:

https://github.com/jadedcat/AS2Configs/issues/27#issuecomment-128916662

**Comment by MarshMilo100** [comment]
See closed issue #27. That is the same issue
