### ISSUE TITLE
Earth Element - Possible bug

### ISSUE THREAD

**Issue by mezoty** [jadedcat/AS2Configs#69]
If pour in Casting Table Liquified Emerald on Rune of the Earth this from Casting Table not disappear, but behaves like a classic TC Cast. From one Rune of the Earth, you can pour unlimited amount of Earth Element. I do not know if this is correct, but the logic says it is not.

**Comment by MarshMilo100** [comment]
I apologize, but I do not understand what your exact issue is, could you try to be a little more clearer.

**Comment by saekalive** [comment]
he is saying if you pour liquid emerald on the rune, the rune doesnt dissapear from the casting table and allows for a dupe

**Comment by MarshMilo100** [comment]
i believe this is intended behavior.
