### ISSUE TITLE
Hopefully Brain Jerky isn't supposed to do this?

### ISSUE THREAD

**Issue by freddy705** [jadedcat/AS2Configs#72]
Was about to die ingame, i found out that i chould dry brains and zombie meat for jerky. The monster jerky is only filling half of my hunger bar and nothing "bonus".

However, dried brains (Brain Jerky) fills 3 - 3 1/2 on food bar and also gives 6 "well fed" ?

This can't be right? (i hope)

**Comment by pjfranke** [comment]
It's right. Did you notice the Thaumcraft aspects you got when you ate the brain jerky? If you could just chow tons of them to fill from almost empty hunger, it'd be a bit OP for how quickly you'd gain aspects. It's a trade-off.
