### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by cdenoo** [jadedcat/AS2Configs#74]
Circumstances:
- Thaumcraft infusion of portal-in-a-box
- All requirements fulfilled
- Start infusion
- Eldritch Eye gets blown off by thaumic goo (instability)
- Place Eldritch Eye on goo-filled pedestal
- The same Eldritch Eye gets blown off by the same goo
- Crash

- Restart client
- Load world
- Crash
etc.

LOG:

Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.tiles.TileInfusionMatrix.craftCycle(TileInfusionMatrix.java:483)
	at thaumcraft.common.tiles.TileInfusionMatrix.func_145845_h(TileInfusionMatrix.java:224)

**Comment by MarshMilo100** [comment]
this is a very similar issue that was unconfirmed. https://github.com/jadedcat/AS2Configs/issues/65

**Comment by MarshMilo100** [comment]
is this issue reproducible in another world?

**Comment by MarshMilo100** [comment]
... or possibly try to load a backup from before the crash ocured.

**Comment by pjfranke** [comment]
As noted, this seems to be very much the same as an error noted in #65 , a random thing ticked badly.  Unfortunately, it may be a bug in Thaumcraft, but the solution is the same as there.  Roll back to a backup prior to the error, or MCEdit to remove your Runic Matrix should fix it.

How stable was your altar setup?  It doesn't fix the bug, but it should help prevent it from recurring if you symetrically place more mob heads, botania glimmering or floating flowers or pylons, crystal clusters, etc to prevent instability.

**Comment by cdenoo** [comment]
Yeah, I read the other issues before your response and I already rolled back.
It's still a bit strange, but whatever.
I have not managed to reproduce it in another world, but as pjfranke said: it's probably random.
Thanks for the help ;)
