### ISSUE TITLE
Not really a bug but I bet it is definetly not intended

### ISSUE THREAD

**Issue by sensisamurai** [jadedcat/AS2Configs#75]
Ok, so this is 2nd time I'm playing AS2 through and this is second time i am using this.
What you can do is make ton of aluminum ingots and make them to buckets, melt down buckets in smeltery and you get iron from them. Sure it has come handy but I bet this is not intended

PLS NO HATE!

**Comment by MarshMilo100** [comment]
this is an issue and will be fixed for the next update... buckets will not be able to be melted in a smeltery.

**Comment by MarshMilo100** [comment]
just don't abuse it until it is fixed.
