### ISSUE TITLE
Golemancer bell

### ISSUE THREAD

**Issue by shooter044** [jadedcat/AS2Configs#78]
Game crashes when you try and make a Golemancers bell in a arcane crafting terminal. I tried twice on my server and had the same result both times. It doesn't happen till you attempt to pull the crafted item out of the interface.

**Comment by tecrogue** [comment]
Can you link your crash log please?

**Comment by tecrogue** [comment]
Confirmed issue. It looks like a work around while we find where that bug is hiding would be to create it in the Thaumcraft Arcane Worktable. As a note, the same error happens with that if you close the interface before you craft it.

http://pastebin.com/yGTu2kBu

**Comment by pjfranke** [comment]
It appears this happens in the Arcane Worktable too, if you close and re-open the table without crafting the item.  Something is duplicating the item in NEI, with an item ID of "-1", and making the recipe invalid when selecting it via NEI.

I saw CustomNPCs listed in the crash report too, but this still fails even without that mod loaded.

**Comment by cblair91** [comment]
@shooter044 Is this still occurring with the latest version?

**Comment by cblair91** [comment]
No response from author, closing.
