### ISSUE TITLE
Smeltery - Blocks dissapearing

### ISSUE THREAD

**Issue by Sn3akr** [jadedcat/AS2Configs#80]
I've been using the smeltery in 1.1.8 and have an issue with blocks dissapearing from the casting basins from the TC smeltery

Edt: Using the standard pack with no alterations - installed 1.1.8 from scratch because of some bug/me being stupid and i couldn't import my old install/saves after a reinstall on my PC. Running win7 ult. - java 8.60

**Comment by pjfranke** [comment]
This is the first we have heard of this issue.  Can you take a video showing the issue?  Are you sure they're not being pulled out of the basin via a transfer node, retrieval node, itemduct, hopper, etc?  That seems the most likely scenario.

**Comment by Sn3akr** [comment]
Nevermind.. Was just me being a derp :-1:
