### ISSUE TITLE
Missing manyullynclematis and bush

### ISSUE THREAD

**Issue by senjinthedragon** [jadedcat/AS2Configs#81]
The manyullynclematis and bush are present in the config files but a comma is missing so they don't show up.
agricraft/CustomCrops.txt line 64-65
manyullynclematis,TConstruct:materials:30,minecraft:soul_sandTConstruct:MetalBlock:2,3,1, The nether is no fun
manyullynbush,TConstruct:materials:5,minecraft:soul_sandTConstruct:MetalBlock:2,3,1, The nether is no fun

should be:
manyullynclematis,TConstruct:materials:30,minecraft:soul_sand,TConstruct:MetalBlock:2,3,1, The nether is no fun
manyullynbush,TConstruct:materials:5,minecraft:soul_sand,TConstruct:MetalBlock:2,3,1, The nether is no fun

**Comment by pjfranke** [comment]
Noted for next update, thank you.

**Comment by senjinthedragon** [comment]
There's no graphics/tile for them either afaik

**Comment by pjfranke** [comment]
For the seed, or for the plant.  Confirmed and noted.

**Comment by Tarig0** [comment]
also note mutations don't seem to be registered

**Comment by Chinthor** [comment]
Trying to fix this and others in my client. The mutations.txt file says to use minetweaker, but minetweaker is not installed that I can see. Though there is a minetweaker log, the mod is not here and there are no scripts either. Then again, when I change the mutations.txt, nothing happens. Any tips for what I'm doing wrong?
