### ISSUE TITLE
unable to make living wood- logs disappear

### ISSUE THREAD

**Issue by darrya** [jadedcat/AS2Configs#83]
when I put logs of any type around my pure white daisy they just disappear instead of turning into living wood- it just started doing this after I updated today.  I captured it on video but it wont allow me to attach it here to show you

**Comment by pjfranke** [comment]
I've tested and am unable to duplicate this.  Can you show your setup?  You can't attach a video directly, but if you can post it somewhere and link it that will allow us to see.

**Comment by darrya** [comment]
im not very social media savy- where could I post it for you?

**Comment by pjfranke** [comment]
If you don't want to share your Google/Youtube account, you could use https://vid.me/

Without an account, you can upload 256MB videos up to 10 minutes long.
With an account, you can upload 1GB videos up to 10 minutes long.

**Comment by darrya** [comment]
https://vid.me/IBNK thank you I uploaded it on vid.me  I don't have a youtube account.

**Comment by pjfranke** [comment]
Thanks.  I see you're using Acacia wood...does it do the same thing with other woods?  What about Oak logs?

I will test with Acacia when I can this evening.

**Comment by darrya** [comment]
yup it ate up all my oak and a bunch of spruce doing that same thing.  every now and then I would get living wood-it double pops when it actually makes some.  I can try to get more videos for u

**Comment by pjfranke** [comment]
Ah.  Are you playing SMP or SSP?  Is this a new instance, or a prior game upgraded to 1.1.13?

**Comment by darrya** [comment]
im playing single and its a world I started about 10 days ago.  the problem began when I installed the update a few days ago

**Comment by darrya** [comment]
ok I just took one with oak - shows me placing the blocks and then disappearing I will upload it and post the link for u

**Comment by darrya** [comment]
https://vid.me/Qjo7   here is oak

**Comment by pjfranke** [comment]
That's very odd, especially as they're disappearing well before 60 seconds (the conversion time).

Unfortunately I don't know why they'd be doing that, especially if there's no logs to indicate the strange behavior.  Try moving the pure daisy elsewhere, and see if it still happens.

**Comment by darrya** [comment]
Ok I will try that and see what happens. Maybe 5% of the time I do get some living wood but mostly they disappear on me

**Comment by MarshMilo100** [comment]
is this issue still happening? or has it been resolved?

**Comment by darrya** [comment]
Yes it's still doing it. I'm frustrated I do not want to have to cheat things in

**Comment by pjfranke** [comment]
Is this still an issue for you with the current pack version?

**Comment by cblair91** [comment]
No response from author, closing.
