### ISSUE TITLE
Endermen keep spawning when using reinforced watering can

### ISSUE THREAD

**Issue by ahmed4455666** [jadedcat/AS2Configs#86]
when using reinforced watering can and right clicking it says variable WATERINGCAN value is 2
i keep right clicking to use it when it hits 10 it spawns enderman

1.craft a reinforced watering can
2.keep right clicking till it says variable WATERINGCAN value is 10
3. enderman spawned very wierd bug

the map i used on it the reinforced wateringcan is default platform

this bug is on ver 1.1.13

**Comment by pjfranke** [comment]
That is an intentional behavior added in the pack; not a bug.
