### ISSUE TITLE
Ex Astris

### ISSUE THREAD

**Issue by Joly0** [jadedcat/AS2Configs#87]
Ex Astris is a Dead Project. The Mod author ihas redone the mod. So please Update to Ex Astris Rebirth, its based on Ex Astris, just with usefull bugfixes and extras. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2424837-ex-astris-rebirth-mod-compatability-for-your or https://github.com/Ex-Astris-Rebirth/Ex-Astris-Rebirth/releases

**Comment by pjfranke** [comment]
Did you read the warning on the thread page?

*Warning : This version is not compatible with previous Ex-Astris. (if you change mod, all of items are gone)*

That's kind of a big deal, and many folks wouldn't be happy about suddenly having to re-make all the items, re-build their sifting infrastructure, etc.

When the pack has a major update...the kind that can break saves, and a world-reset is encouraged, THAT'S when a change like that is appropriate.  That will eventually be coming, but not soon.
