### ISSUE TITLE
Missing blocks warning on new game

### ISSUE THREAD

**Issue by PixelSupreme** [jadedcat/AS2Configs#88]
Fresh installation of version 1.1.13 of the pack through curse client. Every time I start a new game I get a warning about missing blocks/items. The missing items are:

AWWayofTime:itemBloodMagicBook
Botania:excaliber

**Comment by tecrogue** [comment]
This is due to the maps being created with an older version of those mods. The items no longer exist, but it will not cause issues with your saves outside of that first warning.
