### ISSUE TITLE
Agricraft Rare Seeds

### ISSUE THREAD

**Issue by noobyaran9** [jadedcat/AS2Configs#9]
After updating to 1.1.8 all my agricraft rare seed turn into black and pink block.

**Comment by Infernalized** [comment]
Any images?

**Comment by noobyaran9** [comment]
<img width="349" alt="bug" src="https://cloud.githubusercontent.com/assets/13598309/9022062/ba44663e-3897-11e5-8274-84b914360b8d.png">
I accidentally deleted my old world saves so i can't show you when it was planted after i update to 1.1.8.
I can only tell you is that it can't be planted / harvested after growing fully (shown in WAILA).

**Comment by dmf444** [comment]
can we see the fml latest client log?

**Comment by noobyaran9** [comment]
http://pastebin.com/bYmr72YH

**Comment by shadowfacts** [comment]
Hmm, my first guess is that AgriCraft is corrupted or incomplete. Try re-downloading AgriCraft from Curse.

**Comment by noobyaran9** [comment]
Tried redownloading, still not fixed. I bet it was the config problem.

**Comment by jadedcat** [comment]
That looks like the texture files I added vanished for some reason. I'll look into it.

**Comment by InfinityRaider** [comment]
Is the correct ResourcePack enabled?

**Comment by noobyaran9** [comment]
It was the ResourceLoader mod missing that caused the problem.

And i also found out that there were a few mod missing from the 1.1.8 server.zip, they were : 
ResourceLoader
CustomMainMenu
BiomeTweakerCore
JourneyMap

**Comment by pjfranke** [comment]
JourneyMap and CustomMainMenu are client-side mods, they wouldn't be applicable to a server.

ResourceLoader looks like it would also be a client-side mod, and not necessary on the server.  Some client-side mods can cause issues with launching a server if they're installed (unless Forge now can ignore them).  That's why they're not installed.

BiomeTweakerCore sounds like I'd expect it to be necessary on a server for it to actually work though.

**Comment by noobyaran9** [comment]
ResourceLoader is required for the agricraft rare seed. (And other texture in the resource folder in the .minecraft file)

**Comment by pjfranke** [comment]
> ResourceLoader is required for the agricraft rare seed. (And other texture in the resource folder in the .minecraft file)

Obviously required client-side, but I was referring to it being needed on the server.  The server isn't telling you which images to use for items, only that the items exist. The ResourceLoader mod then maps the image files to those item IDs.

**Comment by jadedcat** [comment]
If you are using the server files to play client side you will need to add the missing mods back in.
