### ISSUE TITLE
Can't Load Agrarian Skies 2

### ISSUE THREAD

**Issue by MrBuddha19** [jadedcat/AS2Configs#90]
Whenever i try to launch AS2 i get this crash report. 

http://pastebin.com/4wrLviXT

**Comment by dmf444** [comment]
Try reloading the pack, one of the packages appears to be missing

**Comment by MrBuddha19** [comment]
i uninstalled and reinstalled 3 times same thing happens

**Comment by pjfranke** [comment]
The issue is not with the pack, it's likely any other pack you download and try to play would crash too.

This seems to be the same error as was noted here, text copied below for convenience: https://github.com/jadedcat/AS2Configs/issues/27#issuecomment-128916662

> The error seems to be related to your Scala libraries. I don't know if they're corrupted, but it's a good next spot to look.

> Mine are downloaded by Curse to my "Curse\Minecraft\Install\libraries\org" folder. I actually deleted the scala-lang folder, and it was re-downloaded upon launching the game. They're not actually in the game instance (for me that's Curse\Minecraft\Instances[pack-name]), so re-downloading the pack wouldn't help.

**Comment by MrBuddha19** [comment]
Thanks alot worked like a charm
