### ISSUE TITLE
Crash upon loading world 1.1.13

### ISSUE THREAD

**Issue by DoNotWardBaron** [jadedcat/AS2Configs#91]
Upon attempting to load my single player world, I seem to crash for a reason which is unknown to me, crash report can be read here: http://pastebin.com/NjXn0j4z

I can load/create any other world, it is only the one which I have done work on that seems to crash. If anyone could me with this issue so I can continue playing my save as soon as possible, it would be greatly appreciated. Thank you in advance.

**Comment by MarshMilo100** [comment]
See issue #42. This is the same error
