### ISSUE TITLE
Weird tick drops

### ISSUE THREAD

**Issue by Gravlok** [jadedcat/AS2Configs#92]
I have weird tick drop. I host the server on my laptop (i5 4210U, 8GB RAM) and play on my desktop (Phenom II X4 965 BE, 8GB RAM). The TPS reported by server is correct 20/20, but I still encounter tick drops i.e.: a random cow spawn is rushing towards me and it doesn't run smoothly. It rather teleports small distances every half a second and even if I'm constantly swinging my sword at it I'm still getting hit, and then the cow dies in the next "frame".

**Comment by MarshMilo100** [comment]
Is the tips usually normal but only drops every once in a while? Because this is usually how minecraft servers in general work, especially on a laptop.

**Comment by Gravlok** [comment]
No, it's occurring all the time. It's visible especially well when my girlfriend enters the server. Her movement is exactly the same as described above

**Comment by Gravlok** [comment]
I've noticed one thing. The game slows down to 0 FPS for couple of moments when I'm trying to open a custom compact chest, and while it's opened FPS are oscillating from 0 to 20. When closed FPS goes back to capped 30.

**Comment by Gravlok** [comment]
I found the cause of this behavior. Since, I'm a noob in these things, when the update 1.1.13 came out Jadecat deleted .bat file that runs server. I just hosted it via forge.xx.x.x.xx.jar file and that caused the lag/tick drops (the gui window was also laggy). Wrote .bat file by myself - gave it 4GB of ram and added nogiu. Works wonders. Case closed
