### ISSUE TITLE
World working yesterday, now not working. thermal expansion?

### ISSUE THREAD

**Issue by Jennasie** [jadedcat/AS2Configs#93]
http://pastebin.com/mCri2Whm

i never even closed my game. just save and quit to title then logged back in and im getting a crash report. i tried opening the world in mcedit to delete the blood tank and the other things i did last however it didnt seem to work. i also tried to wrench a portable tank and crashed. im unsure of what i should do to fix this.

**Comment by dmf444** [comment]
What blocks are you using to connect to the Blood Tanks?

**Comment by Jennasie** [comment]
The blood tanks were not connected to anything when I logged out. They were free standing. I did have a portable tank hooked to the altar with a fluiduct. I deleted those blocks as well.

**Comment by pjfranke** [comment]
This this to remove the erroring blocks: https://github.com/jadedcat/AS2Configs/issues/42#issuecomment-135049498

> Also, a possible fix, but recommended to take a back-up before doing so...
> In configs/forge.cfg, change "B:removeErroringEntities=false" to "B:removeErroringEntities=true", start your game. Once logged in, and it not crashing, stop the game and change the config back to false. Then play again like normal :)

**Comment by MarshMilo100** [comment]
closing due to inactitvy
