### ISSUE TITLE
Items not stacking properly

### ISSUE THREAD

**Issue by SirAzrael** [jadedcat/AS2Configs#97]
So I've been having this issue randomly for about a week now where just randomly items (primarily bread, although I've also noticed in my mob farm chest that it's doing it with rotten flesh and zombie brains sometimes as well) will stop stacking to 64 like they should. Bread and toast both only stack up to 8, and when I made bread sandwiches, they would only stack to 4. There's been several times where this happens, and it just seems to go away a with no obvious trigger, only to occur once more a day or two later

**Comment by MarshMilo100** [comment]
bread sandwiches do not exist, but i assume you mean toast sandwiches, either way i cannot confirm this issue.

**Comment by MarshMilo100** [comment]
Did you add any mods or change any configs?

**Comment by SirAzrael** [comment]
Yeah, sorry, toast sandwiches. And no, I hadn't changed anything in the pack at all

**Comment by MarshMilo100** [comment]
Are the items just these specific ones or if you spawn the same items from nei do they also not stack?

**Comment by SirAzrael** [comment]
I'm not sure, I never tried spawning items in from NEI

**Comment by MarshMilo100** [comment]
Just try it in another test world

**Comment by SirAzrael** [comment]
I'm not actually having the issue right now. I copied the backup of my worlds and just reinstalled the mod pack

**Comment by MarshMilo100** [comment]
how often does the issue occur?

**Comment by SirAzrael** [comment]
I'm not really sure. I think I've had it happen 3 or 4 times now in the last 2 1/2-3 weeks, twice it's just gone away without me doing anything, the other times I got sick of it and just reinstalled the pack. I haven't really noticed there being anything in particular that first causes it to happen

**Comment by MarshMilo100** [comment]
We will continue to look out for this type of issue or similar, if we notice it, then we will reopen the issue.
