### ISSUE TITLE
Dark oak to charcoal inconsistency

### ISSUE THREAD

**Issue by PixelSupreme** [jadedcat/AS2Configs#98]
I was growing dark oaks because I read that they produce more than one charcoal when smelted. But when I tried it I only got one charcoal per log.

I then found out that NEI lists two smelting recipes for dark oak logs, yielding one or four charcoal respectivley.

Right now it's not clear to me which way is intended. At least the duplicate recipes should be fixed to avoid confusion.

Pack version: 1.1.13

**Comment by MarshMilo100** [comment]
confirmed, this should be fixed in the next update. either both will yield a single charcoal or 4 charcoal.
