### ISSUE TITLE
Server files missing schematics for Town Builder

### ISSUE THREAD

**Issue by enarkay** [jadedcat/AS2Configs#99]
Version: 1.1.16 (but I've looked through all other versions of server files as well)

Watching jaded's guideline video for the server owners regarding the use of Town Builder, I've been told that "the map comes preloaded with several schematics  as long as you actually download the server files and don't just load up the map."

However, the server files DO NOT include any schematics for Town Builder, nor is there even a folder for Town Builder previously created under the mods folder. Therefore, when I try to use the Town Builder function it come back at me with the message saying that there are no schematics.

Does anyone have an idea where I can download the schematics, if there are any, or will this be fixed and the schematics included in future server files download?

**Comment by MarshMilo100** [comment]
i apologize, but how is town builder supposed to work? is there supposed to be a server side folder for schematics?

**Comment by enarkay** [comment]
Well, I'm not sure if I can elaborate any further but I'll try. So just like I said above, Jaded states in her [AgSkies 2: Server Setup] video that "the map comes preloaded with several schematics as long as you actually download the server files and don't just load up the map."

{Link to the video}
https://www.youtube.com/watch?v=hl8M3YlP5jA (she says it from 0:25~)

So according to what she said, the server files should have a Town Builder folder under the mods folder, and in that folder should be several default schematics which I can use to build pre-designed islands/houses.

However, like I said, there are no schematics included in the server files. I would've thought that there aren't any schematics in the first place and I have to make one/some myself, but seeing how Jaded describes in her video that there ARE preloaded schematics in the server files, I've been looking for them ever since. This does seem to make sense and fit her intention as well, since the chests on the default server map platform conatins recall stones and keys which people can use to divide up and spread out to play on different islands.

I hope I elaborated myself well enough:D

**Comment by cblair91** [comment]
Appears to be fixed with latest version.
